export type To20SkillId='addition-over-10-to-20'|'addition-table-to-20'|'subtraction-over-10-to-20'|'subtraction-table-to-20'|'word-problems-to-20';
export type To20Answer=number;
export const TO20_SKILL_LABELS:Record<To20SkillId,string>={'addition-over-10-to-20':'Cộng qua 10','addition-table-to-20':'Bảng cộng','subtraction-over-10-to-20':'Trừ qua 10','subtraction-table-to-20':'Bảng trừ','word-problems-to-20':'Bài toán thêm – bớt'};
type Base={id:string;skillId:To20SkillId;instruction:string;answers:number[];correctAnswer:number;hintSteps:[string,string,string];explanation:string};
export type AdditionQuestion=Base&{type:'addition';left:number;right:number;split:number;remainder:number};
export type SubtractionQuestion=Base&{type:'subtraction';whole:number;removed:number;toTen:number;remainder:number};
export type MissingQuestion=Base&{type:'missing';operation:'addition'|'subtraction';left:number;right:number;result:number;missing:'left'|'right'};
export type WordQuestion=Base&{type:'word';operation:'addition'|'subtraction';story:string;icon:string;first:number;change:number};
export type To20Question=AdditionQuestion|SubtractionQuestion|MissingQuestion|WordQuestion;
const OBJECTS=[{icon:'🍎',name:'quả táo'},{icon:'📘',name:'quyển truyện'},{icon:'⭐',name:'hình dán'},{icon:'🎈',name:'quả bóng bay'},{icon:'🐟',name:'chú cá'}]as const;
function ri(min:number,max:number){return Math.floor(Math.random()*(max-min+1))+min}function item<T>(a:readonly T[]):T{return a[ri(0,a.length-1)]}function shuffle<T>(a:readonly T[]){const r=[...a];for(let i=r.length-1;i>0;i--){const j=ri(0,i);[r[i],r[j]]=[r[j],r[i]]}return r}function id(t:string){return`${t}-${Date.now()}-${Math.random().toString(36).slice(2,9)}`}
function answers(correct:number){const s=new Set([correct]);for(const d of [1,-1,2,-2,3,-3]){const v=correct+d;if(v>=0&&v<=20)s.add(v);if(s.size===4)break}let v=0;while(s.size<4){s.add(v);v++}return shuffle([...s].slice(0,4))}
function additionValues(){const left=ri(6,9),right=ri(11-left,Math.min(9,20-left));return{left,right,result:left+right,split:10-left,remainder:right-(10-left)}}
function subtractionValues(){const whole=ri(11,18),toTen=whole-10,removed=ri(toTen+1,9);return{whole,removed,result:whole-removed,toTen,remainder:removed-toTen}}
function additionQuestion():AdditionQuestion{const{left,right,result,split,remainder}=additionValues();return{id:id('add20'),type:'addition',skillId:'addition-over-10-to-20',left,right,split,remainder,instruction:`Tính ${left} + ${right} bằng cách làm tròn 10.`,answers:answers(result),correctAnswer:result,hintSteps:[`${left} cần thêm ${split} để được 10.`,`Tách ${right} thành ${split} và ${remainder}.`,`10 + ${remainder} = ${result}.`],explanation:`Tách ${right} thành ${split} và ${remainder}: ${left} + ${split} = 10, rồi 10 + ${remainder} = ${result}.`}}
function subtractionQuestion():SubtractionQuestion{const{whole,removed,result,toTen,remainder}=subtractionValues();return{id:id('sub20'),type:'subtraction',skillId:'subtraction-over-10-to-20',whole,removed,toTen,remainder,instruction:`Tính ${whole} − ${removed} bằng cách trừ qua 10.`,answers:answers(result),correctAnswer:result,hintSteps:[`Từ ${whole}, trừ ${toTen} để về 10.`,`Còn phải trừ tiếp ${remainder}.`,`10 − ${remainder} = ${result}.`],explanation:`Tách ${removed} thành ${toTen} và ${remainder}: ${whole} − ${toTen} = 10, rồi 10 − ${remainder} = ${result}.`}}
function additionTableQuestion():MissingQuestion{const{left,right,result}=additionValues(),missing=item(['left','right']as const),correct=missing==='left'?left:right;return{id:id('add-table'),type:'missing',skillId:'addition-table-to-20',operation:'addition',left,right,result,missing,instruction:'Số nào thích hợp với ô trống?',answers:answers(correct),correctAnswer:correct,hintSteps:[`Tổng là ${result}.`,`Lấy ${result} trừ số hạng đã biết.`,`${left} + ${right} = ${result}, nên ô trống là ${correct}.`],explanation:`${left} + ${right} = ${result}, nên số còn thiếu là ${correct}.`}}
function subtractionTableQuestion():MissingQuestion{const{whole,removed,result}=subtractionValues(),missing=item(['left','right']as const),correct=missing==='left'?whole:removed;return{id:id('sub-table'),type:'missing',skillId:'subtraction-table-to-20',operation:'subtraction',left:whole,right:removed,result,missing,instruction:'Số nào thích hợp với ô trống?',answers:answers(correct),correctAnswer:correct,hintSteps:[missing==='left'?'Muốn tìm số bị trừ, lấy hiệu cộng số trừ.':'Muốn tìm số trừ, lấy số bị trừ trừ hiệu.',missing==='left'?`${result} + ${removed} = ${whole}.`:`${whole} − ${result} = ${removed}.`,`${whole} − ${removed} = ${result}, nên ô trống là ${correct}.`],explanation:`${whole} − ${removed} = ${result}, nên số còn thiếu là ${correct}.`}}
function wordQuestion():WordQuestion{const operation=item(['addition','subtraction']as const),object=item(OBJECTS);if(operation==='addition'){const{left,right,result}=additionValues();return{id:id('word-add20'),type:'word',skillId:'word-problems-to-20',operation,story:`Lan có ${left} ${object.name}, mẹ cho thêm ${right} ${object.name}. Lan có tất cả bao nhiêu ${object.name}?`,icon:object.icon,first:left,change:right,instruction:'Đọc bài toán và chọn đáp số.',answers:answers(result),correctAnswer:result,hintSteps:['“Cho thêm” và “tất cả” cho biết cần làm phép cộng.',`Phép tính là ${left} + ${right}.`,`${left} + ${right} = ${result}.`],explanation:`${left} + ${right} = ${result}. Đáp số: ${result} ${object.name}.`}}const{whole,removed,result}=subtractionValues();return{id:id('word-sub20'),type:'word',skillId:'word-problems-to-20',operation,story:`Có ${whole} ${object.name}, đã dùng ${removed} ${object.name}. Còn lại bao nhiêu ${object.name}?`,icon:object.icon,first:whole,change:removed,instruction:'Đọc bài toán và chọn đáp số.',answers:answers(result),correctAnswer:result,hintSteps:['“Đã dùng” và “còn lại” cho biết cần làm phép trừ.',`Phép tính là ${whole} − ${removed}.`,`${whole} − ${removed} = ${result}.`],explanation:`${whole} − ${removed} = ${result}. Đáp số: ${result} ${object.name}.`}}
type Factory=()=>To20Question;const core:Factory[]=[additionQuestion,additionTableQuestion,subtractionQuestion,subtractionTableQuestion,wordQuestion];function signature(q:To20Question){return`${q.type}-${q.instruction}-${q.correctAnswer}-${'left'in q?q.left:q.first}`}
export function generateTo20Questions(total:5|10|15=10){const used=new Set<string>(),plan=total===5?core:total===10?[...core,...core]:[...core,...core,...core];return shuffle(plan).map(f=>{let q=f(),k=signature(q),t=0;while(used.has(k)&&t<30){q=f();k=signature(q);t++}used.add(k);return q})}
