export type Arithmetic1000SkillId='addition-no-carry-1000'|'addition-carry-1000'|'subtraction-no-borrow-1000'|'subtraction-borrow-1000';
export const ARITHMETIC1000_SKILL_LABELS:Record<Arithmetic1000SkillId,string>={'addition-no-carry-1000':'Cộng không nhớ','addition-carry-1000':'Cộng có nhớ','subtraction-no-borrow-1000':'Trừ không nhớ','subtraction-borrow-1000':'Trừ có nhớ'};
export type Arithmetic1000Question={id:string;skillId:Arithmetic1000SkillId;operation:'addition'|'subtraction';left:number;right:number;answers:number[];correctAnswer:number;instruction:string;hintSteps:[string,string,string];explanation:string;carryRows:string[]};
function ri(a:number,b:number){return Math.floor(Math.random()*(b-a+1))+a}function shuffle<T>(a:readonly T[]){const r=[...a];for(let i=r.length-1;i>0;i--){const j=ri(0,i);[r[i],r[j]]=[r[j],r[i]]}return r}function id(t:string){return`${t}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}function answers(c:number){const s=new Set([c]);for(const d of shuffle([1,-1,10,-10,100,-100,9,-9])){const v=c+d;if(v>=0&&v<=1000)s.add(v);if(s.size===4)break}return shuffle([...s])}
function digits(n:number){return[Math.floor(n/100),Math.floor(n/10)%10,n%10]as const}
function additionCarries(a:number,b:number){const[ah,at,ao]=digits(a),[bh,bt,bo]=digits(b),ones=ao+bo,carry1=ones>=10?1:0,tens=at+bt+carry1,carry2=tens>=10?1:0;return{has:carry1>0||carry2>0,rows:[`${ao} + ${bo} = ${ones}: viết ${ones%10}${carry1?', nhớ 1':''}.`,`${at} + ${bt}${carry1?' + 1':''} = ${tens}: viết ${tens%10}${carry2?', nhớ 1':''}.`,`${ah} + ${bh}${carry2?' + 1':''} = ${ah+bh+carry2}.`]}}
function subtractionBorrows(a:number,b:number){const[ah,at,ao]=digits(a),[bh,bt,bo]=digits(b),borrow1=ao<bo?1:0,adjustedTens=at-borrow1,borrow2=adjustedTens<bt?1:0;return{has:borrow1>0||borrow2>0,rows:[borrow1?`${ao} không trừ được ${bo}, mượn 1 chục: ${ao+10} − ${bo} = ${ao+10-bo}.`:`${ao} − ${bo} = ${ao-bo}.`,borrow2?`${adjustedTens} không trừ được ${bt}, mượn 1 trăm: ${adjustedTens+10} − ${bt} = ${adjustedTens+10-bt}.`:`${adjustedTens} − ${bt} = ${adjustedTens-bt}.`,`${ah-borrow2} − ${bh} = ${ah-borrow2-bh}.`]}}
function additionNoCarry():Arithmetic1000Question{const ah=ri(1,7),bh=ri(1,9-ah),at=ri(0,9),bt=ri(0,9-at),ao=ri(0,9),bo=ri(0,9-ao),left=ah*100+at*10+ao,right=bh*100+bt*10+bo,result=left+right,info=additionCarries(left,right);return{id:id('add-no-carry1000'),skillId:'addition-no-carry-1000',operation:'addition',left,right,answers:answers(result),correctAnswer:result,instruction:'Đặt tính rồi tính. Kết quả nào đúng?',hintSteps:['Đặt các chữ số cùng hàng thẳng cột.',info.rows[0],`${left} + ${right} = ${result}.`],explanation:`Tính lần lượt từ phải sang trái: ${left} + ${right} = ${result}.`,carryRows:info.rows}}
function additionCarry():Arithmetic1000Question{let left=0,right=0,info=additionCarries(0,0);do{left=ri(100,899);right=ri(10,999-left);info=additionCarries(left,right)}while(!info.has);const result=left+right;return{id:id('add-carry1000'),skillId:'addition-carry-1000',operation:'addition',left,right,answers:answers(result),correctAnswer:result,instruction:'Đặt tính rồi tính phép cộng có nhớ.',hintSteps:['Cộng từ hàng đơn vị trước.',info.rows[0],`${info.rows[1]} Kết quả là ${result}.`],explanation:`${info.rows.join(' ')} Vậy ${left} + ${right} = ${result}.`,carryRows:info.rows}}
function subtractionNoBorrow():Arithmetic1000Question{const bh=ri(0,7),ah=ri(Math.max(1,bh),9),bt=ri(0,9),at=ri(bt,9),bo=ri(0,9),ao=ri(bo,9),left=ah*100+at*10+ao,right=bh*100+bt*10+bo,result=left-right,info=subtractionBorrows(left,right);return{id:id('sub-no-borrow1000'),skillId:'subtraction-no-borrow-1000',operation:'subtraction',left,right,answers:answers(result),correctAnswer:result,instruction:'Đặt tính rồi tính. Kết quả nào đúng?',hintSteps:['Đặt các chữ số cùng hàng thẳng cột.',info.rows[0],`${left} − ${right} = ${result}.`],explanation:`Trừ lần lượt từ phải sang trái: ${left} − ${right} = ${result}.`,carryRows:info.rows}}
function subtractionBorrow():Arithmetic1000Question{let left=0,right=0,info=subtractionBorrows(0,0);do{left=ri(100,999);right=ri(10,left-1);info=subtractionBorrows(left,right)}while(!info.has);const result=left-right;return{id:id('sub-borrow1000'),skillId:'subtraction-borrow-1000',operation:'subtraction',left,right,answers:answers(result),correctAnswer:result,instruction:'Đặt tính rồi tính phép trừ có nhớ.',hintSteps:['Trừ từ hàng đơn vị trước.',info.rows[0],`${info.rows[1]} Kết quả là ${result}.`],explanation:`${info.rows.join(' ')} Vậy ${left} − ${right} = ${result}.`,carryRows:info.rows}}
type Factory=()=>Arithmetic1000Question;const plan:Factory[]=[additionNoCarry,additionCarry,subtractionNoBorrow,subtractionBorrow];export function generateArithmetic1000Questions(total:5|10|15=10){return shuffle(Array.from({length:total},(_,i)=>plan[i%4])).map(factory=>factory())}
