export type Grade2TimeSkillId='hours-minutes'|'days-months'|'read-calendar-grade-2';
export type Grade2TimeAnswer=string;
export const GRADE2_TIME_SKILL_LABELS:Record<Grade2TimeSkillId,string>={'hours-minutes':'Giờ và phút','days-months':'Ngày và tháng','read-calendar-grade-2':'Xem lịch'};
export const WEEKDAYS=['Thứ Hai','Thứ Ba','Thứ Tư','Thứ Năm','Thứ Sáu','Thứ Bảy','Chủ nhật']as const;
type Base={id:string;skillId:Grade2TimeSkillId;instruction:string;answers:string[];correctAnswer:string;hintSteps:[string,string,string];explanation:string};
export type ClockQuestion=Base&{type:'clock';hour:number;minute:number};
export type ConversionQuestion=Base&{type:'conversion';amount:number;mode:'hour-to-minute'|'minute-to-hour'};
export type MonthQuestion=Base&{type:'month';month:number;mode:'days'|'before'|'after'};
export type CalendarQuestion=Base&{type:'calendar';month:number;daysInMonth:number;startWeekday:number;targetDate:number;mode:'weekday'|'later-date';distance:number};
export type Grade2TimeQuestion=ClockQuestion|ConversionQuestion|MonthQuestion|CalendarQuestion;
const MONTH_DAYS=[31,28,31,30,31,30,31,31,30,31,30,31];
function ri(min:number,max:number){return Math.floor(Math.random()*(max-min+1))+min}function shuffle<T>(a:readonly T[]){const r=[...a];for(let i=r.length-1;i>0;i--){const j=ri(0,i);[r[i],r[j]]=[r[j],r[i]]}return r}function id(t:string){return`${t}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}function options(correct:string,others:string[]){return shuffle([correct,...shuffle(others.filter(value=>value!==correct)).slice(0,3)])}
function timeText(hour:number,minute:number){return`${hour} giờ ${String(minute).padStart(2,'0')} phút`}
function clockQuestion():ClockQuestion{const hour=ri(1,12),minute=ri(0,11)*5,correct=timeText(hour,minute),otherMinutes=shuffle([0,5,10,15,20,25,30,35,40,45,50,55].filter(v=>v!==minute)).slice(0,3);return{id:id('clock2'),type:'clock',skillId:'hours-minutes',hour,minute,instruction:'Đồng hồ chỉ mấy giờ, mấy phút?',answers:shuffle([correct,...otherMinutes.map(value=>timeText(value===0&&minute!==0?(hour%12)+1:hour,value))]),correctAnswer:correct,hintSteps:['Kim dài chỉ phút: mỗi số tương ứng 5 phút.',`Kim dài chỉ ${minute===0?12:minute/5}, nên là ${minute} phút.`,`Kim ngắn đang ở khoảng số ${hour}. Đồng hồ chỉ ${correct}.`],explanation:`Kim phút chỉ ${minute} phút và kim giờ chỉ ${hour} giờ, nên đồng hồ chỉ ${correct}.`}}
function conversionQuestion():ConversionQuestion{const mode=shuffle(['hour-to-minute','minute-to-hour']as const)[0],amount=ri(1,3);if(mode==='hour-to-minute'){const correct=`${amount*60} phút`;return{id:id('convert'),type:'conversion',skillId:'hours-minutes',mode,amount,instruction:`${amount} giờ bằng bao nhiêu phút?`,answers:options(correct,[`${amount*30} phút`,`${amount*60+10} phút`,`${amount*100} phút`,`${amount+60} phút`]),correctAnswer:correct,hintSteps:['1 giờ bằng 60 phút.',`Có ${amount} giờ nên lấy 60 × ${amount}.`,`60 × ${amount} = ${amount*60} phút.`],explanation:`${amount} giờ = ${amount} × 60 = ${amount*60} phút.`}}const minutes=amount*60,correct=`${amount} giờ`;return{id:id('convert'),type:'conversion',skillId:'hours-minutes',mode,amount:minutes,instruction:`${minutes} phút bằng bao nhiêu giờ?`,answers:options(correct,[`${amount+1} giờ`,`${Math.max(1,amount-1)} giờ`,`${minutes} giờ`,'60 giờ']),correctAnswer:correct,hintSteps:['60 phút bằng 1 giờ.',`Hãy xem ${minutes} có bao nhiêu nhóm 60 phút.`,`${minutes} : 60 = ${amount} giờ.`],explanation:`${minutes} phút = ${minutes} : 60 = ${amount} giờ.`}}
function monthQuestion():MonthQuestion{const month=ri(1,12),mode=shuffle(['days','before','after']as const)[0];if(mode==='days'){const correct=`${MONTH_DAYS[month-1]} ngày`;return{id:id('month-days'),type:'month',skillId:'days-months',month,mode,instruction:`Tháng ${month} có bao nhiêu ngày?`,answers:options(correct,['28 ngày','29 ngày','30 ngày','31 ngày']),correctAnswer:correct,hintSteps:['Nhớ lại số ngày của từng tháng.',month===2?'Tháng 2 thường có 28 ngày.':'Các tháng có 30 hoặc 31 ngày.',`Tháng ${month} có ${MONTH_DAYS[month-1]} ngày.`],explanation:`Trong năm thông thường, tháng ${month} có ${MONTH_DAYS[month-1]} ngày.`}}const target=mode==='before'?(month===1?12:month-1):(month===12?1:month+1),correct=`Tháng ${target}`;return{id:id('month-order'),type:'month',skillId:'days-months',month,mode,instruction:`Tháng liền ${mode==='before'?'trước':'sau'} tháng ${month} là tháng nào?`,answers:options(correct,[`Tháng ${month}`,`Tháng ${target===12?11:target+1}`,`Tháng ${target===1?2:target-1}`,'Tháng 6']),correctAnswer:correct,hintSteps:['Một năm có 12 tháng theo thứ tự từ tháng 1 đến tháng 12.',`Tìm tháng đứng ngay ${mode==='before'?'trước':'sau'} tháng ${month}.`,`Đáp án là tháng ${target}.`],explanation:`Tháng liền ${mode==='before'?'trước':'sau'} tháng ${month} là tháng ${target}.`}}
function calendarQuestion():CalendarQuestion{const month=ri(1,12),daysInMonth=MONTH_DAYS[month-1],startWeekday=ri(0,6),mode=shuffle(['weekday','later-date']as const)[0],distance=mode==='later-date'?ri(2,7):0,targetDate=ri(1,daysInMonth-distance);if(mode==='weekday'){const weekday=WEEKDAYS[(startWeekday+targetDate-1)%7];return{id:id('calendar-weekday'),type:'calendar',skillId:'read-calendar-grade-2',month,daysInMonth,startWeekday,targetDate,mode,distance,instruction:`Ngày ${targetDate} tháng ${month} là thứ mấy?`,answers:options(weekday,WEEKDAYS.filter(day=>day!==weekday)),correctAnswer:weekday,hintSteps:['Tìm ngày được hỏi trên tờ lịch.','Nhìn thẳng lên tên thứ ở đầu cột.',`Ngày ${targetDate} nằm ở cột ${weekday}.`],explanation:`Ngày ${targetDate} tháng ${month} nằm ở cột ${weekday}.`}}const later=targetDate+distance,correct=`Ngày ${later}`;return{id:id('calendar-later'),type:'calendar',skillId:'read-calendar-grade-2',month,daysInMonth,startWeekday,targetDate,mode,distance,instruction:`Sau ngày ${targetDate} tháng ${month} ${distance} ngày là ngày nào?`,answers:options(correct,[`Ngày ${later-1}`,`Ngày ${later+1}`,`Ngày ${targetDate-distance}`,`Ngày ${targetDate}`]),correctAnswer:correct,hintSteps:['Đặt ngón tay vào ngày bắt đầu trên lịch.',`Đếm tiến thêm ${distance} ô, không tính lại ngày bắt đầu.`,`Đến ô ngày ${later}.`],explanation:`Đếm tiếp ${distance} ngày sau ngày ${targetDate}, ta đến ngày ${later} tháng ${month}.`}}
type Factory=()=>Grade2TimeQuestion;const factories:Factory[]=[clockQuestion,conversionQuestion,monthQuestion,calendarQuestion,calendarQuestion];export function generateGrade2TimeQuestions(total:5|10|15=10){return shuffle(Array.from({length:total},(_,i)=>factories[i%factories.length])).map(factory=>factory())}
