export type Grade2FinalSkillId='final-numbers-arithmetic'|'final-multiply-divide'|'final-geometry'|'final-measurement'|'final-data-probability';
export type Grade2FinalAnswer=number|string;
export const GRADE2_FINAL_SKILL_LABELS:Record<Grade2FinalSkillId,string>={'final-numbers-arithmetic':'Số và phép tính','final-multiply-divide':'Nhân và chia','final-geometry':'Hình học','final-measurement':'Đo lường và tiền','final-data-probability':'Dữ liệu và xác suất'};
type Base={id:string;skillId:Grade2FinalSkillId;instruction:string;answers:Grade2FinalAnswer[];correctAnswer:Grade2FinalAnswer;hintSteps:[string,string,string];explanation:string};
export type ArithmeticQ=Base&{type:'arithmetic';left:number;right:number;operation:'+'|'−'};
export type SpecialNumberQ=Base&{type:'special-number';label:string};
export type MultiplyQ=Base&{type:'multiply-divide';left:number;right:number;operation:'×'|':'};
export type GeometryQ=Base&{type:'geometry';mode:'polygon'|'solid'|'broken';sides?:3|4|5;solid?:'cylinder'|'sphere';lengths?:number[]};
export type MeasurementQ=Base&{type:'measurement';mode:'length'|'mass'|'capacity'|'time'|'money';icon:string;display:string};
export type DataQ=Base&{type:'data';labels:string[];icons:string[];counts:number[];target:number};
export type ProbabilityQ=Base&{type:'probability';balls:string[];targetColor:string;outcome:string};
export type Grade2FinalQuestion=ArithmeticQ|SpecialNumberQ|MultiplyQ|GeometryQ|MeasurementQ|DataQ|ProbabilityQ;
function ri(a:number,b:number){return Math.floor(Math.random()*(b-a+1))+a}function pick<T>(a:readonly T[]){return a[ri(0,a.length-1)]}function shuffle<T>(a:readonly T[]){const r=[...a];for(let i=r.length-1;i>0;i--){const j=ri(0,i);[r[i],r[j]]=[r[j],r[i]]}return r}function id(t:string){return`${t}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}function nums(c:number,min=0,max=1000){const s=new Set([c]);for(const d of shuffle([1,-1,10,-10,100,-100,2,-2,5,-5])){const v=c+d;if(v>=min&&v<=max)s.add(v);if(s.size===4)break}return shuffle([...s])}function choices(c:string,others:string[]){return shuffle([c,...shuffle([...new Set(others.filter(v=>v!==c))]).slice(0,3)])}function money(v:number){return`${v.toLocaleString('vi-VN')} đồng`}
function numbersArithmetic():ArithmeticQ|SpecialNumberQ{if(Math.random()<.25){const list=[['Số lớn nhất có ba chữ số',999],['Số nhỏ nhất có ba chữ số',100],['Số chẵn lớn nhất có ba chữ số',998],['Số lẻ nhỏ nhất có ba chữ số',101]]as const,[label,correct]=pick(list);return{id:id('final-special'),type:'special-number',skillId:'final-numbers-arithmetic',label,instruction:`${label} là số nào?`,answers:nums(correct,100,999),correctAnswer:correct,hintSteps:['Số có ba chữ số nằm từ 100 đến 999.',label.includes('chẵn')?'Số chẵn có chữ số tận cùng là 0, 2, 4, 6 hoặc 8.':label.includes('lẻ')?'Số lẻ có chữ số tận cùng là 1, 3, 5, 7 hoặc 9.':'Xét hai đầu của phạm vi.',`${label} là ${correct}.`],explanation:`${label} là ${correct}.`}}const operation=pick(['+','−']as const);let left=ri(100,899),right=operation==='+'?ri(10,999-left):ri(10,left),correct=operation==='+'?left+right:left-right;return{id:id('final-arith'),type:'arithmetic',skillId:'final-numbers-arithmetic',left,right,operation,instruction:'Đặt tính rồi chọn kết quả đúng.',answers:nums(correct),correctAnswer:correct,hintSteps:['Đặt các chữ số cùng hàng thẳng cột.','Tính từ hàng đơn vị trước.',`${left} ${operation} ${right} = ${correct}.`],explanation:`${left} ${operation} ${right} = ${correct}.`}}
function multiplyDivide():MultiplyQ{const factor=pick([2,5]as const),times=ri(1,10),product=factor*times,operation=pick(['×',':']as const),left=operation==='×'?factor:product,right=operation==='×'?times:factor,correct=operation==='×'?product:times;return{id:id('final-md'),type:'multiply-divide',skillId:'final-multiply-divide',left,right,operation,instruction:'Tính nhẩm rồi chọn kết quả.',answers:nums(correct,0,50),correctAnswer:correct,hintSteps:[`Liên hệ bảng nhân ${factor}.`,`${factor} × ${times} = ${product}.`,`${left} ${operation} ${right} = ${correct}.`],explanation:`${left} ${operation} ${right} = ${correct}.`}}
function geometry():GeometryQ{const mode=pick(['polygon','solid','broken']as const);if(mode==='polygon'){const sides=pick([3,4,5]as const);return{id:id('final-polygon'),type:'geometry',skillId:'final-geometry',mode,sides,instruction:'Hình dưới đây có bao nhiêu cạnh?',answers:shuffle([3,4,5,6]),correctAnswer:sides,hintSteps:['Đi theo đường bao quanh hình.','Đếm mỗi đoạn thẳng một lần.',`Hình có ${sides} cạnh.`],explanation:`Đếm được ${sides} cạnh.`}}if(mode==='solid'){const solid=pick(['cylinder','sphere']as const),correct=solid==='cylinder'?'Khối trụ':'Khối cầu';return{id:id('final-solid'),type:'geometry',skillId:'final-geometry',mode,solid,instruction:'Hình khối dưới đây có tên là gì?',answers:shuffle(['Khối trụ','Khối cầu','Khối lập phương','Khối hộp chữ nhật']),correctAnswer:correct,hintSteps:['Quan sát mặt phẳng và mặt cong.',solid==='cylinder'?'Khối có hai mặt phẳng hình tròn.':'Khối tròn đều, không có mặt phẳng.',`Đây là ${correct.toLowerCase()}.`],explanation:`Đây là ${correct.toLowerCase()}.`}}const lengths=Array.from({length:ri(3,4)},()=>ri(2,7)),total=lengths.reduce((s,v)=>s+v,0);return{id:id('final-broken'),type:'geometry',skillId:'final-geometry',mode,lengths,instruction:'Đường gấp khúc dài bao nhiêu xăng-ti-mét?',answers:nums(total,1,40),correctAnswer:total,hintSteps:['Đọc độ dài từng đoạn.',`Cộng ${lengths.join(' + ')}.`,`Tổng là ${total} cm.`],explanation:`${lengths.join(' + ')} = ${total} cm.`}}
function measurement():MeasurementQ{const mode=pick(['length','mass','capacity','time','money']as const);if(mode==='length'){const km=ri(2,8),correct=km*1000;return{id:id('final-length'),type:'measurement',skillId:'final-measurement',mode,icon:'📏',display:`${km} km = ? m`,instruction:`${km} km bằng bao nhiêu mét?`,answers:shuffle([...new Set([correct,(km-1)*1000,(km+1)*1000,km*100])]),correctAnswer:correct,hintSteps:['1 km = 1 000 m.',`Lấy ${km} nhân 1 000.`,`Kết quả là ${correct} m.`],explanation:`${km} km = ${correct} m.`}}if(mode==='time'){const hours=ri(1,3),correct=hours*60;return{id:id('final-time'),type:'measurement',skillId:'final-measurement',mode,icon:'⏱️',display:`${hours} giờ = ? phút`,instruction:`${hours} giờ bằng bao nhiêu phút?`,answers:shuffle([...new Set([correct,hours*30,correct+30,hours*100])]),correctAnswer:correct,hintSteps:['1 giờ = 60 phút.',`Lấy ${hours} nhân 60.`,`Kết quả là ${correct} phút.`],explanation:`${hours} giờ = ${correct} phút.`}}if(mode==='money'){const notes=shuffle([1000,2000,5000,10000]).slice(0,ri(2,3)),total=notes.reduce((s,v)=>s+v,0);return{id:id('final-money'),type:'measurement',skillId:'final-measurement',mode,icon:'💵',display:notes.map(money).join(' + '),instruction:'Tổng số tiền là bao nhiêu?',answers:choices(money(total),[money(total+1000),money(Math.max(0,total-1000)),money(total+2000)]),correctAnswer:money(total),hintSteps:['Đọc từng mệnh giá.','Cộng các mệnh giá lại.',`Tổng là ${money(total)}.`],explanation:`Tổng số tiền là ${money(total)}.`}}const unit=mode==='mass'?'kg':'l',first=ri(10,30),change=ri(2,9),correct=first+change,icon=mode==='mass'?'⚖️':'🪣';return{id:id('final-measure'),type:'measurement',skillId:'final-measurement',mode,icon,display:`${first} ${unit} + ${change} ${unit} = ?`,instruction:'Kết quả phép tính đo lường là bao nhiêu?',answers:nums(correct,1,50),correctAnswer:correct,hintSteps:[`Các số cùng đơn vị ${unit}.`,`Cộng ${first} + ${change}.`,`Kết quả là ${correct} ${unit}.`],explanation:`${first} ${unit} + ${change} ${unit} = ${correct} ${unit}.`}}
function dataProbability():DataQ|ProbabilityQ{if(Math.random()<.6){const items=shuffle([['Táo','🍎'],['Cam','🍊'],['Dâu','🍓']]as const),counts=shuffle([3,4,5,6,7]).slice(0,3),target=ri(0,2),correct=counts[target];return{id:id('final-data'),type:'data',skillId:'final-data-probability',labels:items.map(x=>x[0]),icons:items.map(x=>x[1]),counts,target,instruction:`Biểu đồ có bao nhiêu ${items[target][0].toLowerCase()}?`,answers:nums(correct,0,10),correctAnswer:correct,hintSteps:[`Tìm hàng ${items[target][0]}.`,'Mỗi hình biểu thị một quả.',`Đếm được ${correct} quả.`],explanation:`Có ${correct} ${items[target][0].toLowerCase()}.`}}const target=pick([{name:'đỏ',css:'bg-red-500'},{name:'xanh',css:'bg-blue-500'},{name:'vàng',css:'bg-yellow-400'}]),outcome=pick(['Chắc chắn','Có thể','Không thể']as const),others=[{name:'đỏ',css:'bg-red-500'},{name:'xanh',css:'bg-blue-500'},{name:'vàng',css:'bg-yellow-400'}].filter(c=>c.name!==target.name);let balls:string[]=[];if(outcome==='Chắc chắn')balls=Array(5).fill(target.css);else if(outcome==='Không thể')balls=Array.from({length:5},()=>pick(others).css);else balls=shuffle([target.css,target.css,...Array.from({length:4},()=>pick(others).css)]);return{id:id('final-probability'),type:'probability',skillId:'final-data-probability',balls,targetColor:target.name,outcome,instruction:`Lấy một bóng bất kỳ. Khả năng lấy được bóng màu ${target.name} là gì?`,answers:shuffle(['Chắc chắn','Có thể','Không thể']),correctAnswer:outcome,hintSteps:['Quan sát các màu bóng trong túi.',outcome==='Chắc chắn'?'Tất cả đều đúng màu được hỏi.':outcome==='Không thể'?'Không có màu được hỏi.':'Có màu được hỏi và còn màu khác.',`Đáp án là ${outcome}.`],explanation:`Khả năng lấy bóng màu ${target.name} là ${outcome.toLowerCase()}.`}}
type Factory=()=>Grade2FinalQuestion;const plan:Factory[]=[numbersArithmetic,multiplyDivide,geometry,measurement,dataProbability];export function generateGrade2FinalQuestions(total:5|10|15=10){return shuffle(Array.from({length:total},(_,i)=>plan[i%5])).map(factory=>factory())}
