export type G2S1SkillId='arithmetic'|'geometry'|'measurement'|'time-calendar'|'word-problem';
export type G2S1Answer=number|string;
export const G2S1_SKILL_LABELS:Record<G2S1SkillId,string>={arithmetic:'Ôn phép tính',geometry:'Ôn hình phẳng',measurement:'Ôn đo lường','time-calendar':'Ôn giờ và lịch','word-problem':'Bài toán tổng hợp'};
type Base={id:string;skillId:G2S1SkillId;instruction:string;answers:G2S1Answer[];correctAnswer:G2S1Answer;hintSteps:[string,string,string];explanation:string};
export type ArithmeticQ=Base&{type:'arithmetic';operation:'+'|'−';left:number;right:number};
export type GeometryQ=Base&{type:'geometry';mode:'polygon'|'broken';sides?:3|4|5;lengths?:number[]};
export type MeasureQ=Base&{type:'measurement';unit:'kg'|'l';icon:string;first:number;change:number;operation:'+'|'−'};
export type ClockQ=Base&{type:'clock';hour:number;minute:number};
export type CalendarQ=Base&{type:'calendar';month:number;days:number;start:number;date:number};
export type WordQ=Base&{type:'word';story:string;icon:string;first:number;change:number;operation:'+'|'−'};
export type G2S1Question=ArithmeticQ|GeometryQ|MeasureQ|ClockQ|CalendarQ|WordQ;
const DAYS=['Thứ Hai','Thứ Ba','Thứ Tư','Thứ Năm','Thứ Sáu','Thứ Bảy','Chủ nhật']as const;
function ri(a:number,b:number){return Math.floor(Math.random()*(b-a+1))+a}function pick<T>(a:readonly T[]){return a[ri(0,a.length-1)]}function shuffle<T>(a:readonly T[]){const r=[...a];for(let i=r.length-1;i>0;i--){const j=ri(0,i);[r[i],r[j]]=[r[j],r[i]]}return r}function id(t:string){return`${t}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}function nums(c:number,max=100){const s=new Set([c]);for(const d of shuffle([1,-1,2,-2,10,-10,5,-5])){const v=c+d;if(v>=0&&v<=max)s.add(v);if(s.size===4)break}return shuffle([...s])}function texts(correct:string,others:string[]){return shuffle([correct,...shuffle([...new Set(others.filter(x=>x!==correct))]).slice(0,3)])}
function arithmetic():ArithmeticQ{const operation=pick(['+','−']as const);let left=0,right=0,result=0;if(operation==='+'){do{left=ri(8,79);right=ri(3,99-left)}while(left%10+right%10<10);result=left+right}else{do{left=ri(20,99);right=ri(2,left-1)}while(left%10>=right%10);result=left-right}return{id:id('arith'),type:'arithmetic',skillId:'arithmetic',operation,left,right,instruction:'Đặt tính rồi chọn kết quả đúng.',answers:nums(result),correctAnswer:result,hintSteps:['Đặt các chữ số cùng hàng thẳng cột.','Tính từ hàng đơn vị trước.',`${left} ${operation} ${right} = ${result}.`],explanation:`${left} ${operation} ${right} = ${result}.`}}
function geometry():GeometryQ{const mode=pick(['polygon','broken']as const);if(mode==='polygon'){const sides=pick([3,4,5]as const);return{id:id('geo'),type:'geometry',skillId:'geometry',mode,sides,instruction:'Hình dưới đây có bao nhiêu cạnh?',answers:shuffle([3,4,5,6]),correctAnswer:sides,hintSteps:['Đi theo đường bao của hình.','Mỗi đoạn thẳng trên đường bao là một cạnh.',`Hình có ${sides} cạnh${sides===4?', là hình tứ giác':''}.`],explanation:`Đếm được ${sides} cạnh${sides===4?', nên đây là hình tứ giác':''}.`}}const lengths=Array.from({length:ri(3,4)},()=>ri(2,7)),total=lengths.reduce((s,v)=>s+v,0);return{id:id('broken'),type:'geometry',skillId:'geometry',mode,lengths,instruction:'Đường gấp khúc dài bao nhiêu xăng-ti-mét?',answers:nums(total,40),correctAnswer:total,hintSteps:['Đọc độ dài trên từng đoạn thẳng.',`Thực hiện phép cộng ${lengths.join(' + ')}.`,`Tổng là ${total} cm.`],explanation:`${lengths.join(' + ')} = ${total} cm.`}}
function measurement():MeasureQ{const unit=pick(['kg','l']as const),operation=pick(['+','−']as const),first=ri(8,30),change=ri(2,Math.min(9,operation==='−'?first-1:9)),result=operation==='+'?first+change:first-change,icon=unit==='kg'?'⚖️':'🪣';return{id:id('measure'),type:'measurement',skillId:'measurement',unit,icon,first,change,operation,instruction:`Kết quả của phép tính đo lường là bao nhiêu?`,answers:nums(result,50),correctAnswer:result,hintSteps:[`Hai số cùng đơn vị ${unit}.`,`Thực hiện ${operation==='+'?'phép cộng':'phép trừ'} ${first} ${operation} ${change}.`,`${first} ${operation} ${change} = ${result} ${unit}.`],explanation:`${first} ${unit} ${operation} ${change} ${unit} = ${result} ${unit}.`}}
function timeCalendar():ClockQ|CalendarQ{if(Math.random()<.55){const hour=ri(1,12),minute=ri(0,11)*5,correct=`${hour} giờ ${String(minute).padStart(2,'0')} phút`;return{id:id('clock'),type:'clock',skillId:'time-calendar',hour,minute,instruction:'Đồng hồ chỉ mấy giờ, mấy phút?',answers:texts(correct,[`${hour} giờ ${String((minute+5)%60).padStart(2,'0')} phút`,`${hour} giờ ${String((minute+10)%60).padStart(2,'0')} phút`,`${hour%12+1} giờ ${String(minute).padStart(2,'0')} phút`]),correctAnswer:correct,hintSteps:['Kim dài cho biết số phút, mỗi số là 5 phút.',`Kim dài chỉ ${minute} phút.`,`Kim ngắn chỉ khoảng số ${hour}.`],explanation:`Đồng hồ chỉ ${correct}.`}}const month=ri(1,12),days=pick([28,30,31]),start=ri(0,6),date=ri(1,days),correct=DAYS[(start+date-1)%7];return{id:id('calendar'),type:'calendar',skillId:'time-calendar',month,days,start,date,instruction:`Ngày ${date} tháng ${month} là thứ mấy?`,answers:texts(correct,DAYS.filter(d=>d!==correct)),correctAnswer:correct,hintSteps:['Tìm ngày được hỏi trên lịch.','Nhìn lên đầu cột chứa ngày đó.',`Ngày ${date} nằm ở cột ${correct}.`],explanation:`Ngày ${date} tháng ${month} là ${correct}.`}}
function word():WordQ{const object=pick([{icon:'📚',name:'quyển sách'},{icon:'🍊',name:'quả cam'},{icon:'🎈',name:'quả bóng bay'}]),operation=pick(['+','−']as const),first=ri(20,70),change=ri(5,Math.min(25,operation==='−'?first-1:100-first)),result=operation==='+'?first+change:first-change,story=operation==='+'?`Thư viện có ${first} ${object.name}, mua thêm ${change} ${object.name}. Thư viện có tất cả bao nhiêu ${object.name}?`:`Cửa hàng có ${first} ${object.name}, đã bán ${change} ${object.name}. Cửa hàng còn lại bao nhiêu ${object.name}?`;return{id:id('word'),type:'word',skillId:'word-problem',story,icon:object.icon,first,change,operation,instruction:'Đọc bài toán và chọn đáp số đúng.',answers:nums(result),correctAnswer:result,hintSteps:[operation==='+'?'“Thêm” và “tất cả” cho biết cần cộng.':'“Đã bán” và “còn lại” cho biết cần trừ.',`Phép tính: ${first} ${operation} ${change}.`,`Kết quả là ${result}.`],explanation:`${first} ${operation} ${change} = ${result}.`}}
type Factory=()=>G2S1Question;const plan:Factory[]=[arithmetic,geometry,measurement,timeCalendar,word];export function generateG2S1Questions(total:5|10|15=10){return shuffle(Array.from({length:total},(_,i)=>plan[i%5])).map(f=>f())}
export{DAYS as G2S1_WEEKDAYS};
