export type LengthMoneySkillId='length-units-grade-2'|'measure-length-grade-2'|'vietnamese-money';
export type LengthMoneyAnswer=number|string;
export const LENGTH_MONEY_SKILL_LABELS:Record<LengthMoneySkillId,string>={'length-units-grade-2':'Đề-xi-mét, mét, ki-lô-mét','measure-length-grade-2':'Đo và ước lượng','vietnamese-money':'Tiền Việt Nam'};
type Base={id:string;skillId:LengthMoneySkillId;instruction:string;answers:LengthMoneyAnswer[];correctAnswer:LengthMoneyAnswer;hintSteps:[string,string,string];explanation:string};
export type UnitQ=Base&{type:'unit';icon:string;object:string;value:number;unit:'dm'|'m'|'km'};
export type ConvertQ=Base&{type:'convert';from:number;fromUnit:'m'|'km';toUnit:'dm'|'m'};
export type RulerQ=Base&{type:'ruler';length:number;unit:'dm'|'m'};
export type EstimateQ=Base&{type:'estimate';icon:string;object:string};
export type MoneyQ=Base&{type:'money';mode:'recognize'|'count'|'buy';notes:number[];price?:number};
export type LengthMoneyQuestion=UnitQ|ConvertQ|RulerQ|EstimateQ|MoneyQ;
const MONEY=[1000,2000,5000,10000,20000]as const;
const OBJECTS=[{icon:'✏️',object:'chiếc bút chì',value:2,unit:'dm' as const},{icon:'🚪',object:'chiều cao cánh cửa',value:2,unit:'m' as const},{icon:'🏫',object:'chiều dài lớp học',value:8,unit:'m' as const},{icon:'🛣️',object:'quãng đường giữa hai xã',value:5,unit:'km' as const},{icon:'🚴',object:'quãng đường đạp xe',value:3,unit:'km' as const},{icon:'🛏️',object:'chiều dài chiếc giường',value:2,unit:'m' as const}]as const;
function ri(a:number,b:number){return Math.floor(Math.random()*(b-a+1))+a}function pick<T>(a:readonly T[]){return a[ri(0,a.length-1)]}function shuffle<T>(a:readonly T[]){const r=[...a];for(let i=r.length-1;i>0;i--){const j=ri(0,i);[r[i],r[j]]=[r[j],r[i]]}return r}function id(t:string){return`${t}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}function nums(c:number,min=0,max=10000){const s=new Set([c]);for(const d of shuffle([1,-1,2,-2,5,-5,10,-10,1000,-1000])){const v=c+d;if(v>=min&&v<=max)s.add(v);if(s.size===4)break}return shuffle([...s])}function money(v:number){return`${v.toLocaleString('vi-VN')} đồng`}
function moneyAnswers(c:number){const s=new Set([c]);for(const d of shuffle([1000,-1000,2000,-2000,5000,-5000])){const v=c+d;if(v>=0&&v<=50000)s.add(v);if(s.size===4)break}return shuffle([...s]).map(money)}
function unitQuestion():UnitQ{const item=pick(OBJECTS);return{id:id('unit-length'),type:'unit',skillId:'length-units-grade-2',...item,instruction:`Đơn vị nào thích hợp để đo ${item.object}?`,answers:shuffle(['dm','m','km']),correctAnswer:item.unit,hintSteps:['Nghĩ xem đồ vật hoặc quãng đường dài khoảng bao nhiêu.',item.unit==='dm'?'Đồ vật nhỏ hơn 1 mét có thể đo bằng đề-xi-mét.':item.unit==='m'?'Đồ vật hoặc căn phòng thường đo bằng mét.':'Quãng đường xa thường đo bằng ki-lô-mét.',`Đơn vị phù hợp là ${item.unit}.`],explanation:`${item.object[0].toUpperCase()+item.object.slice(1)} phù hợp đo bằng ${item.unit}.`}}
function convertQuestion():ConvertQ{const fromUnit=pick(['m','km']as const),toUnit=fromUnit==='m'?'dm':'m',from=ri(1,8),correct=from*(fromUnit==='m'?10:1000);return{id:id('convert-length'),type:'convert',skillId:'length-units-grade-2',from,fromUnit,toUnit,instruction:`${from} ${fromUnit} bằng bao nhiêu ${toUnit}?`,answers:nums(correct,1,10000),correctAnswer:correct,hintSteps:[fromUnit==='m'?'1 m = 10 dm.':'1 km = 1 000 m.',`Lấy ${from} nhân với ${fromUnit==='m'?10:'1 000'}.`,`Kết quả là ${correct} ${toUnit}.`],explanation:`${from} ${fromUnit} = ${correct} ${toUnit}.`}}
function rulerQuestion():RulerQ{const unit=pick(['dm','m']as const),length=ri(2,9);return{id:id('ruler'),type:'ruler',skillId:'measure-length-grade-2',length,unit,instruction:`Đoạn thẳng dài bao nhiêu ${unit}?`,answers:nums(length,1,12),correctAnswer:length,hintSteps:['Điểm đầu của đoạn thẳng ở vạch 0.','Điểm cuối nằm ở vạch mang số nào?',`Điểm cuối ở vạch ${length}, nên đoạn thẳng dài ${length} ${unit}.`],explanation:`Đoạn thẳng bắt đầu ở 0 và kết thúc ở ${length}, nên dài ${length} ${unit}.`}}
function estimateQuestion():EstimateQ{const item=pick(OBJECTS),correct=`${item.value} ${item.unit}`;const wrong=shuffle(OBJECTS.filter(x=>`${x.value} ${x.unit}`!==correct)).slice(0,3).map(x=>`${x.value} ${x.unit}`);return{id:id('estimate'),type:'estimate',skillId:'measure-length-grade-2',icon:item.icon,object:item.object,instruction:`Độ dài nào hợp lý nhất với ${item.object}?`,answers:shuffle([correct,...wrong]),correctAnswer:correct,hintSteps:['Hình dung kích thước ngoài đời thật.','Loại các đáp án có đơn vị không phù hợp.',`Ước lượng hợp lý là ${correct}.`],explanation:`${item.object[0].toUpperCase()+item.object.slice(1)} dài khoảng ${correct}.`}}
function moneyQuestion():MoneyQ{const mode=pick(['recognize','count','buy']as const);if(mode==='recognize'){const note=pick(MONEY);return{id:id('money-recognize'),type:'money',skillId:'vietnamese-money',mode,notes:[note],instruction:'Tờ tiền minh họa có mệnh giá bao nhiêu?',answers:shuffle(MONEY.slice(0,4).includes(note)?MONEY.slice(0,4).map(money):[note,1000,5000,10000].map(money)),correctAnswer:money(note),hintSteps:['Quan sát con số lớn trên tờ tiền.','Dấu chấm dùng để tách hàng nghìn.',`Mệnh giá là ${money(note)}.`],explanation:`Đây là tờ ${money(note)}.`}}const count=ri(2,4),notes=Array.from({length:count},()=>pick(MONEY.slice(0,4))),total=notes.reduce((s,v)=>s+v,0);if(mode==='count'){return{id:id('money-count'),type:'money',skillId:'vietnamese-money',mode,notes,instruction:'Có tất cả bao nhiêu tiền?',answers:moneyAnswers(total),correctAnswer:money(total),hintSteps:['Đọc mệnh giá từng tờ tiền.','Cộng các mệnh giá lại với nhau.',`${notes.map(money).join(' + ')} = ${money(total)}.`],explanation:`Tổng số tiền là ${money(total)}.`}}const possible=[1000,2000,5000,10000,15000].filter(v=>v<total),price=possible.length?pick(possible):1000,change=total-price;return{id:id('money-buy'),type:'money',skillId:'vietnamese-money',mode,notes,price,instruction:`Có số tiền dưới đây, mua món đồ giá ${money(price)}. Còn lại bao nhiêu?`,answers:moneyAnswers(change),correctAnswer:money(change),hintSteps:['Cộng số tiền đang có.','Lấy tổng số tiền trừ giá món đồ.',`${money(total)} − ${money(price)} = ${money(change)}.`],explanation:`Còn lại ${money(total)} − ${money(price)} = ${money(change)}.`}}
type Factory=()=>LengthMoneyQuestion;const plan:Factory[]=[unitQuestion,convertQuestion,rulerQuestion,estimateQuestion,moneyQuestion];export function generateLengthMoneyQuestions(total:5|10|15=10){return shuffle(Array.from({length:total},(_,i)=>plan[i%5])).map(factory=>factory())}
