export type MeasureSkillId='kilogram'|'compare-mass'|'liter'|'compare-capacity'|'mass-capacity-problems';export type MeasureAnswer=number|string;
export const MEASURE_SKILL_LABELS:Record<MeasureSkillId,string>={kilogram:'Đơn vị ki-lô-gam','compare-mass':'Cân và so sánh khối lượng',liter:'Đơn vị lít','compare-capacity':'So sánh dung tích','mass-capacity-problems':'Bài toán đo lường'};
type Base={id:string;skillId:MeasureSkillId;instruction:string;answers:MeasureAnswer[];correctAnswer:MeasureAnswer;hintSteps:[string,string,string];explanation:string};
export type UnitQuestion=Base&{type:'unit';unit:'kg'|'l';icon:string;objectName:string;value:number};
export type BalanceQuestion=Base&{type:'balance';mode:'read'|'compare';leftIcon:string;rightIcon:string;leftMass:number;rightMass:number};
export type CapacityQuestion=Base&{type:'capacity';mode:'read'|'compare';first:number;second:number;firstIcon:string;secondIcon:string};
export type MeasureWordQuestion=Base&{type:'word';unit:'kg'|'l';operation:'addition'|'subtraction';story:string;icon:string;first:number;change:number};
export type MeasureQuestion=UnitQuestion|BalanceQuestion|CapacityQuestion|MeasureWordQuestion;
const MASS_OBJECTS=[{icon:'🍉',name:'quả dưa hấu',value:3},{icon:'🎒',name:'chiếc cặp',value:2},{icon:'🍚',name:'túi gạo',value:5},{icon:'🐱',name:'chú mèo',value:4}]as const;
const CAPACITY_OBJECTS=[{icon:'🧴',name:'chai nước',value:1},{icon:'🫙',name:'bình nước',value:2},{icon:'🪣',name:'xô nước',value:8},{icon:'🛢️',name:'can nước',value:5}]as const;
function ri(a:number,b:number){return Math.floor(Math.random()*(b-a+1))+a}function item<T>(a:readonly T[]):T{return a[ri(0,a.length-1)]}function shuffle<T>(a:readonly T[]){const r=[...a];for(let i=r.length-1;i>0;i--){const j=ri(0,i);[r[i],r[j]]=[r[j],r[i]]}return r}function id(t:string){return`${t}-${Date.now()}-${Math.random().toString(36).slice(2,9)}`}
function nums(correct:number,max=30){const s=new Set([correct]);for(const d of [1,-1,2,-2,5,-5]){const v=correct+d;if(v>=0&&v<=max)s.add(v);if(s.size===4)break}let v=0;while(s.size<4){s.add(v);v++}return shuffle([...s].slice(0,4))}
function kilogramQuestion():UnitQuestion{const o=item(MASS_OBJECTS),symbol=Math.random()<.5;if(symbol)return{id:id('kg-symbol'),type:'unit',skillId:'kilogram',unit:'kg',icon:'⚖️',objectName:'ki-lô-gam',value:o.value,instruction:'Kí hiệu của ki-lô-gam là gì?',answers:shuffle(['kg','l','cm','giờ']),correctAnswer:'kg',hintSteps:['Ki-lô-gam là đơn vị đo khối lượng.','Kí hiệu gồm hai chữ cái viết thường.','Ki-lô-gam viết tắt là kg.'],explanation:'Ki-lô-gam được viết tắt là kg.'};return{id:id('kg-unit'),type:'unit',skillId:'kilogram',unit:'kg',icon:o.icon,objectName:o.name,value:o.value,instruction:`${o.name} nặng khoảng ${o.value} ... Chọn đơn vị thích hợp.`,answers:shuffle(['kg','l','cm','giờ']),correctAnswer:'kg',hintSteps:['Câu hỏi đang nói về khối lượng.','Khối lượng của đồ vật này phù hợp với ki-lô-gam.','Đơn vị thích hợp là kg.'],explanation:`Có thể viết: ${o.value} kg.`}}
function balanceQuestion():BalanceQuestion{const mode=item(['read','compare']as const);if(mode==='read'){const o=item(MASS_OBJECTS),mass=ri(1,9);return{id:id('balance-read'),type:'balance',skillId:'compare-mass',mode,leftIcon:o.icon,rightIcon:'🏋️',leftMass:mass,rightMass:mass,instruction:'Cân thăng bằng. Vật ở đĩa trái nặng bao nhiêu ki-lô-gam?',answers:nums(mass,15).map(n=>`${n} kg`),correctAnswer:`${mass} kg`,hintSteps:['Hai đĩa cân ngang nhau nên khối lượng hai bên bằng nhau.','Đĩa bên phải có các quả cân ghi số ki-lô-gam.','Vật nặng bằng tổng số ki-lô-gam ở đĩa phải.'],explanation:`Cân thăng bằng nên vật ở đĩa trái nặng ${mass} kg.`}}let a=item(MASS_OBJECTS),b=item(MASS_OBJECTS);while(b.name===a.name)b=item(MASS_OBJECTS);const askHeavy=Math.random()<.5,correct=askHeavy?(a.value>b.value?a.name:b.name):(a.value<b.value?a.name:b.name);return{id:id('balance-compare'),type:'balance',skillId:'compare-mass',mode,leftIcon:a.icon,rightIcon:b.icon,leftMass:a.value,rightMass:b.value,instruction:askHeavy?'Vật nào nặng hơn?':'Vật nào nhẹ hơn?',answers:shuffle([a.name,b.name]),correctAnswer:correct,hintSteps:['So sánh số ki-lô-gam của hai vật.',`${a.name}: ${a.value} kg; ${b.name}: ${b.value} kg.`,`${correct} ${askHeavy?'nặng hơn':'nhẹ hơn'}.`],explanation:`${correct} ${askHeavy?'nặng hơn':'nhẹ hơn'} vật còn lại.`}}
function literQuestion():UnitQuestion{const o=item(CAPACITY_OBJECTS),symbol=Math.random()<.5;if(symbol)return{id:id('liter-symbol'),type:'unit',skillId:'liter',unit:'l',icon:'🫗',objectName:'lít',value:o.value,instruction:'Kí hiệu của lít là gì?',answers:shuffle(['l','kg','cm','phút']),correctAnswer:'l',hintSteps:['Lít là đơn vị đo dung tích.','Kí hiệu là một chữ cái viết thường.','Lít được viết tắt là l.'],explanation:'Lít được viết tắt là l.'};return{id:id('liter-unit'),type:'unit',skillId:'liter',unit:'l',icon:o.icon,objectName:o.name,value:o.value,instruction:`${o.name} chứa khoảng ${o.value} ... Chọn đơn vị thích hợp.`,answers:shuffle(['l','kg','cm','phút']),correctAnswer:'l',hintSteps:['Câu hỏi nói về lượng chất lỏng.','Dung tích thường được đo bằng lít.','Đơn vị thích hợp là l.'],explanation:`Có thể viết: ${o.value} l.`}}
function capacityQuestion():CapacityQuestion{const mode=item(['read','compare']as const),first=ri(2,9),second=ri(1,first-1);if(mode==='read')return{id:id('capacity-read'),type:'capacity',skillId:'compare-capacity',mode,first,second:0,firstIcon:'🪣',secondIcon:'',instruction:'Trong bình đang có bao nhiêu lít nước?',answers:nums(first,15).map(n=>`${n} l`),correctAnswer:`${first} l`,hintSteps:['Quan sát vạch mức nước trong bình.','Đọc số ở ngang mặt nước.','Bình có '+first+' l nước.'],explanation:`Mặt nước ngang vạch ${first}, nên bình có ${first} l nước.`};return{id:id('capacity-compare'),type:'capacity',skillId:'compare-capacity',mode,first,second,firstIcon:'🪣',secondIcon:'🫙',instruction:'Bình nào chứa nhiều nước hơn?',answers:shuffle(['Bình A','Bình B']),correctAnswer:'Bình A',hintSteps:['So sánh số lít của hai bình.',`Bình A có ${first} l, bình B có ${second} l.`,`${first} lớn hơn ${second}, nên bình A chứa nhiều hơn.`],explanation:`Bình A có ${first} l, nhiều hơn bình B có ${second} l.`}}
function wordQuestion():MeasureWordQuestion{const unit=item(['kg','l']as const),operation=item(['addition','subtraction']as const),first=ri(5,15),change=operation==='addition'?ri(1,20-first):ri(1,first-1),result=operation==='addition'?first+change:first-change,icon=unit==='kg'?'🍚':'🪣',noun=unit==='kg'?'gạo':'nước',sign=operation==='addition'?'+':'−';const story=operation==='addition'?`Kho có ${first} ${unit} ${noun}, nhập thêm ${change} ${unit}. Kho có tất cả bao nhiêu ${unit} ${noun}?`:`Có ${first} ${unit} ${noun}, đã dùng ${change} ${unit}. Còn lại bao nhiêu ${unit} ${noun}?`;return{id:id('measure-word'),type:'word',skillId:'mass-capacity-problems',unit,operation,story,icon,first,change,instruction:'Đọc bài toán và chọn đáp số.',answers:nums(result,30).map(n=>`${n} ${unit}`),correctAnswer:`${result} ${unit}`,hintSteps:[operation==='addition'?'“Thêm” và “tất cả” cho biết cần cộng.':'“Đã dùng” và “còn lại” cho biết cần trừ.',`Phép tính là ${first} ${sign} ${change}.`,`${first} ${sign} ${change} = ${result} ${unit}.`],explanation:`${first} ${sign} ${change} = ${result} ${unit}.`}}
type Factory=()=>MeasureQuestion;const core:Factory[]=[kilogramQuestion,balanceQuestion,literQuestion,capacityQuestion,wordQuestion];function sig(q:MeasureQuestion){return`${q.type}-${q.instruction}-${q.correctAnswer}`}
export function generateMeasureQuestions(total:5|10|15=10){const used=new Set<string>(),plan=total===5?core:total===10?[...core,...core]:[...core,...core,...core];return shuffle(plan).map(f=>{let q=f(),k=sig(q),t=0;while(used.has(k)&&t<30){q=f();k=sig(q);t++}used.add(k);return q})}
