export type MultiplyDivideSkillId='multiplication-concept'|'tables-2-5'|'division-concept'|'division-tables-2-5';
export type MultiplyDivideAnswer=number|string;
export const MULTIPLY_DIVIDE_SKILL_LABELS:Record<MultiplyDivideSkillId,string>={'multiplication-concept':'Làm quen phép nhân','tables-2-5':'Bảng nhân 2 và 5','division-concept':'Làm quen phép chia','division-tables-2-5':'Bảng chia 2 và 5'};
type Base={id:string;skillId:MultiplyDivideSkillId;instruction:string;answers:MultiplyDivideAnswer[];correctAnswer:MultiplyDivideAnswer;hintSteps:[string,string,string];explanation:string};
export type GroupsQuestion=Base&{type:'groups';groupCount:number;perGroup:number;icon:string;mode:'count'|'equation'};
export type MultiplyQuestion=Base&{type:'multiply';factor:2|5;times:number;missing:'result'|'factor'};
export type ShareQuestion=Base&{type:'share';total:number;groups:number;perGroup:number;icon:string;mode:'share'|'grouping'};
export type DivideQuestion=Base&{type:'divide';divisor:2|5;quotient:number;total:number;missing:'result'|'divisor'};
export type MultiplyDivideQuestion=GroupsQuestion|MultiplyQuestion|ShareQuestion|DivideQuestion;
const ICONS=['🍎','⭐','⚽','🐟','🧁']as const;
function ri(a:number,b:number){return Math.floor(Math.random()*(b-a+1))+a}function pick<T>(a:readonly T[]){return a[ri(0,a.length-1)]}function shuffle<T>(a:readonly T[]){const r=[...a];for(let i=r.length-1;i>0;i--){const j=ri(0,i);[r[i],r[j]]=[r[j],r[i]]}return r}function id(t:string){return`${t}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}function answers(c:number,max=50){const s=new Set([c]);for(const d of shuffle([1,-1,2,-2,5,-5,10,-10])){const v=c+d;if(v>=0&&v<=max)s.add(v);if(s.size===4)break}return shuffle([...s])}
function groupsQuestion():GroupsQuestion{const groupCount=ri(2,5),perGroup=ri(2,5),correct=groupCount*perGroup,mode=pick(['count','equation']as const),icon=pick(ICONS);return{id:id('groups'),type:'groups',skillId:'multiplication-concept',groupCount,perGroup,icon,mode,instruction:mode==='count'?`Có ${groupCount} nhóm, mỗi nhóm có ${perGroup}. Có tất cả bao nhiêu?`:'Phép nhân nào phù hợp với hình vẽ?',answers:mode==='count'?answers(correct):shuffle([`${groupCount} × ${perGroup} = ${correct}`,`${groupCount} + ${perGroup} = ${groupCount+perGroup}`,`${correct} : ${groupCount} = ${perGroup}`,`${groupCount} × ${perGroup+1} = ${groupCount*(perGroup+1)}`]),correctAnswer:mode==='count'?correct:`${groupCount} × ${perGroup} = ${correct}`,hintSteps:[`Có ${groupCount} nhóm bằng nhau.`,`Cộng ${perGroup} lặp lại ${groupCount} lần.`,`${perGroup} + ${Array.from({length:groupCount-1},()=>perGroup).join(' + ')} = ${correct}, nên ${groupCount} × ${perGroup} = ${correct}.`],explanation:`${groupCount} nhóm, mỗi nhóm ${perGroup}: ${groupCount} × ${perGroup} = ${correct}.`}}
function multiplyQuestion():MultiplyQuestion{const factor=pick([2,5]as const),times=ri(1,10),result=factor*times,missing=pick(['result','factor']as const),correct=missing==='result'?result:times;return{id:id('multiply'),type:'multiply',skillId:'tables-2-5',factor,times,missing,instruction:'Số nào thích hợp với ô trống?',answers:answers(correct),correctAnswer:correct,hintSteps:[`Đây là phép tính trong bảng nhân ${factor}.`,missing==='result'?`Lấy ${factor} cộng lặp lại ${times} lần.`:`Tìm số nhân với ${factor} để được ${result}.`,`${factor} × ${times} = ${result}.`],explanation:`${factor} × ${times} = ${result}, nên ô trống là ${correct}.`}}
function shareQuestion():ShareQuestion{const mode=pick(['share','grouping']as const),groups=ri(2,5),perGroup=ri(2,5),total=groups*perGroup,icon=pick(ICONS),correct=mode==='share'?perGroup:groups;return{id:id('share'),type:'share',skillId:'division-concept',total,groups,perGroup,icon,mode,instruction:mode==='share'?`Chia đều ${total} đồ vật vào ${groups} nhóm. Mỗi nhóm có bao nhiêu?`:`Có ${total} đồ vật, xếp ${perGroup} đồ vật vào mỗi nhóm. Được bao nhiêu nhóm?`,answers:answers(correct,20),correctAnswer:correct,hintSteps:[mode==='share'?`Chia lần lượt vào ${groups} nhóm.`:`Khoanh từng nhóm có ${perGroup} đồ vật.`,'Các nhóm phải có số lượng bằng nhau.',mode==='share'?`${total} : ${groups} = ${perGroup}.`:`${total} : ${perGroup} = ${groups}.`],explanation:mode==='share'?`${total} : ${groups} = ${perGroup}, mỗi nhóm có ${perGroup}.`:`${total} : ${perGroup} = ${groups}, được ${groups} nhóm.`}}
function divideQuestion():DivideQuestion{const divisor=pick([2,5]as const),quotient=ri(1,10),total=divisor*quotient,missing=pick(['result','divisor']as const),correct=missing==='result'?quotient:divisor;return{id:id('divide'),type:'divide',skillId:'division-tables-2-5',divisor,quotient,total,missing,instruction:'Số nào thích hợp với ô trống?',answers:answers(correct),correctAnswer:correct,hintSteps:[`Liên hệ bảng nhân ${divisor}.`,`Vì ${divisor} × ${quotient} = ${total}.`,`${total} : ${divisor} = ${quotient}.`],explanation:`${divisor} × ${quotient} = ${total}, nên ${total} : ${divisor} = ${quotient}.`}}
type Factory=()=>MultiplyDivideQuestion;const plan:Factory[]=[groupsQuestion,multiplyQuestion,shareQuestion,divideQuestion,multiplyQuestion];export function generateMultiplyDivideQuestions(total:5|10|15=10){return shuffle(Array.from({length:total},(_,i)=>plan[i%5])).map(factory=>factory())}
