export type Numbers1000SkillId='hundreds-tens-ones'|'read-write-1000'|'compare-1000'|'round-hundreds-tens';
export type Numbers1000Answer=number|string;
export const NUMBERS1000_SKILL_LABELS:Record<Numbers1000SkillId,string>={'hundreds-tens-ones':'Trăm, chục và đơn vị','read-write-1000':'Đọc và viết số','compare-1000':'So sánh và số đặc biệt','round-hundreds-tens':'Số tròn trăm, tròn chục'};
type Base={id:string;skillId:Numbers1000SkillId;instruction:string;answers:Numbers1000Answer[];correctAnswer:Numbers1000Answer;hintSteps:[string,string,string];explanation:string};
export type BlocksQ=Base&{type:'blocks';number:number;hundreds:number;tens:number;ones:number};
export type PlaceQ=Base&{type:'place';number:number;digit:number;place:'trăm'|'chục'|'đơn vị'};
export type ReadWriteQ=Base&{type:'read-write';number:number;mode:'read'|'write'};
export type CompareQ=Base&{type:'compare';left:number;right:number};
export type OrderQ=Base&{type:'order';values:number[];mode:'ascending'|'descending'};
export type SpecialQ=Base&{type:'special';kind:string};
export type SequenceQ=Base&{type:'sequence';values:(number|null)[];step:10|100};
export type Numbers1000Question=BlocksQ|PlaceQ|ReadWriteQ|CompareQ|OrderQ|SpecialQ|SequenceQ;
function ri(a:number,b:number){return Math.floor(Math.random()*(b-a+1))+a}function pick<T>(a:readonly T[]){return a[ri(0,a.length-1)]}function shuffle<T>(a:readonly T[]){const r=[...a];for(let i=r.length-1;i>0;i--){const j=ri(0,i);[r[i],r[j]]=[r[j],r[i]]}return r}function id(t:string){return`${t}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}function nums(c:number,min=100,max=999){const s=new Set([c]);for(const d of shuffle([1,-1,10,-10,100,-100,2,-2])){const v=c+d;if(v>=min&&v<=max)s.add(v);if(s.size===4)break}return shuffle([...s])}function textOptions(correct:string,others:string[]){return shuffle([correct,...shuffle([...new Set(others.filter(x=>x!==correct))]).slice(0,3)])}
const DIGITS=['không','một','hai','ba','bốn','năm','sáu','bảy','tám','chín'];
function readTwo(n:number,hasHundreds=false){const tens=Math.floor(n/10),ones=n%10;if(tens===0)return ones===0?'':`${hasHundreds?'linh ':''}${DIGITS[ones]}`;if(tens===1)return`mười${ones===0?'':ones===5?' lăm':` ${DIGITS[ones]}`}`;const oneWord=ones===0?'':ones===1?' mốt':ones===4?' tư':ones===5?' lăm':` ${DIGITS[ones]}`;return`${DIGITS[tens]} mươi${oneWord}`}
export function readVietnameseNumber(n:number){const hundreds=Math.floor(n/100),rest=n%100;if(hundreds===0)return readTwo(rest);return`${DIGITS[hundreds]} trăm${rest===0?'':` ${readTwo(rest,true)}`}`}
function blocksQuestion():BlocksQ{const hundreds=ri(1,6),tens=ri(0,6),ones=ri(0,6),number=hundreds*100+tens*10+ones;return{id:id('blocks1000'),type:'blocks',skillId:'hundreds-tens-ones',number,hundreds,tens,ones,instruction:'Các khối biểu diễn số nào?',answers:nums(number),correctAnswer:number,hintSteps:['Mỗi bảng lớn là 1 trăm, mỗi thanh là 1 chục, mỗi ô nhỏ là 1 đơn vị.',`Có ${hundreds} trăm, ${tens} chục và ${ones} đơn vị.`,`Số cần tìm là ${number}.`],explanation:`${hundreds} trăm + ${tens} chục + ${ones} đơn vị = ${number}.`}}
function placeQuestion():PlaceQ{const number=ri(100,999),place=pick(['trăm','chục','đơn vị']as const),digit=place==='trăm'?Math.floor(number/100):place==='chục'?Math.floor(number/10)%10:number%10;return{id:id('place1000'),type:'place',skillId:'hundreds-tens-ones',number,digit,place,instruction:`Trong số ${number}, chữ số hàng ${place} là mấy?`,answers:shuffle([digit,...shuffle([0,1,2,3,4,5,6,7,8,9].filter(v=>v!==digit)).slice(0,3)]),correctAnswer:digit,hintSteps:['Đọc số theo thứ tự trăm, chục, đơn vị.',`Xác định vị trí hàng ${place}.`,`Chữ số hàng ${place} là ${digit}.`],explanation:`Số ${number} có chữ số hàng ${place} là ${digit}.`}}
function readWriteQuestion():ReadWriteQ{const number=ri(100,999),mode=pick(['read','write']as const),words=readVietnameseNumber(number);if(mode==='write'){return{id:id('write1000'),type:'read-write',skillId:'read-write-1000',number,mode,instruction:`Số “${words}” được viết là số nào?`,answers:nums(number),correctAnswer:number,hintSteps:['Xác định lần lượt hàng trăm, hàng chục và hàng đơn vị.','Viết mỗi chữ số vào đúng hàng.',`Số cần viết là ${number}.`],explanation:`“${words}” được viết là ${number}.`}}const others=nums(number).filter(v=>v!==number).map(readVietnameseNumber);return{id:id('read1000'),type:'read-write',skillId:'read-write-1000',number,mode,instruction:`Số ${number} được đọc như thế nào?`,answers:textOptions(words,others),correctAnswer:words,hintSteps:['Đọc chữ số hàng trăm trước.','Sau đó đọc hàng chục và hàng đơn vị.',`Số ${number} đọc là “${words}”.`],explanation:`Số ${number} đọc là “${words}”.`}}
function compareQuestion():CompareQ{const left=ri(100,999),right=Math.random()<.2?left:ri(100,999),correct=left>right?'>':left<right?'<':'=';return{id:id('compare1000'),type:'compare',skillId:'compare-1000',left,right,instruction:'Chọn dấu thích hợp.',answers:shuffle(['<','=','>']),correctAnswer:correct,hintSteps:['So sánh hàng trăm trước.','Nếu hàng trăm bằng nhau, so sánh hàng chục rồi hàng đơn vị.',`${left} ${correct} ${right}.`],explanation:`${left} ${correct} ${right}.`}}
function orderQuestion():OrderQ{const values=shuffle([...new Set(Array.from({length:7},()=>ri(100,999)))]).slice(0,4);while(values.length<4){const v=ri(100,999);if(!values.includes(v))values.push(v)}const mode=pick(['ascending','descending']as const),sorted=[...values].sort((a,b)=>mode==='ascending'?a-b:b-a),correct=sorted.join(' – ');const distractors=[...Array.from({length:5},()=>shuffle(values).join(' – '))];return{id:id('order1000'),type:'order',skillId:'compare-1000',values,mode,instruction:`Dãy nào sắp xếp các số theo thứ tự ${mode==='ascending'?'từ bé đến lớn':'từ lớn đến bé'}?`,answers:textOptions(correct,distractors),correctAnswer:correct,hintSteps:['So sánh chữ số hàng trăm của các số.','Nếu hàng trăm bằng nhau, xét tiếp hàng chục và hàng đơn vị.',`Thứ tự đúng là ${correct}.`],explanation:`Dãy đúng: ${correct}.`}}
const SPECIALS=[['Số lớn nhất có ba chữ số',999],['Số nhỏ nhất có ba chữ số',100],['Số chẵn lớn nhất có ba chữ số',998],['Số lẻ lớn nhất có ba chữ số',999],['Số chẵn nhỏ nhất có ba chữ số',100],['Số lẻ nhỏ nhất có ba chữ số',101]]as const;
function specialQuestion():SpecialQ{const[kind,correct]=pick(SPECIALS);return{id:id('special1000'),type:'special',skillId:'compare-1000',kind,instruction:`${kind} là số nào?`,answers:nums(correct),correctAnswer:correct,hintSteps:['Số có ba chữ số nằm từ 100 đến 999.',kind.includes('chẵn')?'Số chẵn có chữ số tận cùng là 0, 2, 4, 6 hoặc 8.':kind.includes('lẻ')?'Số lẻ có chữ số tận cùng là 1, 3, 5, 7 hoặc 9.':'Xét giới hạn của các số có ba chữ số.',`${kind} là ${correct}.`],explanation:`${kind} là ${correct}.`}}
function sequenceQuestion():SequenceQ{const step=pick([10,100]as const),count=5,start=step===10?ri(10,70)*10:ri(1,5)*100,index=ri(1,3),full=Array.from({length:count},(_,i)=>start+i*step),correct=full[index],values=full.map((v,i)=>i===index?null:v);return{id:id('sequence1000'),type:'sequence',skillId:'round-hundreds-tens',values,step,instruction:'Số nào thích hợp với ô trống?',answers:nums(correct,step,999),correctAnswer:correct,hintSteps:[`Các số tăng thêm ${step} sau mỗi bước.`,`Lấy số đứng trước cộng ${step}.`,`Số còn thiếu là ${correct}.`],explanation:`Dãy số tăng đều ${step}, nên số còn thiếu là ${correct}.`}}
type Factory=()=>Numbers1000Question;const plan:Factory[]=[blocksQuestion,placeQuestion,readWriteQuestion,compareQuestion,specialQuestion,orderQuestion,sequenceQuestion];export function generateNumbers1000Questions(total:5|10|15=10){return shuffle(Array.from({length:total},(_,i)=>plan[i%plan.length])).map(factory=>factory())}
