export type SolidsSkillId='recognize-cylinder'|'recognize-sphere'|'compare-solids';
export type SolidsAnswer=number|string;
export const SOLIDS_SKILL_LABELS:Record<SolidsSkillId,string>={'recognize-cylinder':'Khối trụ','recognize-sphere':'Khối cầu','compare-solids':'Phân loại hình khối'};
export type SolidKind='cylinder'|'sphere';
type Base={id:string;skillId:SolidsSkillId;instruction:string;answers:SolidsAnswer[];correctAnswer:SolidsAnswer;hintSteps:[string,string,string];explanation:string};
export type SolidQuestion=Base&{type:'solid';solid:SolidKind;color:string};
export type ObjectQuestion=Base&{type:'object';solid:SolidKind;icon:string;name:string};
export type SortQuestion=Base&{type:'sort';target:SolidKind;objects:{solid:SolidKind;icon:string;name:string}[]};
export type PropertyQuestion=Base&{type:'property';solid:SolidKind};
export type SolidsQuestion=SolidQuestion|ObjectQuestion|SortQuestion|PropertyQuestion;
const CYLINDERS=[{icon:'🥫',name:'lon sữa'},{icon:'🧻',name:'cuộn giấy'},{icon:'🛢️',name:'thùng dầu'},{icon:'🥁',name:'chiếc trống'}]as const;
const SPHERES=[{icon:'⚽',name:'quả bóng'},{icon:'🍊',name:'quả cam'},{icon:'🌍',name:'quả địa cầu'},{icon:'🔮',name:'quả cầu'}]as const;
function ri(a:number,b:number){return Math.floor(Math.random()*(b-a+1))+a}function pick<T>(a:readonly T[]){return a[ri(0,a.length-1)]}function shuffle<T>(a:readonly T[]){const r=[...a];for(let i=r.length-1;i>0;i--){const j=ri(0,i);[r[i],r[j]]=[r[j],r[i]]}return r}function id(t:string){return`${t}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}function nums(c:number){return shuffle([...new Set([c,Math.max(0,c-1),c+1,c+2])])}
function solidQuestion(kind:SolidKind):SolidQuestion{const label=kind==='cylinder'?'Khối trụ':'Khối cầu';return{id:id('solid'),type:'solid',skillId:kind==='cylinder'?'recognize-cylinder':'recognize-sphere',solid:kind,color:pick(['sky','emerald','orange','violet']),instruction:'Hình khối dưới đây có tên là gì?',answers:shuffle(['Khối trụ','Khối cầu','Khối lập phương','Khối hộp chữ nhật']),correctAnswer:label,hintSteps:[kind==='cylinder'?'Quan sát hai mặt phẳng tròn ở hai đầu.':'Khối này tròn đều về mọi phía.',kind==='cylinder'?'Mặt bên của khối có dạng cong.':'Khối không có mặt phẳng và không có cạnh.',`Đây là ${label.toLowerCase()}.`],explanation:kind==='cylinder'?'Khối trụ có hai mặt phẳng hình tròn và một mặt cong.':'Khối cầu tròn đều, không có mặt phẳng và không có cạnh.'}}
function objectQuestion(kind:SolidKind):ObjectQuestion{const object=pick(kind==='cylinder'?CYLINDERS:SPHERES),label=kind==='cylinder'?'Khối trụ':'Khối cầu';return{id:id('object'),type:'object',skillId:kind==='cylinder'?'recognize-cylinder':'recognize-sphere',solid:kind,...object,instruction:`${object.name[0].toUpperCase()+object.name.slice(1)} có dạng khối gì?`,answers:shuffle(['Khối trụ','Khối cầu','Khối lập phương','Khối hộp chữ nhật']),correctAnswer:label,hintSteps:['Hãy hình dung đồ vật khi xoay quanh.',kind==='cylinder'?'Đồ vật có hai đầu tròn và mặt bên cong.':'Đồ vật tròn đều như quả bóng.',`Đồ vật có dạng ${label.toLowerCase()}.`],explanation:`${object.name[0].toUpperCase()+object.name.slice(1)} có dạng ${label.toLowerCase()}.`}}
function sortQuestion():SortQuestion{const target=pick(['cylinder','sphere']as const),targetCount=ri(2,4),otherCount=5-targetCount,objects=shuffle([...Array.from({length:targetCount},()=>({...pick(target==='cylinder'?CYLINDERS:SPHERES),solid:target})),...Array.from({length:otherCount},()=>({...pick(target==='cylinder'?SPHERES:CYLINDERS),solid:target==='cylinder'?'sphere' as const:'cylinder' as const}))]);const label=target==='cylinder'?'khối trụ':'khối cầu';return{id:id('sort'),type:'sort',skillId:'compare-solids',target,objects,instruction:`Có bao nhiêu đồ vật dạng ${label}?`,answers:nums(targetCount),correctAnswer:targetCount,hintSteps:['Quan sát từng đồ vật từ trái sang phải.',target==='cylinder'?'Chọn vật có hai đầu tròn và mặt bên cong.':'Chọn vật tròn đều như quả bóng.',`Đếm được ${targetCount} đồ vật dạng ${label}.`],explanation:`Có ${targetCount} đồ vật dạng ${label}.`}}
function propertyQuestion():PropertyQuestion{const solid=pick(['cylinder','sphere']as const),correct=solid==='cylinder'?'Có hai mặt phẳng hình tròn':'Không có mặt phẳng';return{id:id('property'),type:'property',skillId:'compare-solids',solid,instruction:`Đặc điểm nào đúng với ${solid==='cylinder'?'khối trụ':'khối cầu'}?`,answers:shuffle([correct,'Có sáu mặt vuông','Có tám đỉnh','Có các cạnh thẳng']),correctAnswer:correct,hintSteps:['Quan sát các bề mặt của khối.',solid==='cylinder'?'Khối trụ có thể đứng trên hai đầu.':'Khối cầu lăn được theo mọi hướng.',correct],explanation:`${solid==='cylinder'?'Khối trụ có hai mặt phẳng hình tròn và một mặt cong.':'Khối cầu chỉ có bề mặt cong, không có mặt phẳng.'}`}}
type Factory=()=>SolidsQuestion;const plan:Factory[]=[()=>solidQuestion('cylinder'),()=>solidQuestion('sphere'),()=>objectQuestion('cylinder'),()=>objectQuestion('sphere'),()=>Math.random()<.5?sortQuestion():propertyQuestion()];export function generateSolidsQuestions(total:5|10|15=10){return shuffle(Array.from({length:total},(_,i)=>plan[i%5])).map(factory=>factory())}
