export type StatisticsSkillId='collect-classify-data'|'picture-chart'|'simple-probability';
export type StatisticsAnswer=number|string;
export const STATISTICS_SKILL_LABELS:Record<StatisticsSkillId,string>={'collect-classify-data':'Thu thập và phân loại','picture-chart':'Biểu đồ tranh','simple-probability':'Khả năng xảy ra'};
type Base={id:string;skillId:StatisticsSkillId;instruction:string;answers:StatisticsAnswer[];correctAnswer:StatisticsAnswer;hintSteps:[string,string,string];explanation:string};
export type CountDataQ=Base&{type:'count-data';items:string[];target:string;targetName:string};
export type ClassifyQ=Base&{type:'classify';icon:string;name:string;category:string};
export type PictureChartQ=Base&{type:'picture-chart';labels:string[];icons:string[];counts:number[];mode:'read'|'most'|'difference';targetIndex:number;secondIndex:number};
export type ProbabilityQ=Base&{type:'probability';balls:string[];targetColor:string;targetClass:string;outcome:'Chắc chắn'|'Có thể'|'Không thể'};
export type StatisticsQuestion=CountDataQ|ClassifyQ|PictureChartQ|ProbabilityQ;
const GROUPS=[{category:'Trái cây',items:[['🍎','quả táo'],['🍊','quả cam'],['🍌','quả chuối']]},{category:'Con vật',items:[['🐶','chú chó'],['🐱','chú mèo'],['🐟','chú cá']]},{category:'Đồ chơi',items:[['⚽','quả bóng'],['🪁','chiếc diều'],['🧸','gấu bông']]}]as const;
const CHART_ITEMS=[['Táo','🍎'],['Cam','🍊'],['Chuối','🍌'],['Dâu','🍓']]as const;
const COLORS=[{name:'đỏ',className:'bg-red-500'},{name:'xanh',className:'bg-blue-500'},{name:'vàng',className:'bg-yellow-400'}]as const;
function ri(a:number,b:number){return Math.floor(Math.random()*(b-a+1))+a}function pick<T>(a:readonly T[]){return a[ri(0,a.length-1)]}function shuffle<T>(a:readonly T[]){const r=[...a];for(let i=r.length-1;i>0;i--){const j=ri(0,i);[r[i],r[j]]=[r[j],r[i]]}return r}function id(t:string){return`${t}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}function nums(c:number,min=0,max=15){const s=new Set([c]);for(const d of shuffle([1,-1,2,-2,3,-3])){const v=c+d;if(v>=min&&v<=max)s.add(v);if(s.size===4)break}return shuffle([...s])}function textOptions(c:string,others:string[]){return shuffle([c,...shuffle([...new Set(others.filter(v=>v!==c))]).slice(0,3)])}
function countDataQuestion():CountDataQ{const group=pick(GROUPS),selected=pick(group.items),target=selected[0],targetName=selected[1],targetCount=ri(2,5),others=Array.from({length:ri(3,6)},()=>pick(group.items.filter(item=>item[0]!==target))[0]),items=shuffle([...Array(targetCount).fill(target),...others]);return{id:id('count-data'),type:'count-data',skillId:'collect-classify-data',items,target,targetName,instruction:`Có bao nhiêu ${targetName}?`,answers:nums(targetCount),correctAnswer:targetCount,hintSteps:[`Chỉ đánh dấu các hình ${target}.`,'Đếm từng hình đã đánh dấu một lần.',`Có ${targetCount} ${targetName}.`],explanation:`Kiểm đếm được ${targetCount} ${targetName}.`}}
function classifyQuestion():ClassifyQ{const group=pick(GROUPS),item=pick(group.items);return{id:id('classify'),type:'classify',skillId:'collect-classify-data',icon:item[0],name:item[1],category:group.category,instruction:`${item[1][0].toUpperCase()+item[1].slice(1)} thuộc nhóm nào?`,answers:shuffle(GROUPS.map(value=>value.category)),correctAnswer:group.category,hintSteps:['Nhìn đặc điểm và công dụng của đồ vật.','So sánh với tên các nhóm.',`${item[1][0].toUpperCase()+item[1].slice(1)} thuộc nhóm ${group.category.toLowerCase()}.`],explanation:`${item[1][0].toUpperCase()+item[1].slice(1)} được xếp vào nhóm ${group.category.toLowerCase()}.`}}
function chartQuestion():PictureChartQ{const chosen=shuffle(CHART_ITEMS).slice(0,3),counts=shuffle([2,3,4,5,6,7,8]).slice(0,3);const labels=chosen.map(x=>x[0]),icons=chosen.map(x=>x[1]),mode=pick(['read','most','difference']as const),targetIndex=ri(0,2),secondIndex=(targetIndex+ri(1,2))%3;if(mode==='read'){const correct=counts[targetIndex];return{id:id('chart-read'),type:'picture-chart',skillId:'picture-chart',labels,icons,counts,mode,targetIndex,secondIndex,instruction:`Biểu đồ có bao nhiêu ${labels[targetIndex].toLowerCase()}?`,answers:nums(correct),correctAnswer:correct,hintSteps:[`Tìm hàng ${labels[targetIndex]}.`,'Mỗi hình biểu thị một quả.',`Đếm được ${correct} quả.`],explanation:`Hàng ${labels[targetIndex]} có ${correct} hình, nên có ${correct} quả.`}}if(mode==='most'){const max=Math.max(...counts),idx=counts.indexOf(max),correct=labels[idx];return{id:id('chart-most'),type:'picture-chart',skillId:'picture-chart',labels,icons,counts,mode,targetIndex:idx,secondIndex,instruction:'Loại quả nào có nhiều nhất?',answers:shuffle(labels),correctAnswer:correct,hintSteps:['Đếm số hình ở từng hàng.','So sánh ba kết quả.',`${correct} có ${max} hình, nhiều nhất.`],explanation:`${correct} có ${max} hình nên là loại nhiều nhất.`}}const difference=Math.abs(counts[targetIndex]-counts[secondIndex]);return{id:id('chart-diff'),type:'picture-chart',skillId:'picture-chart',labels,icons,counts,mode,targetIndex,secondIndex,instruction:`${labels[targetIndex]} và ${labels[secondIndex]} hơn kém nhau bao nhiêu quả?`,answers:nums(difference),correctAnswer:difference,hintSteps:['Đếm số hình ở hai hàng được hỏi.','Lấy số lớn trừ số bé.',`${Math.max(counts[targetIndex],counts[secondIndex])} − ${Math.min(counts[targetIndex],counts[secondIndex])} = ${difference}.`],explanation:`Hai loại hơn kém nhau ${difference} quả.`}}
function probabilityQuestion():ProbabilityQ{const target=pick(COLORS),outcome=pick(['Chắc chắn','Có thể','Không thể']as const),otherColors=COLORS.filter(c=>c.name!==target.name);let balls:{name:string;className:string}[]=[];if(outcome==='Chắc chắn')balls=Array.from({length:ri(4,7)},()=>target);else if(outcome==='Không thể')balls=Array.from({length:ri(4,7)},()=>pick(otherColors));else{balls=[target,...Array.from({length:ri(3,6)},()=>pick(Math.random()<.6?otherColors:COLORS))];if(balls.every(b=>b.name===target.name))balls.push(pick(otherColors))}balls=shuffle(balls);return{id:id('probability'),type:'probability',skillId:'simple-probability',balls:balls.map(b=>b.className),targetColor:target.name,targetClass:target.className,outcome,instruction:`Không nhìn vào túi, lấy một quả bóng. Khả năng lấy được bóng màu ${target.name} là gì?`,answers:shuffle(['Chắc chắn','Có thể','Không thể']),correctAnswer:outcome,hintSteps:['Quan sát tất cả màu bóng có trong túi.',outcome==='Chắc chắn'?`Mọi quả bóng đều màu ${target.name}.`:outcome==='Không thể'?`Trong túi không có bóng màu ${target.name}.`:`Trong túi có bóng màu ${target.name} và còn có màu khác.`,`Đáp án là “${outcome}”.`],explanation:outcome==='Chắc chắn'?`Tất cả bóng đều màu ${target.name}, nên chắc chắn lấy được.`:outcome==='Không thể'?`Không có bóng màu ${target.name}, nên không thể lấy được.`:`Có bóng màu ${target.name} nhưng cũng có màu khác, nên có thể lấy được.`}}
type Factory=()=>StatisticsQuestion;const plan:Factory[]=[countDataQuestion,classifyQuestion,chartQuestion,chartQuestion,probabilityQuestion];export function generateStatisticsQuestions(total:5|10|15=10){return shuffle(Array.from({length:total},(_,i)=>plan[i%5])).map(factory=>factory())}
