import { useEffect, useMemo, useState } from 'react';
import { FINAL_REVIEW_SKILL_LABELS, generateFinalReviewQuestions, type FinalReviewAnswer, type FinalReviewQuestion, type FinalReviewSkillId } from '../lib/finalReviewQuestionGenerator';

type Screen = 'intro' | 'guide' | 'lesson' | 'result';
type PracticeSize = 5 | 10 | 15;
type Result = { questionId: string; skillId: FinalReviewSkillId; attempts: number; correctFirstTry: boolean };
type SavedBest = { score: number; stars: number };
const STORAGE_KEY = 'dao-toan-hoc:lop-1:on-tap-cuoi-nam:best-v1';
function starsFor(score: number) { return score >= 90 ? 3 : score >= 70 ? 2 : 1; }

function Shape({ shape }: { shape: 'circle' | 'square' | 'triangle' | 'rectangle' }) {
  if (shape === 'triangle') return <div className="h-0 w-0 border-x-[90px] border-b-[150px] border-x-transparent border-b-fuchsia-500" />;
  return <div className={`bg-fuchsia-500 shadow-lg ${shape === 'circle' ? 'h-40 w-40 rounded-full' : shape === 'square' ? 'h-40 w-40' : 'h-32 w-56'}`} />;
}
function Solid({ solid }: { solid: 'cube' | 'cuboid' }) {
  const wide = solid === 'cuboid';
  return <svg viewBox="0 0 300 220" className="h-56 w-72"><polygon points={wide ? '45,80 210,80 260,40 95,40' : '65,75 205,75 245,35 105,35'} fill="#c4b5fd"/><polygon points={wide ? '210,80 260,40 260,155 210,195' : '205,75 245,35 245,175 205,215'} fill="#7c3aed"/><rect x={wide ? 45 : 65} y={wide ? 80 : 75} width={wide ? 165 : 140} height={wide ? 115 : 140} fill="#a855f7"/><g fill="none" stroke="#581c87" strokeWidth="5" strokeLinejoin="round"><polygon points={wide ? '45,80 210,80 260,40 95,40' : '65,75 205,75 245,35 105,35'}/><polygon points={wide ? '210,80 260,40 260,155 210,195' : '205,75 245,35 245,175 205,215'}/><rect x={wide ? 45 : 65} y={wide ? 80 : 75} width={wide ? 165 : 140} height={wide ? 115 : 140}/></g></svg>;
}
function Clock({ hour }: { hour: number }) {
  return <svg viewBox="0 0 300 300" className="h-64 w-64"><circle cx="150" cy="150" r="136" fill="#fff" stroke="#a855f7" strokeWidth="10"/>{Array.from({length:12}).map((_,i)=>{const n=i+1,a=(n*30-90)*Math.PI/180;return <text key={n} x={150+Math.cos(a)*105} y={157+Math.sin(a)*105} textAnchor="middle" fontSize="24" fontWeight="900">{n}</text>})}<line x1="150" y1="150" x2="150" y2="68" stroke="#334155" strokeWidth="10" strokeLinecap="round" transform={`rotate(${hour*30} 150 150)`}/><line x1="150" y1="150" x2="150" y2="40" stroke="#0ea5e9" strokeWidth="7" strokeLinecap="round"/><circle cx="150" cy="150" r="11" fill="#f97316"/></svg>;
}
function Ruler({ length }: { length: number }) {
  const start=40, step=58, end=start+length*step;
  return <svg viewBox="0 0 660 210" className="w-full max-w-3xl"><line x1={start} y1="55" x2={end} y2="55" stroke="#a855f7" strokeWidth="18" strokeLinecap="round"/><rect x="25" y="100" width="610" height="82" rx="10" fill="#fef3c7" stroke="#f59e0b" strokeWidth="3"/>{Array.from({length:11}).map((_,i)=>{const x=start+i*step;return <g key={i}><line x1={x} y1="100" x2={x} y2="135" stroke="#92400e" strokeWidth="3"/><text x={x} y="165" textAnchor="middle" fontSize="22" fontWeight="800">{i}</text></g>})}<text x="620" y="165" textAnchor="end" fontWeight="800">cm</text></svg>;
}

export default function FinalReviewGame() {
  const [screen,setScreen]=useState<Screen>('intro'), [practiceSize,setPracticeSize]=useState<PracticeSize>(10), [questions,setQuestions]=useState<FinalReviewQuestion[]>([]), [questionIndex,setQuestionIndex]=useState(0), [selectedAnswer,setSelectedAnswer]=useState<FinalReviewAnswer|null>(null), [attempts,setAttempts]=useState(0), [hintLevel,setHintLevel]=useState(0), [canContinue,setCanContinue]=useState(false), [results,setResults]=useState<Result[]>([]), [bestResult,setBestResult]=useState<SavedBest|null>(null), [reviewMode,setReviewMode]=useState(false);
  useEffect(()=>{setQuestions(generateFinalReviewQuestions(10));const saved=localStorage.getItem(STORAGE_KEY);if(saved)try{setBestResult(JSON.parse(saved))}catch{localStorage.removeItem(STORAGE_KEY)}},[]);
  const question=questions[questionIndex], progress=questions.length?((questionIndex+1)/questions.length)*100:0;
  const summary=useMemo(()=>{const correct=results.filter(x=>x.correctFirstTry).length,score=results.length?Math.round(correct/results.length*100):0;const bySkill=(Object.keys(FINAL_REVIEW_SKILL_LABELS) as FinalReviewSkillId[]).map(skillId=>{const list=results.filter(x=>x.skillId===skillId);return{skillId,total:list.length,correct:list.filter(x=>x.correctFirstTry).length}}).filter(x=>x.total>0);return{correct,score,stars:starsFor(score),bySkill}},[results]);
  function resetAnswer(){setSelectedAnswer(null);setAttempts(0);setHintLevel(0);setCanContinue(false)}
  function prepareSession(size:PracticeSize){setPracticeSize(size);setQuestions(generateFinalReviewQuestions(size));setQuestionIndex(0);setResults([]);setReviewMode(false);resetAnswer();setScreen('guide')}
  function chooseAnswer(answer:FinalReviewAnswer){if(!question||canContinue)return;const next=attempts+1;setAttempts(next);setSelectedAnswer(answer);if(answer===question.correctAnswer){setCanContinue(true);setResults(current=>[...current,{questionId:question.id,skillId:question.skillId,attempts:next,correctFirstTry:next===1}])}else setHintLevel(Math.min(next,3))}
  function nextQuestion(){if(questionIndex<questions.length-1){setQuestionIndex(i=>i+1);resetAnswer();return}if(!reviewMode){const correct=results.filter(x=>x.correctFirstTry).length,score=Math.round(correct/questions.length*100),saved={score,stars:starsFor(score)};if(!bestResult||score>bestResult.score){localStorage.setItem(STORAGE_KEY,JSON.stringify(saved));setBestResult(saved)}}setScreen('result')}
  function review(){const ids=new Set(results.filter(x=>!x.correctFirstTry).map(x=>x.questionId)),missed=questions.filter(x=>ids.has(x.id));if(!missed.length)return;setQuestions(missed);setQuestionIndex(0);setResults([]);setReviewMode(true);resetAnswer();setScreen('lesson')}
  function answerClass(answer:FinalReviewAnswer){if(selectedAnswer===answer&&answer!==question.correctAnswer)return'border-red-400 bg-red-50 text-red-700';if(canContinue&&answer===question.correctAnswer)return'border-emerald-400 bg-emerald-50 text-emerald-700';return'border-slate-200 bg-white text-slate-800 hover:-translate-y-1 hover:border-fuchsia-300 hover:bg-fuchsia-50'}
  function Answers(){return <div className={`grid gap-3 ${question.answers.length===3?'sm:grid-cols-3':'grid-cols-2 sm:grid-cols-4'}`}>{question.answers.map(a=><button key={String(a)} type="button" disabled={canContinue} onClick={()=>chooseAnswer(a)} className={`min-h-20 rounded-2xl border-4 px-3 py-4 text-lg font-black shadow-sm transition md:text-xl ${answerClass(a)}`}>{a}</button>)}</div>}
  function Visual(){
    if(question.type==='number'){
      if(question.mode==='place-value')return <div className="grid min-h-64 place-items-center rounded-3xl bg-cyan-50"><p className="text-8xl font-black text-cyan-700">{question.number}</p></div>;
      if(question.mode==='compare')return <div className="grid min-h-64 grid-cols-[1fr_auto_1fr] place-items-center rounded-3xl bg-cyan-50 p-6 text-6xl font-black"><span>{question.left}</span><span className="text-cyan-600">?</span><span>{question.right}</span></div>;
      return <div className="flex min-h-64 flex-wrap items-center justify-center gap-3 rounded-3xl bg-cyan-50 p-6">{question.sequence?.map((n,i)=><span key={i} className={`grid h-20 w-20 place-items-center rounded-2xl text-3xl font-black ${n===null?'border-4 border-dashed border-cyan-400 bg-white text-cyan-600':'bg-cyan-500 text-white'}`}>{n??'?'}</span>)}</div>;
    }
    if(question.type==='calculation'){const sign=question.operation==='addition'?'+':'−',result=question.operation==='addition'?question.left+question.right:question.left-question.right;return <div className="grid min-h-64 place-items-center rounded-3xl bg-indigo-50 p-6"><p className="text-5xl font-black text-indigo-800 md:text-7xl">{question.left} {sign} {question.missing?'?':question.right} = {question.missing?result:'?'}</p></div>}
    if(question.type==='word')return <div className="grid min-h-64 place-items-center rounded-3xl bg-amber-50 p-7 text-center"><div><div className="text-7xl">{question.icon}</div><p className="mx-auto mt-4 max-w-3xl text-xl font-black leading-9">{question.story}</p></div></div>;
    if(question.type==='geometry'){
      if(question.mode==='flat'&&question.shape)return <div className="grid min-h-72 place-items-center rounded-3xl bg-fuchsia-50"><Shape shape={question.shape}/></div>;
      if(question.mode==='solid'&&question.solid)return <div className="grid min-h-72 place-items-center rounded-3xl bg-violet-50"><Solid solid={question.solid}/></div>;
      const relation=question.relation,vertical=relation?.includes('trên')||relation?.includes('dưới'),reverse=relation==='Bên phải'||relation==='Phía dưới';return <div className={`flex min-h-72 items-center justify-center gap-12 rounded-3xl bg-emerald-50 text-8xl ${vertical?'flex-col':''} ${reverse?'flex-row-reverse':''} ${vertical&&reverse?'flex-col-reverse':''}`}><span>{question.firstIcon}</span><span>{question.secondIcon}</span></div>;
    }
    if(question.mode==='length'&&question.value)return <div className="overflow-x-auto rounded-3xl bg-amber-50 p-4"><Ruler length={question.value}/></div>;
    if(question.mode==='clock'&&question.value)return <div className="grid min-h-72 place-items-center rounded-3xl bg-purple-50"><Clock hour={question.value}/></div>;
    return <div className="rounded-3xl bg-orange-50 p-6"><div className="mx-auto grid max-w-3xl grid-cols-7 gap-1">{['Thứ Hai','Thứ Ba','Thứ Tư','Thứ Năm','Thứ Sáu','Thứ Bảy','Chủ nhật'].map(day=><div key={day} className={`grid min-h-24 place-items-center rounded-xl px-1 text-center text-xs font-black sm:text-sm ${day===question.focusDay?'bg-orange-500 text-white':'bg-white text-slate-500'}`}>{day}</div>)}</div></div>;
  }
  if(!questions.length)return <main className="grid min-h-screen place-items-center text-center"><div><div className="text-7xl">🏆</div><p className="mt-4 text-xl font-black text-fuchsia-700">Sóc Nâu đang chuẩn bị thử thách...</p></div></main>;
  if(screen==='intro')return <main className="mx-auto max-w-5xl px-4 py-8 md:py-12"><a href="/lop-1" className="inline-flex rounded-xl bg-white px-4 py-3 font-black text-slate-600 shadow-sm">← Lớp 1</a><section className="mt-6 overflow-hidden rounded-[2.5rem] border-4 border-white bg-white shadow-2xl shadow-fuchsia-100"><div className="bg-gradient-to-br from-fuchsia-500 via-purple-600 to-indigo-600 p-8 text-white md:p-12"><p className="font-black tracking-widest text-fuchsia-100">Mục 10 · Bài 38–41</p><h1 className="mt-2 text-3xl font-black md:text-5xl">Ôn tập cuối năm</h1><p className="mt-4 max-w-3xl text-lg font-semibold leading-8 text-white/90">Luyện tổng hợp những kiến thức và kỹ năng quan trọng của lớp 1.</p></div><div className="p-6 md:p-10"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[['💯','Số đến 100'],['➕','Phép tính'],['📖','Bài toán'],['🔺','Hình học'],['📏','Đo lường']].map(([icon,label])=><div key={label} className="rounded-2xl bg-slate-50 p-4 text-center"><div className="text-3xl">{icon}</div><p className="mt-2 font-black text-slate-700">{label}</p></div>)}</div><h2 className="mt-8 text-xl font-black">Chọn lượt luyện tập</h2><div className="mt-4 grid gap-4 md:grid-cols-3">{([[5,'Luyện nhanh','Mỗi nhóm kiến thức một câu'],[10,'Luyện chuẩn','Hai câu cho mỗi nhóm'],[15,'Thử thách cuối năm','Ba câu cho mỗi nhóm']] as const).map(([size,title,desc])=><button key={size} onClick={()=>prepareSession(size)} className={`rounded-3xl border-4 p-5 text-left transition hover:-translate-y-1 ${size===10?'border-fuchsia-400 bg-fuchsia-50 shadow-lg':'border-slate-100 bg-white hover:border-purple-300'}`}><span className="text-sm font-black text-fuchsia-700">{size} câu</span><span className="mt-1 block text-xl font-black">{title}</span><span className="mt-2 block font-semibold text-slate-500">{desc}</span></button>)}</div>{bestResult&&<p className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-4 font-bold text-amber-800">Kết quả tốt nhất: {bestResult.score}% · {'⭐'.repeat(bestResult.stars)}</p>}</div></section></main>;
  if(screen==='guide')return <main className="mx-auto max-w-4xl px-4 py-10"><section className="rounded-[2.5rem] border-4 border-white bg-white p-7 shadow-2xl shadow-fuchsia-100 md:p-10"><div className="flex items-start gap-4"><span className="text-6xl">🐿️</span><div><p className="font-black text-fuchsia-700">Sóc Nâu nhắc bé</p><h1 className="mt-1 text-3xl font-black">Đọc kỹ câu hỏi trước khi chọn</h1></div></div><div className="my-7 grid gap-4 sm:grid-cols-2"><div className="rounded-3xl bg-fuchsia-50 p-5"><p className="font-black text-fuchsia-700">Không cần vội</p><p className="mt-2 font-semibold text-slate-600">Quan sát hình, số hoặc đồng hồ rồi mới bắt đầu tính.</p></div><div className="rounded-3xl bg-indigo-50 p-5"><p className="font-black text-indigo-700">Tự kiểm tra</p><p className="mt-2 font-semibold text-slate-600">Xem kết quả có hợp lí với câu hỏi hay không.</p></div></div><button onClick={()=>setScreen('lesson')} className="w-full rounded-2xl bg-fuchsia-600 px-7 py-4 text-lg font-black text-white">Bắt đầu {practiceSize} câu</button></section></main>;
  if(screen==='result'){const missed=results.filter(x=>!x.correctFirstTry).length;return <main className="mx-auto max-w-4xl px-4 py-10"><section className="rounded-[2.5rem] border-4 border-white bg-white p-7 text-center shadow-2xl shadow-fuchsia-100 md:p-10"><div className="text-7xl">{reviewMode?'💪':'🏆'}</div><p className="mt-4 font-black tracking-widest text-fuchsia-700">{reviewMode?'Hoàn thành lượt ôn lại':'Hoàn thành ôn tập cuối năm'}</p><h1 className="mt-2 text-4xl font-black">{summary.score>=90?'Sẵn sàng lên lớp 2!':summary.score>=70?'Hoàn thành tốt!':'Mình cùng luyện thêm nhé!'}</h1><div className="mt-6 flex justify-center gap-3 text-5xl">{[1,2,3].map(s=><span key={s} className={s<=summary.stars?'':'grayscale opacity-20'}>⭐</span>)}</div><div className="mt-7 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-sky-50 p-5"><p className="font-black text-sky-700">Điểm số</p><p className="text-3xl font-black">{summary.score}%</p></div><div className="rounded-2xl bg-emerald-50 p-5"><p className="font-black text-emerald-700">Đúng lần đầu</p><p className="text-3xl font-black">{summary.correct}/{results.length}</p></div><div className="rounded-2xl bg-amber-50 p-5"><p className="font-black text-amber-700">Sao nhận được</p><p className="text-3xl font-black">{summary.stars}/3</p></div></div><div className="mt-7 overflow-hidden rounded-3xl border-2 border-slate-100 text-left"><h2 className="bg-slate-50 px-5 py-4 text-xl font-black">Kết quả theo kỹ năng</h2>{summary.bySkill.map(x=>{const p=Math.round(x.correct/x.total*100);return <div key={x.skillId} className="grid gap-2 border-t px-5 py-4 sm:grid-cols-[1fr_auto]"><div><p className="font-black">{FINAL_REVIEW_SKILL_LABELS[x.skillId]}</p><div className="mt-2 h-2 rounded-full bg-slate-100"><div className={`h-full rounded-full ${p>=70?'bg-emerald-400':'bg-orange-400'}`} style={{width:`${p}%`}}/></div></div><p className="font-black">{x.correct}/{x.total}</p></div>})}</div><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row">{!reviewMode&&missed>0&&<button onClick={review} className="rounded-2xl bg-orange-500 px-6 py-4 font-black text-white">Ôn lại {missed} câu cần nhớ</button>}<button onClick={()=>prepareSession(practiceSize)} className="rounded-2xl bg-fuchsia-600 px-6 py-4 font-black text-white">Luyện bộ câu mới</button><a href="/lop-1" className="rounded-2xl border-2 border-slate-200 px-6 py-4 font-black">Về lớp 1</a></div></section></main>}
  return <main className="mx-auto max-w-5xl px-4 py-7"><header className="mb-5 flex items-center justify-between"><button onClick={()=>setScreen('intro')} className="rounded-xl bg-white px-4 py-3 font-black shadow-sm">← Thoát</button><div className="text-right"><p className="font-black text-fuchsia-700">{reviewMode?'Ôn lại · ':''}Câu {questionIndex+1}/{questions.length}</p><p className="text-sm font-bold text-slate-500">{FINAL_REVIEW_SKILL_LABELS[question.skillId]}</p></div></header><div className="mb-6 h-3 overflow-hidden rounded-full bg-white"><div className="h-full bg-gradient-to-r from-fuchsia-400 to-purple-600" style={{width:`${progress}%`}}/></div><section className="rounded-[2.5rem] border-4 border-white bg-white p-5 shadow-2xl shadow-fuchsia-100 md:p-9"><div className="mb-6 flex items-center gap-4"><span className="text-5xl">{questionIndex%2===0?'🐿️':'🐻'}</span><div><p className="font-black text-fuchsia-700">{questionIndex%2===0?'Sóc Nâu hỏi':'Gấu Mật hỏi'}</p><h1 className="mt-1 text-2xl font-black md:text-3xl">{question.instruction}</h1></div></div><Visual/><div className="mt-6"><Answers/></div>{selectedAnswer!==null&&!canContinue&&<div className="mt-6 rounded-3xl border-2 border-orange-200 bg-orange-50 p-5"><h2 className="text-xl font-black text-orange-700">💡 Chưa đúng, mình xem lại nhé!</h2><p className="mt-2 font-semibold"><span className="font-black">Gợi ý {hintLevel}/3:</span> {question.hintSteps[Math.max(0,hintLevel-1)]}</p><button onClick={()=>setSelectedAnswer(null)} className="mt-4 rounded-xl bg-orange-500 px-5 py-3 font-black text-white">Chọn lại đáp án</button></div>}{canContinue&&<div className="mt-6 rounded-3xl border-2 border-emerald-200 bg-emerald-50 p-5"><div className="flex flex-col items-center justify-between gap-4 sm:flex-row"><div><h2 className="text-xl font-black text-emerald-700">🎉 Chính xác!</h2><p className="mt-1 font-semibold">{question.explanation}</p></div><button onClick={nextQuestion} className="w-full rounded-2xl bg-fuchsia-600 px-6 py-4 font-black text-white sm:w-auto">{questionIndex===questions.length-1?'Xem kết quả':'Câu tiếp theo →'}</button></div></div>}</section></main>;
}
