import ResultShare from './ResultShare';
import SolutionExplanation from './SolutionExplanation';
import { buildAdaptiveQuestionSet } from '../lib/learningProfile';
import { playCorrectSound, playFinalSound, playWrongSound } from '../lib/gameAudio';
import { useEffect, useMemo, useState } from 'react';
import { GRADE2_REVIEW_SKILL_LABELS, generateGrade2ReviewQuestions, type Grade2ReviewAnswer, type Grade2ReviewQuestion, type Grade2ReviewSkillId } from '../lib/grade2ReviewQuestionGenerator';

type Screen='intro'|'guide'|'lesson'|'result';type Size=5|10|15;type Result={questionId:string;skillId:Grade2ReviewSkillId;attempts:number;correctFirstTry:boolean};type Best={score:number;stars:number};
const STORAGE_KEY='trang-toan:lop-2:on-tap-bo-sung:best-v1';
function starsFor(score:number){return score>=90?3:score>=70?2:1}

function TensOnes({number}:{number:number}){const tens=Math.floor(number/10),ones=number%10;return <div className="flex flex-wrap justify-center gap-6"><div className="flex flex-wrap justify-center gap-2">{Array.from({length:tens}).map((_,i)=><div key={i} className="grid h-32 w-8 grid-rows-10 overflow-hidden rounded-lg border-2 border-cyan-600 bg-cyan-300">{Array.from({length:10}).map((_,j)=><span key={j} className="border-b border-cyan-500/70"/>)}</div>)}</div><div className="flex flex-wrap content-start justify-center gap-2">{Array.from({length:ones}).map((_,i)=><span key={i} className="h-8 w-8 rounded-lg border-2 border-orange-500 bg-orange-300"/>)}</div></div>}
function NumberLine({question}:{question:Extract<Grade2ReviewQuestion,{type:'number-line'}>}){return <div className="overflow-x-auto rounded-3xl bg-sky-50 p-5"><div className="mx-auto min-w-[620px] max-w-3xl"><div className="flex items-end">{question.values.map((value,i)=><div key={i} className="flex-1 text-center"><div className={`mx-auto mb-2 grid h-12 w-12 place-items-center rounded-xl text-xl font-black ${value===null?'border-4 border-dashed border-sky-400 bg-white text-sky-600':value===question.focus&&question.relation!=='missing'?'bg-orange-500 text-white':'bg-white text-slate-700 shadow-sm'}`}>{value??'?'}</div><div className="h-5 border-l-2 border-slate-500"/></div>)}</div><div className="relative h-1 bg-slate-600 after:absolute after:-right-1 after:-top-2 after:border-y-[5px] after:border-l-[12px] after:border-y-transparent after:border-l-slate-600"/></div></div>}
function Equation({question}:{question:Extract<Grade2ReviewQuestion,{type:'component'}>}){const sign=question.operation==='addition'?'+':'−';const cell=(value:number,target:string)=><span className={`grid min-h-24 min-w-24 place-items-center rounded-2xl px-5 text-4xl font-black ${question.target===target?'bg-amber-400 text-amber-950 ring-8 ring-amber-200':'bg-white text-slate-800 shadow-sm'}`}>{value}</span>;return <div className="flex min-h-64 flex-wrap items-center justify-center gap-4 rounded-3xl bg-amber-50 p-6">{cell(question.left,'left')}<span className="text-5xl font-black text-slate-500">{sign}</span>{cell(question.right,'right')}<span className="text-5xl font-black text-slate-500">=</span>{cell(question.result,'result')}</div>}
function DifferenceBars({first,second}:{first:number;second:number}){const max=Math.max(first,second);return <div className="space-y-5 rounded-3xl bg-emerald-50 p-7"><div className="grid grid-cols-[5rem_1fr_auto] items-center gap-3"><b className="text-emerald-700">Nhóm xanh</b><div className="h-10 rounded-xl bg-cyan-500" style={{width:`${first/max*100}%`}}/><strong>{first}</strong></div><div className="grid grid-cols-[5rem_1fr_auto] items-center gap-3"><b className="text-orange-700">Nhóm cam</b><div className="h-10 rounded-xl bg-orange-400" style={{width:`${second/max*100}%`}}/><strong>{second}</strong></div><p className="text-center text-sm font-bold text-slate-500">Hai thanh bắt đầu từ cùng một vị trí</p></div>}
function Calculation({question}:{question:Extract<Grade2ReviewQuestion,{type:'calculation'}>}){const sign=question.operation==='addition'?'+':'−';if(question.layout==='vertical')return <div className="grid min-h-64 place-items-center rounded-3xl bg-indigo-50"><div className="grid grid-cols-[3rem_6rem] text-right text-5xl font-black leading-tight"><span/><span>{question.left}</span><span className="text-indigo-600">{sign}</span><span>{question.right}</span><span className="col-span-2 mt-2 border-t-4 border-slate-700 pt-3">?</span></div></div>;return <div className="grid min-h-64 place-items-center rounded-3xl bg-indigo-50"><p className="text-6xl font-black text-indigo-800">{question.left} {sign} {question.right} = ?</p></div>}

export default function Grade2ReviewGame(){
  const[screen,setScreen]=useState<Screen>('intro'),[size,setSize]=useState<Size>(10),[questions,setQuestions]=useState<Grade2ReviewQuestion[]>([]),[index,setIndex]=useState(0),[selected,setSelected]=useState<Grade2ReviewAnswer|null>(null),[attempts,setAttempts]=useState(0),[hint,setHint]=useState(0),[canContinue,setCanContinue]=useState(false),[results,setResults]=useState<Result[]>([]),[best,setBest]=useState<Best|null>(null),[reviewMode,setReviewMode]=useState(false);
  useEffect(()=>{setQuestions(generateGrade2ReviewQuestions(10));const saved=localStorage.getItem(STORAGE_KEY);if(saved)try{setBest(JSON.parse(saved))}catch{localStorage.removeItem(STORAGE_KEY)}},[]);
  const question=questions[index],progress=questions.length?(index+1)/questions.length*100:0;
  const summary=useMemo(()=>{const correct=results.filter(r=>r.correctFirstTry).length,score=results.length?Math.round(correct/results.length*100):0;const bySkill=(Object.keys(GRADE2_REVIEW_SKILL_LABELS)as Grade2ReviewSkillId[]).map(skillId=>{const list=results.filter(r=>r.skillId===skillId);return{skillId,total:list.length,correct:list.filter(r=>r.correctFirstTry).length}}).filter(x=>x.total);return{correct,score,stars:starsFor(score),bySkill}},[results]);
  function reset(){setSelected(null);setAttempts(0);setHint(0);setCanContinue(false)}
  function prepare(next:Size){setSize(next);setQuestions(generateGrade2ReviewQuestions(next));setIndex(0);setResults([]);setReviewMode(false);reset();setScreen('guide')}
  function choose(answer:Grade2ReviewAnswer){if(!question||canContinue)return;const next=attempts+1;setAttempts(next);setSelected(answer);if(answer===question.correctAnswer){playCorrectSound();setCanContinue(true);setResults(r=>[...r,{questionId:question.id,skillId:question.skillId,attempts:next,correctFirstTry:next===1}])}else{playWrongSound();setHint(Math.min(next,3))}}
  function next(){if(index<questions.length-1){setIndex(i=>i+1);reset();return}if(!reviewMode){const correct=results.filter(r=>r.correctFirstTry).length,score=Math.round(correct/questions.length*100),saved={score,stars:starsFor(score)};if(!best||score>best.score){localStorage.setItem(STORAGE_KEY,JSON.stringify(saved));setBest(saved)}}playFinalSound();setScreen('result')}
  function review(){const ids=new Set(results.filter(r=>!r.correctFirstTry).map(r=>r.questionId)),missed=questions.filter(q=>ids.has(q.id));if(!missed.length)return;setQuestions(missed);setIndex(0);setResults([]);setReviewMode(true);reset();setScreen('lesson')}
  function answerClass(answer:Grade2ReviewAnswer){if(selected===answer&&answer!==question.correctAnswer)return'border-red-400 bg-red-50 text-red-700';if(canContinue&&answer===question.correctAnswer)return'border-emerald-400 bg-emerald-50 text-emerald-700';return'border-slate-200 bg-white text-slate-800 hover:-translate-y-1 hover:border-cyan-300 hover:bg-cyan-50'}
  function Answers(){const long=question.answers.some(a=>String(a).length>12);return <div className={`grid gap-3 ${long?'sm:grid-cols-2':question.answers.length===3?'grid-cols-3':'grid-cols-2 sm:grid-cols-4'}`}>{question.answers.map(a=><button key={String(a)} disabled={canContinue} onClick={()=>choose(a)} className={`min-h-20 rounded-2xl border-4 px-3 py-4 text-lg font-black shadow-sm transition md:text-xl ${answerClass(a)}`}>{a}</button>)}</div>}
  function Visual(){if(question.type==='number'){if(question.mode==='place-value'&&question.number!==undefined)return <div className="rounded-3xl bg-cyan-50 p-6"><TensOnes number={question.number}/><p className="mt-6 text-center text-5xl font-black text-cyan-800">{question.number}</p></div>;if(question.mode==='compare')return <div className="grid min-h-64 grid-cols-[1fr_auto_1fr] place-items-center rounded-3xl bg-cyan-50 p-6 text-6xl font-black"><span>{question.left}</span><span className="text-cyan-600">?</span><span>{question.right}</span></div>;return <div className="grid min-h-64 place-items-center rounded-3xl bg-cyan-50"><p className="text-8xl font-black text-cyan-800">{question.number}</p></div>}if(question.type==='number-line')return <NumberLine question={question}/>;if(question.type==='component')return <Equation question={question}/>;if(question.type==='difference')return <DifferenceBars first={question.first} second={question.second}/>;return <Calculation question={question}/>}
  if(!questions.length)return <main className="grid min-h-screen place-items-center"><div className="text-center"><div className="text-7xl">🐿️</div><p className="mt-4 text-xl font-black text-cyan-700">Sóc Nâu đang chuẩn bị bài...</p></div></main>;
  if(screen==='intro')return <main className="mx-auto max-w-5xl px-4 py-8 md:py-12"><a href="/lop-2" className="inline-flex rounded-xl bg-white px-4 py-3 font-black text-slate-600 shadow-sm">← Lớp 2</a><section className="mt-6 overflow-hidden rounded-[2.5rem] border-4 border-white bg-white shadow-2xl shadow-cyan-100"><div className="bg-gradient-to-br from-cyan-400 via-sky-500 to-blue-600 p-8 text-white md:p-12"><p className="font-black tracking-widest text-cyan-100">Mục 1 · Bài 1–6</p><h1 className="mt-2 text-3xl font-black md:text-5xl">Ôn tập và bổ sung</h1><p className="mt-4 max-w-3xl text-lg font-semibold leading-8 text-white/90">Ôn số đến 100, tia số, thành phần phép tính và cộng trừ không nhớ.</p></div><div className="p-6 md:p-10"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[['💯','Số đến 100'],['➡️','Tia số'],['🧩','Thành phần phép tính'],['⚖️','Hơn, kém'],['➕','Cộng trừ không nhớ']].map(([icon,label])=><div key={label} className="rounded-2xl bg-slate-50 p-4 text-center"><div className="text-3xl">{icon}</div><p className="mt-2 font-black text-slate-700">{label}</p></div>)}</div><h2 className="mt-8 text-xl font-black">Chọn lượt luyện tập</h2><div className="mt-4 grid gap-4 md:grid-cols-3">{([[5,'Luyện nhanh','Mỗi kỹ năng một câu'],[10,'Luyện chuẩn','Hai câu cho mỗi kỹ năng'],[15,'Thử thách','Ba câu cho mỗi kỹ năng']]as const).map(([n,title,desc])=><button key={n} onClick={()=>prepare(n)} className={`rounded-3xl border-4 p-5 text-left transition hover:-translate-y-1 ${n===10?'border-cyan-400 bg-cyan-50 shadow-lg':'border-slate-100 bg-white hover:border-sky-300'}`}><span className="text-sm font-black text-cyan-700">{n} câu</span><span className="mt-1 block text-xl font-black">{title}</span><span className="mt-2 block font-semibold text-slate-500">{desc}</span></button>)}</div>{best&&<p className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-4 font-bold text-amber-800">Kết quả tốt nhất: {best.score}% · {'⭐'.repeat(best.stars)}</p>}</div></section></main>;
  if(screen==='guide')return <main className="mx-auto max-w-4xl px-4 py-10"><section className="rounded-[2.5rem] border-4 border-white bg-white p-7 shadow-2xl shadow-cyan-100 md:p-10"><div className="flex items-start gap-4"><span className="text-6xl">🐿️</span><div><p className="font-black text-cyan-700">Sóc Nâu nhắc bé</p><h1 className="mt-1 text-3xl font-black">Quan sát hàng chục và hàng đơn vị</h1></div></div><div className="my-7 grid gap-4 sm:grid-cols-2"><div className="rounded-3xl bg-cyan-50 p-5"><p className="font-black text-cyan-700">So sánh số</p><p className="mt-2 font-semibold text-slate-600">So sánh hàng chục trước, nếu bằng nhau mới so sánh hàng đơn vị.</p></div><div className="rounded-3xl bg-amber-50 p-5"><p className="font-black text-amber-700">Tính không nhớ</p><p className="mt-2 font-semibold text-slate-600">Đặt thẳng cột rồi tính từ hàng đơn vị.</p></div></div><button onClick={()=>setScreen('lesson')} className="w-full rounded-2xl bg-cyan-600 px-7 py-4 text-lg font-black text-white">Bắt đầu {size} câu</button></section></main>;
  if(screen==='result'){const missed=results.filter(r=>!r.correctFirstTry).length;return <main className="mx-auto max-w-4xl px-4 py-10"><section className="rounded-[2.5rem] border-4 border-white bg-white p-7 text-center shadow-2xl shadow-cyan-100 md:p-10"><div className="text-7xl">{reviewMode?'💪':'🏅'}</div><p className="mt-4 font-black tracking-widest text-cyan-700">{reviewMode?'Hoàn thành lượt ôn lại':'Hoàn thành bài luyện tập'}</p><h1 className="mt-2 text-4xl font-black">{summary.score>=90?'Khởi đầu xuất sắc!':summary.score>=70?'Hoàn thành tốt!':'Mình cùng luyện thêm nhé!'}</h1><div className="mt-6 flex justify-center gap-3 text-5xl">{[1,2,3].map(s=><span key={s} className={s<=summary.stars?'':'grayscale opacity-20'}>⭐</span>)}</div><div className="mt-7 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-sky-50 p-5"><p className="font-black text-sky-700">Điểm số</p><p className="text-3xl font-black">{summary.score}%</p></div><div className="rounded-2xl bg-emerald-50 p-5"><p className="font-black text-emerald-700">Đúng lần đầu</p><p className="text-3xl font-black">{summary.correct}/{results.length}</p></div><div className="rounded-2xl bg-amber-50 p-5"><p className="font-black text-amber-700">Sao nhận được</p><p className="text-3xl font-black">{summary.stars}/3</p></div></div><div className="mt-7 overflow-hidden rounded-3xl border-2 border-slate-100 text-left"><h2 className="bg-slate-50 px-5 py-4 text-xl font-black">Kết quả theo kỹ năng</h2>{summary.bySkill.map(x=>{const p=Math.round(x.correct/x.total*100);return <div key={x.skillId} className="grid gap-2 border-t px-5 py-4 sm:grid-cols-[1fr_auto]"><div><p className="font-black">{GRADE2_REVIEW_SKILL_LABELS[x.skillId]}</p><div className="mt-2 h-2 rounded-full bg-slate-100"><div className={`h-full rounded-full ${p>=70?'bg-emerald-400':'bg-orange-400'}`} style={{width:`${p}%`}}/></div></div><b>{x.correct}/{x.total}</b></div>})}</div><ResultShare score={summary.score} correct={summary.correct} total={results.length} stars={summary.stars} attempts={results} /><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row">{!reviewMode&&missed>0&&<button onClick={review} className="rounded-2xl bg-orange-500 px-6 py-4 font-black text-white">Ôn lại {missed} câu</button>}<button onClick={()=>prepare(size)} className="rounded-2xl bg-cyan-600 px-6 py-4 font-black text-white">Luyện bộ câu mới</button><a href="/lop-2" className="rounded-2xl border-2 border-slate-200 px-6 py-4 font-black">Về lớp 2</a></div></section></main>}
  return <main className="mx-auto max-w-5xl px-4 py-7"><header className="mb-5 flex items-center justify-between"><button onClick={()=>setScreen('intro')} className="rounded-xl bg-white px-4 py-3 font-black shadow-sm">← Thoát</button><div className="text-right"><p className="font-black text-cyan-700">{reviewMode?'Ôn lại · ':''}Câu {index+1}/{questions.length}</p><p className="text-sm font-bold text-slate-500">{GRADE2_REVIEW_SKILL_LABELS[question.skillId]}</p></div></header><div className="mb-6 h-3 overflow-hidden rounded-full bg-white"><div className="h-full bg-gradient-to-r from-cyan-400 to-blue-600" style={{width:`${progress}%`}}/></div><section className="rounded-[2.5rem] border-4 border-white bg-white p-5 shadow-2xl shadow-cyan-100 md:p-9"><div className="mb-6 flex items-center gap-4"><span className="text-5xl">{index%2===0?'🐿️':'🐻'}</span><div><p className="font-black text-cyan-700">{index%2===0?'Sóc Nâu hỏi':'Gấu Mật hỏi'}</p><h1 className="mt-1 text-2xl font-black md:text-3xl">{question.instruction}</h1></div></div><Visual/><div className="mt-6"><Answers/></div>{selected!==null&&!canContinue&&<div className="mt-6 rounded-3xl border-2 border-orange-200 bg-orange-50 p-5"><h2 className="text-xl font-black text-orange-700">💡 Chưa đúng, mình xem lại nhé!</h2><p className="mt-2 font-semibold"><b>Gợi ý {hint}/3:</b> {question.hintSteps[Math.max(0,hint-1)]}</p><button onClick={()=>setSelected(null)} className="mt-4 rounded-xl bg-orange-500 px-5 py-3 font-black text-white">Chọn lại đáp án</button></div>}{canContinue&&<div className="mt-6 rounded-3xl border-2 border-emerald-200 bg-emerald-50 p-5"><div className="flex flex-col items-center justify-between gap-4 sm:flex-row"><div><h2 className="text-xl font-black text-emerald-700">🎉 Chính xác!</h2><SolutionExplanation steps={question.hintSteps} conclusion={question.explanation} /></div><button onClick={next} className="w-full rounded-2xl bg-cyan-600 px-6 py-4 font-black text-white sm:w-auto">{index===questions.length-1?'Xem kết quả':'Câu tiếp theo →'}</button></div></div>}</section></main>
}
