import { useEffect, useMemo, useState } from 'react';
import ResultShare from './ResultShare';
import { buildAdaptiveQuestionSet } from '../lib/learningProfile';
import { playCorrectSound, playFinalSound, playWrongSound } from '../lib/gameAudio';
import { GRADE3_STAGE2_SKILL_LABELS, generateGrade3Stage2Questions, type Grade3Stage2Answer, type Grade3Stage2Module, type Grade3Stage2Question, type Grade3Stage2SkillId } from '../lib/grade3Stage2QuestionGenerator';

type Screen = 'intro' | 'guide' | 'lesson' | 'result';
type PracticeSize = 5 | 10 | 15;
type QuestionResult = { questionId: string; skillId: Grade3Stage2SkillId; attempts: number; correctFirstTry: boolean };
type Props = { module: Grade3Stage2Module };

const CONFIG = {
  geometry: { number: 3, lessons: '16–22', title: 'Hình phẳng và hình khối', description: 'Nhận biết trung điểm, hình tròn, góc, hình chữ nhật, hình vuông và các khối quen thuộc.', accent: 'orange', mascot: '🐿️', topics: [['📍', 'Trung điểm'], ['⭕', 'Hình tròn'], ['📐', 'Góc'], ['🔷', 'Hình phẳng'], ['🧊', 'Hình khối']], guide: [['📍', 'Trung điểm', 'Trung điểm nằm giữa và cách đều hai đầu mút.'], ['📐', 'Góc vuông', 'Có thể so góc với góc của tờ giấy hình chữ nhật.']] },
  multiply100: { number: 4, lessons: '23–29', title: 'Phép nhân, phép chia trong phạm vi 100', description: 'Nhân, chia số có hai chữ số; gấp, giảm một số; chia hết, chia có dư và bài toán hai bước.', accent: 'blue', mascot: '🐻', topics: [['✖️', 'Nhân hai chữ số'], ['➗', 'Chia và số dư'], ['📈', 'Gấp, giảm'], ['📖', 'Bài toán hai bước']], guide: [['➗', 'Số dư', 'Số dư luôn nhỏ hơn số chia.'], ['📖', 'Hai bước tính', 'Đọc kỹ để tìm kết quả bước một trước khi làm bước hai.']] },
  measurement: { number: 5, lessons: '30–35', title: 'Độ dài, khối lượng, dung tích và nhiệt độ', description: 'Làm quen mi-li-mét, gam, mi-li-lít, độ C và vận dụng trong tình huống thực tế.', accent: 'rose', mascot: '🐿️', topics: [['📏', 'Mi-li-mét'], ['⚖️', 'Gam'], ['🧪', 'Mi-li-lít'], ['🌡️', 'Độ C']], guide: [['📏', 'Đọc vạch chia', 'Xác định giá trị giữa hai vạch trước khi đọc.'], ['🔁', 'Đổi đơn vị', '1 cm = 10 mm; 1 kg = 1 000 g; 1 l = 1 000 ml.']] },
} as const;

const TONES = {
  orange: { text: 'text-orange-700', button: 'bg-orange-500 hover:bg-orange-600', bar: 'from-orange-400 to-amber-500', pale: 'bg-orange-50 text-orange-900', shadow: 'shadow-orange-100', selected: 'border-orange-400 bg-orange-50' },
  blue: { text: 'text-blue-700', button: 'bg-blue-600 hover:bg-blue-700', bar: 'from-blue-500 to-indigo-600', pale: 'bg-blue-50 text-blue-900', shadow: 'shadow-blue-100', selected: 'border-blue-400 bg-blue-50' },
  rose: { text: 'text-rose-700', button: 'bg-rose-500 hover:bg-rose-600', bar: 'from-rose-400 to-pink-500', pale: 'bg-rose-50 text-rose-900', shadow: 'shadow-rose-100', selected: 'border-rose-400 bg-rose-50' },
} as const;

const starsFor = (score: number) => score >= 90 ? 3 : score >= 70 ? 2 : 1;

function QuestionVisual({ question, tone }: { question: Grade3Stage2Question; tone: (typeof TONES)[keyof typeof TONES] }) {
  if (question.type === 'expression') return <div className={`grid min-h-64 place-items-center rounded-3xl p-6 ${tone.pale}`}><div className="text-center">{question.caption && <p className="mb-4 font-black opacity-70">{question.caption}</p>}<p className="break-words text-4xl font-black sm:text-6xl">{question.expression}</p></div></div>;

  if (question.type === 'segment') {
    const middleX = 90 + question.leftLength / (question.leftLength + question.rightLength) * 520;
    const points = [90, middleX, 610];
    return <div className={`rounded-3xl p-6 ${tone.pale}`}><svg viewBox="0 0 700 240" className="mx-auto min-h-56 w-full max-w-3xl" role="img" aria-label="Đoạn thẳng có ba điểm"><line x1="90" y1="110" x2="610" y2="110" stroke="#334155" strokeWidth="8" strokeLinecap="round" />{points.map((x, index) => <g key={index}><circle cx={x} cy="110" r="14" fill={index === 1 ? '#f59e0b' : '#0f766e'} /><text x={x} y="75" textAnchor="middle" fontSize="34" fontWeight="900" fill="#0f172a">{question.labels[index]}</text></g>)}<text x={(90 + middleX) / 2} y="165" textAnchor="middle" fontSize="24" fontWeight="800" fill="#475569">{question.leftLength} cm</text><text x={(middleX + 610) / 2} y="165" textAnchor="middle" fontSize="24" fontWeight="800" fill="#475569">{question.rightLength} cm</text></svg></div>;
  }

  if (question.type === 'circle') return <div className={`rounded-3xl p-5 ${tone.pale}`}><svg viewBox="0 0 500 300" className="mx-auto min-h-64 w-full max-w-xl" role="img" aria-label="Hình tròn có tâm, bán kính và đường kính"><circle cx="250" cy="150" r="115" fill="white" stroke="#0284c7" strokeWidth="7" /><line x1="135" y1="150" x2="365" y2="150" stroke="#f97316" strokeWidth={question.focus === 'diameter' ? 9 : 4} /><line x1="250" y1="150" x2="325" y2="63" stroke="#7c3aed" strokeWidth={question.focus === 'radius' ? 9 : 4} /><circle cx="250" cy="150" r={question.focus === 'center' ? 13 : 8} fill="#0f172a" /><text x="250" y="185" textAnchor="middle" fontSize="28" fontWeight="900">O</text><text x="120" y="145" fontSize="26" fontWeight="900">A</text><text x="375" y="145" fontSize="26" fontWeight="900">B</text></svg></div>;

  if (question.type === 'angle') { const endpoint = question.degrees === 90 ? [90, 35] : question.degrees === 45 ? [205, 65] : [20, 55]; return <div className={`rounded-3xl p-6 ${tone.pale}`}><svg viewBox="0 0 340 240" className="mx-auto min-h-56 w-full max-w-md" role="img" aria-label="Hình vẽ một góc"><line x1="90" y1="180" x2="290" y2="180" stroke="#334155" strokeWidth="12" strokeLinecap="round" /><line x1="90" y1="180" x2={endpoint[0]} y2={endpoint[1]} stroke="#334155" strokeWidth="12" strokeLinecap="round" /><circle cx="90" cy="180" r="10" fill="#f59e0b" />{question.degrees === 90 && <path d="M90 145 L125 145 L125 180" fill="none" stroke="#f59e0b" strokeWidth="6" />}</svg></div>; }

  if (question.type === 'shape') { const points = question.shape === 'triangle' ? '250,45 90,220 410,220' : question.shape === 'quadrilateral' ? '110,65 400,45 350,220 70,190' : undefined; return <div className={`grid min-h-64 place-items-center rounded-3xl p-6 ${tone.pale}`}><svg viewBox="0 0 500 270" className="w-full max-w-xl" role="img" aria-label="Hình phẳng">{points ? <polygon points={points} fill="#bfdbfe" stroke="#2563eb" strokeWidth="8" /> : <rect x={(500 - question.width) / 2} y={(270 - question.height) / 2} width={question.width} height={question.height} rx="3" fill="#bbf7d0" stroke="#059669" strokeWidth="8" />}</svg></div>; }

  if (question.type === 'solid') return <div className={`grid min-h-64 place-items-center rounded-3xl p-6 text-center ${tone.pale}`}><div><div className="text-9xl">{question.objectIcon}</div><p className="mt-4 text-2xl font-black">{question.objectName}</p><p className="mt-2 font-bold opacity-70">Quan sát dạng hình khối của đồ vật</p></div></div>;

  if (question.type === 'groups') return <div className={`rounded-3xl p-5 ${tone.pale}`}><div className="flex min-h-56 flex-wrap content-center justify-center gap-3">{Array.from({ length: question.groups }).map((_, index) => <div key={index} className="flex min-w-24 items-center justify-center gap-2 rounded-2xl bg-white p-3 shadow-sm"><span className="text-3xl">{question.icon}</span><b>× {question.perGroup}</b></div>)}</div><p className="text-center font-black">{question.groups} nhóm bằng nhau</p></div>;

  if (question.type === 'bars') { const width = Math.max(question.first, question.second); return <div className={`space-y-6 rounded-3xl p-7 ${tone.pale}`}><div><div className="mb-2 flex justify-between font-black"><span>Số bé</span><span>{question.first}</span></div><div className="h-12 rounded-2xl bg-amber-400" style={{ width: `${question.first / width * 100}%` }} /></div><div><div className="mb-2 flex justify-between font-black"><span>Số lớn</span><span>{question.second}</span></div><div className="h-12 rounded-2xl bg-blue-500" /></div></div>; }

  if (question.type === 'context') return <div className={`grid min-h-64 place-items-center rounded-3xl p-6 text-center ${tone.pale}`}><div><div className="text-8xl">{question.icon}</div><p className="mt-4 text-2xl font-black">{question.visualTitle}</p><p className="mt-2 text-lg font-bold opacity-75">{question.visualText}</p></div></div>;

  if (question.type === 'thermometer') {
    const scaleTop = 40, scaleBottom = 290;
    const liquidTop = scaleBottom - question.temperature / 50 * (scaleBottom - scaleTop);
    return <div className={`grid min-h-72 place-items-center rounded-3xl p-4 ${tone.pale}`}><svg viewBox="0 0 270 340" className="h-72 w-auto max-w-full" role="img" aria-label={`Nhiệt kế chỉ ${question.temperature} độ C`}><rect x="48" y="20" width="64" height="300" rx="32" fill="white" stroke="#cbd5e1" strokeWidth="6" /><line x1="80" y1={liquidTop} x2="80" y2={scaleBottom} stroke="#f43f5e" strokeWidth="17" strokeLinecap="round" /><circle cx="80" cy={scaleBottom} r="27" fill="#f43f5e" />{Array.from({ length: 11 }).map((_, index) => { const value = index * 5, y = scaleBottom - value / 50 * (scaleBottom - scaleTop), major = value % 10 === 0; return <g key={value}><line x1="130" y1={y} x2={major ? 153 : 145} y2={y} stroke="#64748b" strokeWidth={major ? 3 : 2} /><text x="163" y={y + 6} fontSize="18" fontWeight="700" fill="#475569">{value}°</text></g>; })}</svg></div>;
  }

  if (question.measure === 'ruler') {
    const startX = 35, endX = 735, baseline = 125, markX = startX + question.value / question.max * (endX - startX);
    return <div className={`grid min-h-64 place-items-center rounded-3xl p-4 ${tone.pale}`}><svg viewBox="0 0 770 205" className="w-full max-w-3xl" role="img" aria-label={`Thước đo chỉ ${question.value} mi-li-mét`}><rect x="15" y="25" width="740" height="145" rx="18" fill="#fef3c7" stroke="#f59e0b" strokeWidth="5" /><line x1={startX} y1={baseline} x2={endX} y2={baseline} stroke="#92400e" strokeWidth="5" />{Array.from({ length: 101 }).map((_, value) => { const x = startX + value / 100 * (endX - startX), height = value % 10 === 0 ? 38 : value % 5 === 0 ? 27 : 17; return <line key={value} x1={x} y1={baseline} x2={x} y2={baseline - height} stroke="#78350f" strokeWidth={value % 10 === 0 ? 2.5 : 1.2} />; })}<line x1={startX} y1="62" x2={markX} y2="62" stroke="#2563eb" strokeWidth="12" strokeLinecap="round" /><circle cx={markX} cy="62" r="9" fill="#1d4ed8" />{[0, 20, 40, 60, 80, 100].map((value) => <text key={value} x={startX + value / 100 * (endX - startX)} y="155" textAnchor="middle" fontSize="17" fontWeight="800" fill="#78350f">{value}</text>)}<text x="735" y="195" textAnchor="end" fontSize="18" fontWeight="900" fill="#92400e">mm</text></svg></div>;
  }

  if (question.measure === 'scale') {
    const needleAngle = Math.PI * (1 - question.value / question.max);
    const needleX = 150 + Math.cos(needleAngle) * 92;
    const needleY = 175 - Math.sin(needleAngle) * 92;
    return <div className={`grid min-h-72 place-items-center rounded-3xl p-6 ${tone.pale}`}><svg viewBox="0 0 300 220" className="w-full max-w-sm" role="img" aria-label={`Mặt cân chỉ ${question.value} gam`}><path d="M35 175 A115 115 0 0 1 265 175" fill="white" stroke="#475569" strokeWidth="8" />{Array.from({ length: 21 }).map((_, index) => { const angle = Math.PI * (1 - index / 20), major = index % 2 === 0, x1 = 150 + Math.cos(angle) * (major ? 99 : 105), y1 = 175 - Math.sin(angle) * (major ? 99 : 105), x2 = 150 + Math.cos(angle) * 114, y2 = 175 - Math.sin(angle) * 114; return <line key={index} x1={x1} y1={y1} x2={x2} y2={y2} stroke="#334155" strokeWidth={major ? 4 : 2} />; })}<line x1="150" y1="175" x2={needleX} y2={needleY} stroke="#ef4444" strokeWidth="7" strokeLinecap="round" /><circle cx="150" cy="175" r="11" fill="#0f172a" /><text x="30" y="205" fontSize="18" fontWeight="900">0</text><text x="132" y="55" fontSize="18" fontWeight="900">500</text><text x="235" y="205" fontSize="18" fontWeight="900">1 000 g</text></svg></div>;
  }

  const jugTop = 30, jugBottom = 290, waterTop = jugBottom - question.value / question.max * (jugBottom - jugTop);
  return <div className={`grid min-h-72 place-items-center rounded-3xl p-4 ${tone.pale}`}><svg viewBox="0 0 340 330" className="h-72 w-auto max-w-full" role="img" aria-label={`Bình có ${question.value} mi-li-lít nước`}><path d="M55 30 L55 285 Q55 310 80 310 L190 310 Q215 310 215 285 L215 30" fill="white" stroke="#0284c7" strokeWidth="7" /><path d={`M59 ${waterTop} L211 ${waterTop} L211 285 Q211 306 190 306 L80 306 Q59 306 59 285 Z`} fill="#7dd3fc" /><line x1="59" y1={waterTop} x2="211" y2={waterTop} stroke="#0369a1" strokeWidth="5" />{Array.from({ length: 11 }).map((_, index) => { const value = index * 100, y = jugBottom - value / 1000 * (jugBottom - jugTop); return <g key={value}><line x1="215" y1={y} x2="250" y2={y} stroke="#075985" strokeWidth="2.5" /><text x="330" y={y + 6} textAnchor="end" fontSize="16" fontWeight="800" fill="#075985">{value} ml</text></g>; })}</svg></div>;
}

export default function Grade3Stage2Game({ module }: Props) {
  const config = CONFIG[module], tone = TONES[config.accent], storageKey = `trang-toan:lop-3:${module}:best-v1`;
  const [screen, setScreen] = useState<Screen>('intro'), [size, setSize] = useState<PracticeSize>(10), [questions, setQuestions] = useState<Grade3Stage2Question[]>([]), [index, setIndex] = useState(0), [selected, setSelected] = useState<Grade3Stage2Answer | null>(null), [attempts, setAttempts] = useState(0), [hint, setHint] = useState(0), [canContinue, setCanContinue] = useState(false), [results, setResults] = useState<QuestionResult[]>([]), [best, setBest] = useState<{ score: number; stars: number } | null>(null), [reviewMode, setReviewMode] = useState(false);
  useEffect(() => { setQuestions(generateGrade3Stage2Questions(module, 10)); const saved = localStorage.getItem(storageKey); if (saved) try { setBest(JSON.parse(saved)); } catch { localStorage.removeItem(storageKey); } }, [module, storageKey]);
  const question = questions[index], progress = questions.length ? (index + 1) / questions.length * 100 : 0;
  const summary = useMemo(() => { const correct = results.filter((result) => result.correctFirstTry).length, score = results.length ? Math.round(correct / results.length * 100) : 0; const bySkill = [...new Set(results.map((result) => result.skillId))].map((skillId) => { const list = results.filter((result) => result.skillId === skillId); return { skillId, total: list.length, correct: list.filter((result) => result.correctFirstTry).length }; }); return { correct, score, stars: starsFor(score), bySkill }; }, [results]);
  const reset = () => { setSelected(null); setAttempts(0); setHint(0); setCanContinue(false); };
  function prepare(nextSize: PracticeSize) { setSize(nextSize); setQuestions(buildAdaptiveQuestionSet(() => generateGrade3Stage2Questions(module, nextSize), nextSize)); setIndex(0); setResults([]); setReviewMode(false); reset(); setScreen('guide'); }
  function choose(answer: Grade3Stage2Answer) { if (!question || canContinue) return; const next = attempts + 1; setAttempts(next); setSelected(answer); if (answer === question.correctAnswer) { playCorrectSound(); setCanContinue(true); setResults((current) => [...current, { questionId: question.id, skillId: question.skillId, attempts: next, correctFirstTry: next === 1 }]); } else { playWrongSound(); setHint(Math.min(next, 3)); } }
  function next() { if (index < questions.length - 1) { setIndex((value) => value + 1); reset(); return; } if (!reviewMode) { const correct = results.filter((result) => result.correctFirstTry).length, score = Math.round(correct / questions.length * 100), saved = { score, stars: starsFor(score) }; if (!best || score > best.score) { localStorage.setItem(storageKey, JSON.stringify(saved)); setBest(saved); } } playFinalSound(); setScreen('result'); }
  function review() { const ids = new Set(results.filter((result) => !result.correctFirstTry).map((result) => result.questionId)), missed = questions.filter((item) => ids.has(item.id)); if (!missed.length) return; setQuestions(missed); setIndex(0); setResults([]); setReviewMode(true); reset(); setScreen('lesson'); }
  function answerClass(answer: Grade3Stage2Answer) { if (selected === answer && answer !== question.correctAnswer) return 'border-red-400 bg-red-50 text-red-700'; if (canContinue && answer === question.correctAnswer) return 'border-emerald-400 bg-emerald-50 text-emerald-700'; return 'border-slate-200 bg-white text-slate-800 hover:-translate-y-1 hover:border-amber-300 hover:bg-amber-50'; }

  if (!questions.length) return <main className="grid min-h-screen place-items-center"><div className="text-center"><div className="text-7xl">{config.mascot}</div><p className={`mt-4 text-xl font-black ${tone.text}`}>Đang chuẩn bị bài luyện...</p></div></main>;
  if (screen === 'intro') return <main className="mx-auto max-w-5xl px-4 py-8 md:py-12"><a href="/lop-3" className="inline-flex rounded-xl bg-white px-4 py-3 font-black text-slate-600 shadow-sm">← Lớp 3</a><section className={`mt-6 overflow-hidden rounded-[2.5rem] border-4 border-white bg-white shadow-2xl ${tone.shadow}`}><div className={`bg-gradient-to-br ${tone.bar} p-8 text-white md:p-12`}><p className="font-black tracking-widest text-white/75">Mục {config.number} · Bài {config.lessons}</p><h1 className="mt-2 text-3xl font-black md:text-5xl">{config.title}</h1><p className="mt-4 max-w-3xl text-lg font-semibold leading-8 text-white/90">{config.description}</p></div><div className="p-6 md:p-10"><div className={`grid gap-3 sm:grid-cols-2 ${config.topics.length === 5 ? 'lg:grid-cols-5' : 'lg:grid-cols-4'}`}>{config.topics.map(([icon, label]) => <div key={label} className="rounded-2xl bg-slate-50 p-4 text-center"><div className="text-3xl">{icon}</div><p className="mt-2 font-black text-slate-700">{label}</p></div>)}</div><h2 className="mt-8 text-xl font-black">Chọn lượt luyện tập</h2><div className="mt-4 grid gap-4 md:grid-cols-3">{([[5, 'Luyện nhanh', 'Mỗi kỹ năng chính một câu'], [10, 'Luyện chuẩn', 'Đủ nhận biết và vận dụng'], [15, 'Thử thách', 'Nhiều tình huống thực tế hơn']] as const).map(([count, title, description]) => <button key={count} onClick={() => prepare(count)} className={`rounded-3xl border-4 p-5 text-left transition hover:-translate-y-1 ${count === 10 ? `${tone.selected} shadow-lg` : 'border-slate-100 bg-white hover:border-amber-300'}`}><span className={`text-sm font-black ${tone.text}`}>{count} câu</span><span className="mt-1 block text-xl font-black">{title}</span><span className="mt-2 block font-semibold text-slate-500">{description}</span></button>)}</div>{best && <p className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-4 font-bold text-amber-800">Kết quả tốt nhất: {best.score}% · {'⭐'.repeat(best.stars)}</p>}</div></section></main>;
  if (screen === 'guide') return <main className="mx-auto max-w-4xl px-4 py-10"><section className={`rounded-[2.5rem] border-4 border-white bg-white p-7 shadow-2xl ${tone.shadow} md:p-10`}><div className="flex items-start gap-4"><span className="text-6xl">{config.mascot}</span><div><p className={`font-black ${tone.text}`}>Nhớ kỹ trước khi làm</p><h1 className="mt-1 text-3xl font-black">Quan sát hình và tách từng bước</h1></div></div><div className="my-7 grid gap-4 sm:grid-cols-2">{config.guide.map(([icon, title, description], guideIndex) => <div key={title} className={`rounded-3xl p-5 ${guideIndex ? 'bg-amber-50' : tone.pale}`}><p className="font-black">{icon} {title}</p><p className="mt-2 font-semibold text-slate-600">{description}</p></div>)}</div><button onClick={() => setScreen('lesson')} className={`w-full rounded-2xl px-7 py-4 text-lg font-black text-white ${tone.button}`}>Bắt đầu {size} câu</button></section></main>;
  if (screen === 'result') { const missed = results.filter((result) => !result.correctFirstTry).length; return <main className="mx-auto max-w-4xl px-4 py-10"><section className={`rounded-[2.5rem] border-4 border-white bg-white p-7 text-center shadow-2xl ${tone.shadow} md:p-10`}><div className="text-7xl">{reviewMode ? '💪' : '🏅'}</div><p className={`mt-4 font-black tracking-widest ${tone.text}`}>{reviewMode ? 'Hoàn thành lượt ôn lại' : 'Hoàn thành bài luyện tập'}</p><h1 className="mt-2 text-4xl font-black">{summary.score >= 90 ? 'Quan sát và tính toán rất tốt!' : summary.score >= 70 ? 'Hoàn thành tốt!' : 'Mình cùng luyện thêm nhé!'}</h1><div className="mt-6 flex justify-center gap-3 text-5xl">{[1, 2, 3].map((star) => <span key={star} className={star <= summary.stars ? '' : 'grayscale opacity-20'}>⭐</span>)}</div><div className="mt-7 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-sky-50 p-5"><p className="font-black text-sky-700">Điểm số</p><p className="text-3xl font-black">{summary.score}%</p></div><div className="rounded-2xl bg-emerald-50 p-5"><p className="font-black text-emerald-700">Đúng lần đầu</p><p className="text-3xl font-black">{summary.correct}/{results.length}</p></div><div className="rounded-2xl bg-amber-50 p-5"><p className="font-black text-amber-700">Sao nhận được</p><p className="text-3xl font-black">{summary.stars}/3</p></div></div><div className="mt-7 overflow-hidden rounded-3xl border-2 border-slate-100 text-left"><h2 className="bg-slate-50 px-5 py-4 text-xl font-black">Kết quả theo kỹ năng</h2>{summary.bySkill.map((skill) => <div key={skill.skillId} className="grid grid-cols-[1fr_auto] gap-3 border-t px-5 py-4"><b>{GRADE3_STAGE2_SKILL_LABELS[skill.skillId]}</b><b>{skill.correct}/{skill.total}</b></div>)}</div><ResultShare score={summary.score} correct={summary.correct} total={results.length} stars={summary.stars} attempts={results} /><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row">{!reviewMode && missed > 0 && <button onClick={review} className="rounded-2xl bg-orange-500 px-6 py-4 font-black text-white">Ôn lại {missed} câu</button>}<button onClick={() => prepare(size)} className={`rounded-2xl px-6 py-4 font-black text-white ${tone.button}`}>Luyện bộ câu mới</button><a href="/lop-3" className="rounded-2xl border-2 border-slate-200 px-6 py-4 font-black">Về lớp 3</a></div></section></main>; }
  const longAnswers = question.answers.some((answer) => String(answer).length > 12);
  return <main className="mx-auto max-w-5xl px-4 py-7"><header className="mb-5 flex items-center justify-between gap-8"><button onClick={() => setScreen('intro')} className="shrink-0 rounded-xl bg-white px-4 py-3 font-black shadow-sm">← Thoát</button><div className="text-right"><p className={`font-black ${tone.text}`}>{reviewMode ? 'Ôn lại · ' : ''}Câu {index + 1}/{questions.length}</p><p className="text-sm font-bold text-slate-500">{GRADE3_STAGE2_SKILL_LABELS[question.skillId]}</p></div></header><div className="mb-6 h-3 overflow-hidden rounded-full bg-white"><div className={`h-full bg-gradient-to-r ${tone.bar}`} style={{ width: `${progress}%` }} /></div><section className={`rounded-[2.5rem] border-4 border-white bg-white p-5 shadow-2xl ${tone.shadow} md:p-9`}><div className="mb-6 flex items-center gap-4"><span className="text-5xl">{index % 2 ? '🐻' : '🐿️'}</span><div><p className={`font-black ${tone.text}`}>{index % 2 ? 'Gấu Mật hỏi' : 'Sóc Nâu hỏi'}</p><h1 className="mt-1 text-2xl font-black md:text-3xl">{question.instruction}</h1></div></div><QuestionVisual question={question} tone={tone} /><div className={`mt-6 grid gap-3 ${longAnswers ? 'sm:grid-cols-2' : question.answers.length === 2 ? 'grid-cols-2' : 'grid-cols-2 sm:grid-cols-4'}`}>{question.answers.map((answer) => <button key={String(answer)} disabled={canContinue} onClick={() => choose(answer)} className={`min-h-20 rounded-2xl border-4 px-3 py-4 text-lg font-black shadow-sm transition md:text-xl ${answerClass(answer)}`}>{answer}{question.type === 'thermometer' && typeof answer === 'number' ? '°C' : question.type === 'measurement' && typeof answer === 'number' ? ` ${question.unit}` : ''}</button>)}</div>{selected !== null && !canContinue && <div className="mt-6 rounded-3xl border-2 border-orange-200 bg-orange-50 p-5"><h2 className="text-xl font-black text-orange-700">💡 Chưa đúng, mình quan sát lại nhé!</h2><p className="mt-2 font-semibold"><b>Gợi ý {hint}/3:</b> {question.hintSteps[Math.max(0, hint - 1)]}</p><button onClick={() => setSelected(null)} className="mt-4 rounded-xl bg-orange-500 px-5 py-3 font-black text-white">Chọn lại đáp án</button></div>}{canContinue && <div className="mt-6 rounded-3xl border-2 border-emerald-200 bg-emerald-50 p-5"><div className="flex flex-col items-center justify-between gap-4 sm:flex-row"><div><h2 className="text-xl font-black text-emerald-700">🎉 Chính xác!</h2><p className="mt-1 font-semibold">{question.explanation}</p></div><button onClick={next} className={`w-full rounded-2xl px-6 py-4 font-black text-white sm:w-auto ${tone.button}`}>{index === questions.length - 1 ? 'Xem kết quả' : 'Câu tiếp theo →'}</button></div></div>}</section></main>;
}
