import { useEffect, useMemo, useState } from 'react';
import ResultShare from './ResultShare';
import SolutionExplanation from './SolutionExplanation';
import { buildAdaptiveQuestionSet } from '../lib/learningProfile';
import { playCorrectSound, playFinalSound, playWrongSound } from '../lib/gameAudio';
import { GRADE5_SKILL_LABELS, generateGrade5Questions, type Grade5Answer, type Grade5Module, type Grade5Question, type Grade5SkillId } from '../lib/grade5QuestionGenerator';

type Screen = 'intro' | 'guide' | 'lesson' | 'result';
type PracticeSize = 5 | 10 | 15;
type QuestionResult = { questionId: string; skillId: Grade5SkillId; attempts: number; correctFirstTry: boolean };
type Props = { module: Grade5Module };

const CONFIG = {
  review: { number: 1, lessons: '1–9', title: 'Ôn tập và bổ sung', description: 'Ôn số tự nhiên, phân số, hỗn số, phép tính, hình học và đo lường.', accent: 'orange', topics: [['🔢', 'Số tự nhiên'], ['🍕', 'Phân số và hỗn số'], ['🧮', 'Phép tính'], ['📐', 'Hình học']], guideTitle: 'Ôn từ kiến thức quen thuộc', tips: [['🔎', 'Đọc kĩ', 'Xác định dạng toán và đơn vị trước khi tính.'], ['✅', 'Kiểm tra', 'Dùng phép tính ngược hoặc thay kết quả vào đề.']] },
  decimals: { number: 2, lessons: '10–14', title: 'Số thập phân', description: 'Nhận biết, đọc, viết, so sánh và làm tròn số thập phân.', accent: 'cyan', topics: [['🔎', 'Giá trị hàng'], ['⚖️', 'So sánh'], ['✍️', 'Viết số'], ['🎯', 'Làm tròn']], guideTitle: 'Quan sát phần nguyên và từng hàng sau dấu phẩy', tips: [['🔢', 'Giá trị hàng', 'Sau dấu phẩy là hàng phần mười, phần trăm, phần nghìn.'], ['🎯', 'Làm tròn', 'Nhìn chữ số ngay bên phải hàng cần làm tròn.']] },
  'area-units': { number: 3, lessons: '15–18', title: 'Một số đơn vị đo diện tích', description: 'Luyện ki-lô-mét vuông, héc-ta và quan hệ giữa các đơn vị diện tích.', accent: 'emerald', topics: [['🗺️', 'Ki-lô-mét vuông'], ['🌾', 'Héc-ta'], ['🔄', 'Đổi đơn vị'], ['⚖️', 'So sánh']], guideTitle: 'Đổi về cùng đơn vị', tips: [['🌾', 'Héc-ta', '1 ha = 10 000 m².'], ['🗺️', 'Ki-lô-mét vuông', '1 km² = 100 ha = 1 000 000 m².']] },
  'decimal-operations': { number: 4, lessons: '19–24', title: 'Các phép tính với số thập phân', description: 'Cộng, trừ, nhân, chia và tính nhẩm với 10, 100, 1 000.', accent: 'indigo', topics: [['➕', 'Cộng'], ['➖', 'Trừ'], ['✖️', 'Nhân'], ['➗', 'Chia'], ['⚡', 'Tính nhẩm']], guideTitle: 'Đặt dấu phẩy đúng vị trí', tips: [['➕', 'Cộng và trừ', 'Đặt các dấu phẩy thẳng cột.'], ['⚡', 'Nhân chia nhẩm', 'Dịch dấu phẩy theo số chữ số 0.']] },
  'plane-geometry': { number: 5, lessons: '25–29', title: 'Một số hình phẳng, chu vi và diện tích', description: 'Tính diện tích tam giác, hình thang; chu vi và diện tích hình tròn.', accent: 'rose', topics: [['🔺', 'Tam giác'], ['⏢', 'Hình thang'], ['⭕', 'Hình tròn'], ['📐', 'Diện tích']], guideTitle: 'Chọn đúng công thức của từng hình', tips: [['🔺', 'Tam giác', 'S = đáy × cao : 2.'], ['⭕', 'Hình tròn', 'C = r × 2 × 3,14; S = r × r × 3,14.']] },
  'semester-1-review': { number: 6, lessons: '30–35', title: 'Ôn tập học kỳ I', description: 'Ôn số thập phân, phép tính, hình phẳng và đo lường.', accent: 'fuchsia', topics: [['🔢', 'Số thập phân'], ['🧮', 'Phép tính'], ['📐', 'Hình phẳng'], ['📏', 'Đo lường']], guideTitle: 'Tổng hợp kiến thức học kỳ I', tips: [['🧠', 'Phân loại', 'Nhận dạng dạng toán trước khi chọn công thức.'], ['✅', 'Kiểm tra', 'Ghi đủ đơn vị và xem kết quả có hợp lí không.']] },
  'ratio-percent': { number: 7, lessons: '36–44', title: 'Tỉ số và các bài toán liên quan', description: 'Tỉ số, tỉ lệ bản đồ, tổng – tỉ, hiệu – tỉ và tỉ số phần trăm.', accent: 'amber', topics: [['⚖️', 'Tỉ số'], ['🗺️', 'Tỉ lệ bản đồ'], ['🧩', 'Tổng – tỉ'], ['💯', 'Phần trăm']], guideTitle: 'Xác định tổng số phần và giá trị một phần', tips: [['🧩', 'Sơ đồ phần', 'Tìm giá trị một phần rồi nhân số phần.'], ['💯', 'Phần trăm', 'Tỉ số phần trăm = phần : toàn bộ × 100%.']] },
  'volume-units': { number: 8, lessons: '45–48', title: 'Thể tích, đơn vị đo thể tích', description: 'Nhận biết thể tích và đổi cm³, dm³, m³.', accent: 'sky', topics: [['🧱', 'Khối đơn vị'], ['🟦', 'Xăng-ti-mét khối'], ['📦', 'Đề-xi-mét khối'], ['🏠', 'Mét khối']], guideTitle: 'Mỗi bậc đơn vị thể tích hơn kém 1 000 lần', tips: [['🔄', 'Đổi đơn vị', '1 m³ = 1 000 dm³; 1 dm³ = 1 000 cm³.'], ['🧱', 'Đếm khối', 'Số khối = dài × rộng × số lớp.']] },
  'solid-geometry': { number: 9, lessons: '49–55', title: 'Diện tích và thể tích của một số hình khối', description: 'Tính diện tích và thể tích hình hộp chữ nhật, hình lập phương.', accent: 'blue', topics: [['📦', 'Hình hộp chữ nhật'], ['🎲', 'Hình lập phương'], ['📐', 'Diện tích'], ['🧱', 'Thể tích']], guideTitle: 'Phân biệt diện tích xung quanh, toàn phần và thể tích', tips: [['📦', 'Hình hộp', 'V = dài × rộng × cao.'], ['🎲', 'Hình lập phương', 'V = a × a × a; Stp = a × a × 6.']] },
  'time-speed': { number: 10, lessons: '56–62', title: 'Số đo thời gian, vận tốc và chuyển động đều', description: 'Tính với thời gian và giải bài toán vận tốc, quãng đường, thời gian.', accent: 'red', topics: [['⏱️', 'Số đo thời gian'], ['🚗', 'Vận tốc'], ['🛣️', 'Quãng đường'], ['⌛', 'Thời gian']], guideTitle: 'Ghi nhớ tam giác công thức s – v – t', tips: [['🚗', 'Vận tốc', 'v = s : t.'], ['🛣️', 'Quãng đường', 's = v × t; t = s : v.']] },
  statistics: { number: 11, lessons: '63–67', title: 'Một số yếu tố thống kê và xác suất', description: 'Thu thập, phân loại, đọc biểu đồ quạt tròn và tính tỉ số lặp lại.', accent: 'teal', topics: [['🔢', 'Dữ liệu'], ['📊', 'Phân tích'], ['🥧', 'Biểu đồ quạt tròn'], ['🎲', 'Tỉ số lặp lại']], guideTitle: 'Đọc nhãn, tỉ lệ và tổng số đối tượng', tips: [['🥧', 'Biểu đồ quạt tròn', 'Toàn bộ hình tròn biểu diễn 100%.'], ['🎲', 'Tỉ số lặp lại', 'Số lần xuất hiện chia tổng số lần thực hiện.']] },
  'final-review': { number: 12, lessons: '68–75', title: 'Ôn tập cuối năm', description: 'Ôn tổng hợp số, phép tính, tỉ số, hình học, chuyển động và dữ liệu.', accent: 'pink', topics: [['🧮', 'Số và phép tính'], ['💯', 'Tỉ số'], ['📐', 'Hình học'], ['🚗', 'Chuyển động'], ['📊', 'Dữ liệu']], guideTitle: 'Vận dụng kiến thức cả năm', tips: [['🧠', 'Lập kế hoạch', 'Xác định công thức và thứ tự các bước.'], ['✅', 'Tự kiểm tra', 'Ước lượng và kiểm tra đơn vị của kết quả.']] },
} as const;

const THEMES = {
  orange: ['text-orange-700', 'bg-orange-600 hover:bg-orange-700', 'from-orange-400 to-amber-500', 'bg-orange-50 text-orange-950', 'border-orange-400 bg-orange-50'],
  cyan: ['text-cyan-700', 'bg-cyan-600 hover:bg-cyan-700', 'from-cyan-400 to-blue-600', 'bg-cyan-50 text-cyan-950', 'border-cyan-400 bg-cyan-50'],
  emerald: ['text-emerald-700', 'bg-emerald-600 hover:bg-emerald-700', 'from-emerald-400 to-teal-600', 'bg-emerald-50 text-emerald-950', 'border-emerald-400 bg-emerald-50'],
  indigo: ['text-indigo-700', 'bg-indigo-600 hover:bg-indigo-700', 'from-indigo-400 to-violet-600', 'bg-indigo-50 text-indigo-950', 'border-indigo-400 bg-indigo-50'],
  rose: ['text-rose-700', 'bg-rose-600 hover:bg-rose-700', 'from-rose-400 to-pink-600', 'bg-rose-50 text-rose-950', 'border-rose-400 bg-rose-50'],
  fuchsia: ['text-fuchsia-700', 'bg-fuchsia-600 hover:bg-fuchsia-700', 'from-fuchsia-500 to-purple-600', 'bg-fuchsia-50 text-fuchsia-950', 'border-fuchsia-400 bg-fuchsia-50'],
  amber: ['text-amber-700', 'bg-amber-600 hover:bg-amber-700', 'from-amber-400 to-orange-500', 'bg-amber-50 text-amber-950', 'border-amber-400 bg-amber-50'],
  sky: ['text-sky-700', 'bg-sky-600 hover:bg-sky-700', 'from-sky-400 to-cyan-600', 'bg-sky-50 text-sky-950', 'border-sky-400 bg-sky-50'],
  blue: ['text-blue-700', 'bg-blue-600 hover:bg-blue-700', 'from-blue-500 to-indigo-600', 'bg-blue-50 text-blue-950', 'border-blue-400 bg-blue-50'],
  red: ['text-red-700', 'bg-red-600 hover:bg-red-700', 'from-red-500 to-orange-500', 'bg-red-50 text-red-950', 'border-red-400 bg-red-50'],
  teal: ['text-teal-700', 'bg-teal-600 hover:bg-teal-700', 'from-teal-500 to-emerald-600', 'bg-teal-50 text-teal-950', 'border-teal-400 bg-teal-50'],
  pink: ['text-pink-700', 'bg-pink-600 hover:bg-pink-700', 'from-pink-500 to-rose-600', 'bg-pink-50 text-pink-950', 'border-pink-400 bg-pink-50'],
} as const;

function display(answer: Grade5Answer) { return typeof answer === 'number' ? answer.toLocaleString('vi-VN', { maximumFractionDigits: 5 }) : answer; }
function stars(score: number) { return score >= 90 ? 3 : score >= 70 ? 2 : 1; }

function Visual({ question, tone }: { question: Grade5Question; tone: string }) {
  if (question.type === 'expression') return <div className={`grid min-h-64 place-items-center rounded-3xl p-6 ${tone}`}><div className="text-center">{question.caption && <p className="mb-4 font-black opacity-65">{question.caption}</p>}<p className="break-words text-4xl font-black sm:text-6xl">{question.expression}</p></div></div>;
  if (question.type === 'compare') return <div className={`grid min-h-64 grid-cols-[1fr_auto_1fr] place-items-center gap-4 rounded-3xl p-5 text-4xl font-black sm:text-6xl ${tone}`}><span>{question.left}</span><span className="text-amber-500">?</span><span>{question.right}</span></div>;
  if (question.type === 'fraction') return <div className={`grid min-h-64 place-items-center rounded-3xl p-6 ${tone}`}><div className="w-full max-w-xl text-center"><p className="mb-5 text-xl font-black">{question.caption}</p><div className="grid overflow-hidden rounded-2xl border-4 border-current bg-white" style={{ gridTemplateColumns: `repeat(${question.denominator},1fr)` }}>{Array.from({ length: question.denominator }, (_, index) => <span key={index} className={`h-28 border-r-2 border-current last:border-0 ${index < question.numerator ? 'bg-amber-400' : ''}`} />)}</div></div></div>;
  if (question.type === 'bars') { const max = Math.max(...question.values); return <div className={`rounded-3xl p-5 ${tone}`}><p className="text-center text-lg font-black">{question.chartTitle}</p><div className="mx-auto mt-4 flex h-56 max-w-2xl items-end justify-around gap-3 border-b-4 border-l-4 border-current px-4">{question.values.map((value, index) => <div key={question.labels[index]} className="flex h-full flex-1 flex-col items-center justify-end"><b>{value}</b><div className="w-full max-w-20 rounded-t-lg bg-teal-500" style={{ height: `${Math.max(20, value / max * 75)}%` }} /><b className="mt-2">{question.labels[index]}</b></div>)}</div></div>; }
  if (question.type === 'shape') {
    const [a = 4, b = 3, c = 2] = question.measures;
    return <div className={`rounded-3xl p-5 ${tone}`}><svg viewBox="0 0 420 250" className="mx-auto h-60 w-full max-w-2xl" role="img" aria-label={question.caption}>
      {question.shape === 'triangle' && <><polygon points="75,205 345,205 240,45" fill="#fb7185" fillOpacity=".35" stroke="currentColor" strokeWidth="7" /><line x1="240" y1="45" x2="240" y2="205" stroke="#f59e0b" strokeWidth="5" strokeDasharray="8 8" /></>}
      {question.shape === 'trapezoid' && <><polygon points="65,205 355,205 295,65 135,65" fill="#38bdf8" fillOpacity=".35" stroke="currentColor" strokeWidth="7" /><line x1="135" y1="65" x2="135" y2="205" stroke="#f59e0b" strokeWidth="5" strokeDasharray="8 8" /></>}
      {question.shape === 'circle' && <><circle cx="210" cy="125" r="92" fill="#fbbf24" fillOpacity=".3" stroke="currentColor" strokeWidth="7" /><line x1="210" y1="125" x2="302" y2="125" stroke="#ef4444" strokeWidth="6" /><text x="247" y="112" className="fill-current text-xl font-black">r = {a}</text></>}
      {(question.shape === 'cuboid' || question.shape === 'cube') && <><path d="M90 85 L270 85 L340 40 L160 40 Z M90 85 L90 205 L270 205 L270 85 M270 205 L340 160 L340 40" fill="#60a5fa" fillOpacity=".25" stroke="currentColor" strokeWidth="7" strokeLinejoin="round" /><text x="145" y="230" className="fill-current text-lg font-black">{question.shape === 'cube' ? `a = ${a}` : `${a} × ${b} × ${c}`}</text></>}
      {question.shape === 'pie' && <><circle cx="210" cy="125" r="90" fill="#e2e8f0" /><path d={`M210 125 L210 35 A90 90 0 ${a > 50 ? 1 : 0} 1 ${210 + 90 * Math.sin(a * Math.PI / 50)} ${125 - 90 * Math.cos(a * Math.PI / 50)} Z`} fill="#14b8a6" /><text x="210" y="135" textAnchor="middle" className="fill-slate-900 text-2xl font-black">{a}%</text></>}
    </svg><p className="text-center text-xl font-black">{question.caption}</p></div>;
  }
  return <div className={`grid min-h-64 place-items-center rounded-3xl p-6 text-center ${tone}`}><div><div className="text-7xl">{question.icon}</div><p className="mt-4 text-2xl font-black">{question.visualTitle}</p>{question.visualLines.map((line) => <p key={line} className="mt-1 text-lg font-bold opacity-70">{line}</p>)}</div></div>;
}

export default function Grade5Game({ module }: Props) {
  const config = CONFIG[module];
  const [text, button, bar, tone, selectedTone] = THEMES[config.accent];
  const storageKey = `trang-toan:lop-5:${module}:best-v1`;
  const [screen, setScreen] = useState<Screen>('intro');
  const [size, setSize] = useState<PracticeSize>(10);
  const [questions, setQuestions] = useState<Grade5Question[]>([]);
  const [index, setIndex] = useState(0);
  const [selected, setSelected] = useState<Grade5Answer | null>(null);
  const [attempts, setAttempts] = useState(0);
  const [hint, setHint] = useState(0);
  const [canContinue, setCanContinue] = useState(false);
  const [results, setResults] = useState<QuestionResult[]>([]);
  const [best, setBest] = useState<{ score: number; stars: number } | null>(null);
  const [reviewMode, setReviewMode] = useState(false);

  useEffect(() => {
    setQuestions(generateGrade5Questions(module, 10));
    const saved = localStorage.getItem(storageKey);
    if (saved) try { setBest(JSON.parse(saved)); } catch { localStorage.removeItem(storageKey); }
  }, [module, storageKey]);

  const question = questions[index];
  const summary = useMemo(() => {
    const correct = results.filter((item) => item.correctFirstTry).length;
    const score = results.length ? Math.round(correct / results.length * 100) : 0;
    const bySkill = [...new Set(results.map((item) => item.skillId))].map((skillId) => { const entries = results.filter((item) => item.skillId === skillId); return { skillId, total: entries.length, correct: entries.filter((item) => item.correctFirstTry).length }; });
    return { correct, score, stars: stars(score), bySkill };
  }, [results]);

  function resetQuestion() { setSelected(null); setAttempts(0); setHint(0); setCanContinue(false); }
  function prepare(nextSize: PracticeSize) { setSize(nextSize); setQuestions(buildAdaptiveQuestionSet(() => generateGrade5Questions(module, nextSize), nextSize)); setIndex(0); setResults([]); setReviewMode(false); resetQuestion(); setScreen('guide'); }
  function choose(answer: Grade5Answer) { if (!question || canContinue) return; const nextAttempts = attempts + 1; setAttempts(nextAttempts); setSelected(answer); if (answer === question.correctAnswer) { playCorrectSound(); setCanContinue(true); setResults((current) => [...current, { questionId: question.id, skillId: question.skillId, attempts: nextAttempts, correctFirstTry: nextAttempts === 1 }]); } else { playWrongSound(); setHint(Math.min(nextAttempts, 3)); } }
  function next() { if (index < questions.length - 1) { setIndex((value) => value + 1); resetQuestion(); return; } if (!reviewMode) { const score = Math.round(results.filter((item) => item.correctFirstTry).length / questions.length * 100); const saved = { score, stars: stars(score) }; if (!best || score > best.score) { localStorage.setItem(storageKey, JSON.stringify(saved)); setBest(saved); } } playFinalSound(); setScreen('result'); }
  function reviewMistakes() { const missed = new Set(results.filter((item) => !item.correctFirstTry).map((item) => item.questionId)); const nextQuestions = questions.filter((item) => missed.has(item.id)); if (!nextQuestions.length) return; setQuestions(nextQuestions); setIndex(0); setResults([]); setReviewMode(true); resetQuestion(); setScreen('lesson'); }
  function answerClass(answer: Grade5Answer) { if (selected === answer && answer !== question.correctAnswer) return 'border-red-400 bg-red-50 text-red-700'; if (canContinue && answer === question.correctAnswer) return 'border-emerald-400 bg-emerald-50 text-emerald-700'; return 'border-slate-200 bg-white hover:-translate-y-1 hover:border-amber-300 hover:bg-amber-50'; }

  if (!question) return <main className="grid min-h-screen place-items-center"><p className={`text-xl font-black ${text}`}>🦊 Đang chuẩn bị bài luyện...</p></main>;
  if (screen === 'intro') return <main className="mx-auto max-w-5xl px-4 py-8"><a href="/lop-5" className="rounded-xl bg-white px-4 py-3 font-black shadow-sm">← Lớp 5</a><section className="mt-6 overflow-hidden rounded-[2.5rem] border-4 border-white bg-white shadow-2xl"><div className={`bg-gradient-to-br ${bar} p-8 text-white md:p-12`}><p className="font-black tracking-widest text-white/75">Mục {config.number} · Bài {config.lessons}</p><h1 className="mt-2 text-3xl font-black md:text-5xl">{config.title}</h1><p className="mt-4 max-w-3xl text-lg font-semibold leading-8 text-white/90">{config.description}</p></div><div className="p-6 md:p-10"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{config.topics.map(([icon, label]) => <div key={label} className="rounded-2xl bg-slate-50 p-4 text-center"><div className="text-3xl">{icon}</div><p className="mt-2 font-black">{label}</p></div>)}</div><h2 className="mt-8 text-xl font-black">Chọn lượt luyện tập</h2><div className="mt-4 grid gap-4 md:grid-cols-3">{([[5, 'Luyện nhanh', 'Khởi động kiến thức'], [10, 'Luyện chuẩn', 'Cân bằng các kĩ năng'], [15, 'Thử thách', 'Nhiều biến thể hơn']] as const).map(([count, title, description]) => <button key={count} onClick={() => prepare(count)} className={`rounded-3xl border-4 p-5 text-left transition hover:-translate-y-1 ${count === 10 ? selectedTone : 'border-slate-100 bg-white hover:border-amber-300'}`}><span className={`text-sm font-black ${text}`}>{count} câu</span><span className="mt-1 block text-xl font-black">{title}</span><span className="mt-2 block font-semibold text-slate-500">{description}</span></button>)}</div>{best && <p className="mt-6 rounded-2xl bg-amber-50 p-4 font-bold text-amber-800">Kết quả tốt nhất: {best.score}% · {'⭐'.repeat(best.stars)}</p>}</div></section></main>;
  if (screen === 'guide') return <main className="mx-auto max-w-4xl px-4 py-10"><section className="rounded-[2.5rem] border-4 border-white bg-white p-7 shadow-2xl md:p-10"><div className="flex items-center gap-4"><span className="text-6xl">🦊</span><div><p className={`font-black ${text}`}>Cáo Cam nhắc bé</p><h1 className="text-3xl font-black">{config.guideTitle}</h1></div></div><div className="my-7 grid gap-4 sm:grid-cols-2">{config.tips.map(([icon, title, description], i) => <div key={title} className={`rounded-3xl p-5 ${i ? 'bg-amber-50' : tone}`}><b>{icon} {title}</b><p className="mt-2 font-semibold text-slate-600">{description}</p></div>)}</div><button onClick={() => setScreen('lesson')} className={`w-full rounded-2xl px-7 py-4 text-lg font-black text-white ${button}`}>Bắt đầu {size} câu</button></section></main>;
  if (screen === 'result') { const missed = results.filter((item) => !item.correctFirstTry).length; return <main className="mx-auto max-w-4xl px-4 py-10"><section className="rounded-[2.5rem] border-4 border-white bg-white p-7 text-center shadow-2xl md:p-10"><div className="text-7xl">🏅</div><p className={`mt-4 font-black ${text}`}>{reviewMode ? 'Hoàn thành lượt ôn lại' : 'Hoàn thành bài luyện'}</p><h1 className="mt-2 text-4xl font-black">{summary.score >= 90 ? 'Tuyệt vời!' : summary.score >= 70 ? 'Hoàn thành tốt!' : 'Mình cùng luyện thêm nhé!'}</h1><div className="mt-6 text-5xl">{[1, 2, 3].map((star) => <span key={star} className={star <= summary.stars ? '' : 'grayscale opacity-20'}>⭐</span>)}</div><div className="mt-7 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-sky-50 p-5"><b className="text-sky-700">Điểm số</b><p className="text-3xl font-black">{summary.score}%</p></div><div className="rounded-2xl bg-emerald-50 p-5"><b className="text-emerald-700">Đúng lần đầu</b><p className="text-3xl font-black">{summary.correct}/{results.length}</p></div><div className="rounded-2xl bg-amber-50 p-5"><b className="text-amber-700">Sao</b><p className="text-3xl font-black">{summary.stars}/3</p></div></div><div className="mt-7 overflow-hidden rounded-3xl border-2 text-left"><h2 className="bg-slate-50 px-5 py-4 text-xl font-black">Kết quả theo kĩ năng</h2>{summary.bySkill.map((item) => <div key={item.skillId} className="flex justify-between border-t px-5 py-4"><b>{GRADE5_SKILL_LABELS[item.skillId]}</b><b>{item.correct}/{item.total}</b></div>)}</div><ResultShare score={summary.score} correct={summary.correct} total={results.length} stars={summary.stars} attempts={results} /><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row">{missed > 0 && !reviewMode && <button onClick={reviewMistakes} className="rounded-2xl bg-orange-500 px-6 py-4 font-black text-white">Ôn lại {missed} câu</button>}<button onClick={() => prepare(size)} className={`rounded-2xl px-6 py-4 font-black text-white ${button}`}>Luyện bộ câu mới</button><a href="/lop-5" className="rounded-2xl border-2 px-6 py-4 font-black">Về lớp 5</a></div></section></main>; }
  const longAnswers = question.answers.some((answer) => String(answer).length > 14);
  return <main className="mx-auto max-w-5xl px-4 py-7"><header className="mb-5 flex items-center justify-between gap-6"><button onClick={() => setScreen('intro')} className="rounded-xl bg-white px-4 py-3 font-black shadow-sm">← Thoát</button><div className="text-right"><p className={`font-black ${text}`}>{reviewMode ? 'Ôn lại · ' : ''}Câu {index + 1}/{questions.length}</p><p className="text-sm font-bold text-slate-500">{GRADE5_SKILL_LABELS[question.skillId]}</p></div></header><div className="mb-6 h-3 overflow-hidden rounded-full bg-white"><div className={`h-full bg-gradient-to-r ${bar}`} style={{ width: `${(index + 1) / questions.length * 100}%` }} /></div><section className="rounded-[2.5rem] border-4 border-white bg-white p-5 shadow-2xl md:p-9"><div className="mb-6 flex items-center gap-4"><span className="text-5xl">{index % 2 ? '🐿️' : '🦊'}</span><div><p className={`font-black ${text}`}>{index % 2 ? 'Sóc Nâu hỏi' : 'Cáo Cam hỏi'}</p><h1 className="text-2xl font-black md:text-3xl">{question.instruction}</h1></div></div><Visual question={question} tone={tone} /><div className={`mt-6 grid gap-3 ${longAnswers ? 'sm:grid-cols-2' : question.answers.length === 3 ? 'grid-cols-3' : 'grid-cols-2 sm:grid-cols-4'}`}>{question.answers.map((answer, answerIndex) => <button key={`${String(answer)}-${answerIndex}`} disabled={canContinue} onClick={() => choose(answer)} className={`min-h-20 rounded-2xl border-4 px-3 py-4 text-lg font-black transition sm:text-xl ${answerClass(answer)}`}>{display(answer)}</button>)}</div>{selected !== null && !canContinue && <div className="mt-6 rounded-3xl border-2 border-orange-200 bg-orange-50 p-5"><h2 className="text-xl font-black text-orange-700">💡 Chưa đúng, mình xem lại nhé!</h2><p className="mt-2 font-semibold"><b>Gợi ý {hint}/3:</b> {question.hintSteps[Math.max(0, hint - 1)]}</p><button onClick={() => setSelected(null)} className="mt-4 rounded-xl bg-orange-500 px-5 py-3 font-black text-white">Chọn lại</button></div>}{canContinue && <div className="mt-6 rounded-3xl border-2 border-emerald-200 bg-emerald-50 p-5"><div className="flex flex-col items-center justify-between gap-4 sm:flex-row"><div><h2 className="text-xl font-black text-emerald-700">🎉 Chính xác!</h2><SolutionExplanation steps={question.hintSteps} conclusion={question.explanation} /></div><button onClick={next} className={`w-full rounded-2xl px-6 py-4 font-black text-white sm:w-auto ${button}`}>{index === questions.length - 1 ? 'Xem kết quả' : 'Câu tiếp theo →'}</button></div></div>}</section></main>;
}
