import { useEffect, useMemo, useState } from 'react';
import ResultShare from './ResultShare';
import { buildAdaptiveQuestionSet } from '../lib/learningProfile';
import { playCorrectSound, playFinalSound, playWrongSound } from '../lib/gameAudio';
import { GRADE3_STAGE3_SKILL_LABELS, generateGrade3Stage3Questions, type Grade3Stage3Answer, type Grade3Stage3Module, type Grade3Stage3Question, type Grade3Stage3SkillId } from '../lib/grade3Stage3QuestionGenerator';

type Screen = 'intro' | 'guide' | 'lesson' | 'result';
type PracticeSize = 5 | 10 | 15;
type QuestionResult = { questionId: string; skillId: Grade3Stage3SkillId; attempts: number; correctFirstTry: boolean };
type Props = { module: Grade3Stage3Module };

const CONFIG = {
  multiply1000: {
    number: 6, lessons: '36–40', title: 'Phép nhân, phép chia trong phạm vi 1 000', mascot: '🐻', accent: 'indigo',
    description: 'Nhân, chia số có ba chữ số; tính giá trị biểu thức và so sánh số lớn gấp mấy lần số bé.',
    topics: [['✖️', 'Nhân số ba chữ số'], ['➗', 'Chia số ba chữ số'], ['📝', 'Biểu thức số'], ['⚖️', 'So sánh số lần']],
    guide: [['🧮', 'Đặt tính', 'Tính từ hàng đơn vị khi nhân; chia lần lượt từ hàng trăm.'], ['📝', 'Thứ tự tính', 'Trong biểu thức, làm trong ngoặc trước; nhân chia trước cộng trừ.']],
  },
  semester1: {
    number: 7, lessons: '41–44', title: 'Ôn tập học kỳ I', mascot: '🐿️', accent: 'fuchsia',
    description: 'Ôn nhân chia đến 1 000, biểu thức số, hình học, đo lường và bài toán tổng hợp.',
    topics: [['✖️', 'Nhân và chia'], ['📝', 'Biểu thức'], ['📐', 'Hình học'], ['📏', 'Đo lường'], ['📖', 'Bài toán']],
    guide: [['🎯', 'Đọc đúng yêu cầu', 'Xác định câu hỏi thuộc phép tính, hình học hay đo lường.'], ['🔍', 'Kiểm tra kết quả', 'Ước lượng trước và thử lại bằng phép tính ngược.']],
  },
} as const;

const TONES = {
  indigo: { text: 'text-indigo-700', button: 'bg-indigo-600 hover:bg-indigo-700', bar: 'from-indigo-500 to-blue-600', pale: 'bg-indigo-50 text-indigo-900', shadow: 'shadow-indigo-100', selected: 'border-indigo-400 bg-indigo-50' },
  fuchsia: { text: 'text-fuchsia-700', button: 'bg-fuchsia-600 hover:bg-fuchsia-700', bar: 'from-fuchsia-500 to-purple-600', pale: 'bg-fuchsia-50 text-fuchsia-900', shadow: 'shadow-fuchsia-100', selected: 'border-fuchsia-400 bg-fuchsia-50' },
} as const;

const starsFor = (score: number) => score >= 90 ? 3 : score >= 70 ? 2 : 1;

function QuestionVisual({ question, tone }: { question: Grade3Stage3Question; tone: (typeof TONES)[keyof typeof TONES] }) {
  if (question.type === 'calculation') {
    if (question.operation === 'multiply') return <div className={`grid min-h-64 place-items-center rounded-3xl p-6 ${tone.pale}`}><div className="grid grid-cols-[3rem_8rem] text-right text-5xl font-black leading-tight"><span /><span>{question.left}</span><span className="text-indigo-600">×</span><span>{question.right}</span><span className="col-span-2 mt-2 border-t-4 border-slate-700 pt-3">?</span></div></div>;
    return <div className={`grid min-h-64 place-items-center rounded-3xl p-6 ${tone.pale}`}><div className="text-center"><p className="text-sm font-black uppercase tracking-widest opacity-60">Chia số có ba chữ số</p><div className="mt-5 flex items-start justify-center text-5xl font-black"><span className="border-r-4 border-slate-700 pr-4">{question.left}</span><span className="border-t-4 border-slate-700 px-5 pt-2">{question.right}</span></div>{question.remainder !== undefined && question.remainder > 0 && <p className="mt-5 font-bold opacity-70">Kết quả có thể có số dư</p>}</div></div>;
  }
  if (question.type === 'expression') return <div className={`grid min-h-64 place-items-center rounded-3xl p-6 ${tone.pale}`}><div className="text-center"><p className="text-sm font-black uppercase tracking-widest opacity-60">Tính đúng thứ tự</p><p className="mt-5 break-words text-4xl font-black sm:text-6xl">{question.expression}</p></div></div>;
  if (question.type === 'bars') return <div className={`space-y-6 rounded-3xl p-7 ${tone.pale}`}><div><div className="mb-2 flex justify-between font-black"><span>{question.labels[0]}</span><span>{question.small}</span></div><div className="h-12 rounded-2xl bg-amber-400" style={{ width: `${100 / question.times}%` }} /></div><div><div className="mb-2 flex justify-between font-black"><span>{question.labels[1]}</span><span>{question.large}</span></div><div className="flex gap-1">{Array.from({ length: question.times }).map((_, index) => <span key={index} className="h-12 flex-1 rounded-xl bg-indigo-500" />)}</div></div><p className="text-center text-sm font-black opacity-65">Các phần trong thanh dài bằng nhau</p></div>;
  if (question.type === 'context') return <div className={`grid min-h-64 place-items-center rounded-3xl p-6 text-center ${tone.pale}`}><div><div className="text-8xl">{question.icon}</div><p className="mt-4 text-2xl font-black">{question.visualTitle}</p><p className="mt-2 text-lg font-bold opacity-75">{question.visualText}</p></div></div>;
  if (question.type === 'diagram') {
    if (question.diagram === 'right-angle') return <div className={`grid min-h-64 place-items-center rounded-3xl p-6 ${tone.pale}`}><svg viewBox="0 0 320 230" className="w-full max-w-sm"><line x1="70" y1="180" x2="270" y2="180" stroke="#334155" strokeWidth="12" strokeLinecap="round" /><line x1="70" y1="180" x2="70" y2="30" stroke="#334155" strokeWidth="12" strokeLinecap="round" /><path d="M70 140 L110 140 L110 180" fill="none" stroke="#f59e0b" strokeWidth="7" /><text x="48" y="210" fontSize="28" fontWeight="900">A</text></svg></div>;
    if (question.diagram === 'circle') return <div className={`grid min-h-64 place-items-center rounded-3xl p-6 ${tone.pale}`}><svg viewBox="0 0 360 280" className="w-full max-w-md"><circle cx="180" cy="140" r="105" fill="white" stroke="#0284c7" strokeWidth="8" /><line x1="180" y1="140" x2="260" y2="72" stroke="#7c3aed" strokeWidth="9" /><circle cx="180" cy="140" r="9" fill="#0f172a" /><text x="160" y="175" fontSize="26" fontWeight="900">O</text><text x="270" y="68" fontSize="26" fontWeight="900">A</text></svg></div>;
    if (question.diagram === 'rectangle') return <div className={`grid min-h-64 place-items-center rounded-3xl p-6 ${tone.pale}`}><svg viewBox="0 0 420 260" className="w-full max-w-lg"><rect x="70" y="55" width="280" height="150" fill="#bbf7d0" stroke="#059669" strokeWidth="8" />{[[70,55],[350,55],[70,205],[350,205]].map(([x,y], index) => <path key={index} d={index === 0 ? `M${x} ${y+28} L${x+28} ${y+28} L${x+28} ${y}` : index === 1 ? `M${x-28} ${y} L${x-28} ${y+28} L${x} ${y+28}` : index === 2 ? `M${x} ${y-28} L${x+28} ${y-28} L${x+28} ${y}` : `M${x-28} ${y} L${x-28} ${y-28} L${x} ${y-28}`} fill="none" stroke="#f59e0b" strokeWidth="5" />)}</svg></div>;
    return <div className={`grid min-h-64 place-items-center rounded-3xl p-6 ${tone.pale}`}><div className="text-center"><div className="text-9xl">🎲</div><p className="mt-3 text-xl font-black">Khối lập phương</p></div></div>;
  }
  const max = question.measure === 'temperature' ? 50 : question.measure === 'length' ? 100 : 1000;
  const percent = Math.min(100, question.value / max * 100);
  return <div className={`grid min-h-64 place-items-center rounded-3xl p-6 ${tone.pale}`}><div className="w-full max-w-2xl text-center"><div className="text-8xl">{question.icon}</div><div className="relative mt-6 h-12 overflow-hidden rounded-full border-4 border-white bg-white shadow-inner"><div className="h-full rounded-full bg-gradient-to-r from-amber-400 to-rose-500" style={{ width: `${percent}%` }} />{Array.from({ length: 11 }).map((_, index) => <span key={index} className="absolute inset-y-0 w-0.5 bg-slate-600/35" style={{ left: `${index * 10}%` }} />)}</div><div className="mt-3 flex justify-between text-sm font-black"><span>0</span><span>{max / 2} {question.unit}</span><span>{max} {question.unit}</span></div></div></div>;
}

export default function Grade3Stage3Game({ module }: Props) {
  const config = CONFIG[module], tone = TONES[config.accent], storageKey = `trang-toan:lop-3:${module}:best-v1`;
  const [screen, setScreen] = useState<Screen>('intro'), [size, setSize] = useState<PracticeSize>(10), [questions, setQuestions] = useState<Grade3Stage3Question[]>([]), [index, setIndex] = useState(0), [selected, setSelected] = useState<Grade3Stage3Answer | null>(null), [attempts, setAttempts] = useState(0), [hint, setHint] = useState(0), [canContinue, setCanContinue] = useState(false), [results, setResults] = useState<QuestionResult[]>([]), [best, setBest] = useState<{ score: number; stars: number } | null>(null), [reviewMode, setReviewMode] = useState(false);
  useEffect(() => { setQuestions(generateGrade3Stage3Questions(module, 10)); const saved = localStorage.getItem(storageKey); if (saved) try { setBest(JSON.parse(saved)); } catch { localStorage.removeItem(storageKey); } }, [module, storageKey]);
  const question = questions[index], progress = questions.length ? (index + 1) / questions.length * 100 : 0;
  const summary = useMemo(() => { const correct = results.filter((result) => result.correctFirstTry).length, score = results.length ? Math.round(correct / results.length * 100) : 0; const bySkill = [...new Set(results.map((result) => result.skillId))].map((skillId) => { const list = results.filter((result) => result.skillId === skillId); return { skillId, total: list.length, correct: list.filter((result) => result.correctFirstTry).length }; }); return { correct, score, stars: starsFor(score), bySkill }; }, [results]);
  const reset = () => { setSelected(null); setAttempts(0); setHint(0); setCanContinue(false); };
  function prepare(nextSize: PracticeSize) { setSize(nextSize); setQuestions(buildAdaptiveQuestionSet(() => generateGrade3Stage3Questions(module, nextSize), nextSize)); setIndex(0); setResults([]); setReviewMode(false); reset(); setScreen('guide'); }
  function choose(answer: Grade3Stage3Answer) { if (!question || canContinue) return; const nextAttempts = attempts + 1; setAttempts(nextAttempts); setSelected(answer); if (answer === question.correctAnswer) { playCorrectSound(); setCanContinue(true); setResults((current) => [...current, { questionId: question.id, skillId: question.skillId, attempts: nextAttempts, correctFirstTry: nextAttempts === 1 }]); } else { playWrongSound(); setHint(Math.min(nextAttempts, 3)); } }
  function next() { if (index < questions.length - 1) { setIndex((value) => value + 1); reset(); return; } if (!reviewMode) { const correct = results.filter((result) => result.correctFirstTry).length, score = Math.round(correct / questions.length * 100), saved = { score, stars: starsFor(score) }; if (!best || score > best.score) { localStorage.setItem(storageKey, JSON.stringify(saved)); setBest(saved); } } playFinalSound(); setScreen('result'); }
  function review() { const ids = new Set(results.filter((result) => !result.correctFirstTry).map((result) => result.questionId)), missed = questions.filter((item) => ids.has(item.id)); if (!missed.length) return; setQuestions(missed); setIndex(0); setResults([]); setReviewMode(true); reset(); setScreen('lesson'); }
  function answerClass(answer: Grade3Stage3Answer) { if (selected === answer && answer !== question.correctAnswer) return 'border-red-400 bg-red-50 text-red-700'; if (canContinue && answer === question.correctAnswer) return 'border-emerald-400 bg-emerald-50 text-emerald-700'; return 'border-slate-200 bg-white text-slate-800 hover:-translate-y-1 hover:border-amber-300 hover:bg-amber-50'; }

  if (!questions.length) return <main className="grid min-h-screen place-items-center"><div className="text-center"><div className="text-7xl">{config.mascot}</div><p className={`mt-4 text-xl font-black ${tone.text}`}>Đang chuẩn bị bài luyện...</p></div></main>;
  if (screen === 'intro') return <main className="mx-auto max-w-5xl px-4 py-8 md:py-12"><a href="/lop-3" className="inline-flex rounded-xl bg-white px-4 py-3 font-black text-slate-600 shadow-sm">← Lớp 3</a><section className={`mt-6 overflow-hidden rounded-[2.5rem] border-4 border-white bg-white shadow-2xl ${tone.shadow}`}><div className={`bg-gradient-to-br ${tone.bar} p-8 text-white md:p-12`}><p className="font-black tracking-widest text-white/75">Mục {config.number} · Bài {config.lessons}</p><h1 className="mt-2 text-3xl font-black md:text-5xl">{config.title}</h1><p className="mt-4 max-w-3xl text-lg font-semibold leading-8 text-white/90">{config.description}</p></div><div className="p-6 md:p-10"><div className={`grid gap-3 sm:grid-cols-2 ${config.topics.length === 5 ? 'lg:grid-cols-5' : 'lg:grid-cols-4'}`}>{config.topics.map(([icon, label]) => <div key={label} className="rounded-2xl bg-slate-50 p-4 text-center"><div className="text-3xl">{icon}</div><p className="mt-2 font-black text-slate-700">{label}</p></div>)}</div><h2 className="mt-8 text-xl font-black">Chọn lượt luyện tập</h2><div className="mt-4 grid gap-4 md:grid-cols-3">{([[5, 'Luyện nhanh', 'Bao quát đủ nhóm kiến thức'], [10, 'Luyện chuẩn', 'Cân bằng tính toán và vận dụng'], [15, 'Thử thách', 'Nhiều biểu thức và bài toán hơn']] as const).map(([count, title, description]) => <button key={count} onClick={() => prepare(count)} className={`rounded-3xl border-4 p-5 text-left transition hover:-translate-y-1 ${count === 10 ? `${tone.selected} shadow-lg` : 'border-slate-100 bg-white hover:border-amber-300'}`}><span className={`text-sm font-black ${tone.text}`}>{count} câu</span><span className="mt-1 block text-xl font-black">{title}</span><span className="mt-2 block font-semibold text-slate-500">{description}</span></button>)}</div>{best && <p className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-4 font-bold text-amber-800">Kết quả tốt nhất: {best.score}% · {'⭐'.repeat(best.stars)}</p>}</div></section></main>;
  if (screen === 'guide') return <main className="mx-auto max-w-4xl px-4 py-10"><section className={`rounded-[2.5rem] border-4 border-white bg-white p-7 shadow-2xl ${tone.shadow} md:p-10`}><div className="flex items-start gap-4"><span className="text-6xl">{config.mascot}</span><div><p className={`font-black ${tone.text}`}>Chuẩn bị trước khi làm</p><h1 className="mt-1 text-3xl font-black">Tính đúng thứ tự, kiểm tra từng bước</h1></div></div><div className="my-7 grid gap-4 sm:grid-cols-2">{config.guide.map(([icon, title, description], guideIndex) => <div key={title} className={`rounded-3xl p-5 ${guideIndex ? 'bg-amber-50' : tone.pale}`}><p className="font-black">{icon} {title}</p><p className="mt-2 font-semibold text-slate-600">{description}</p></div>)}</div><button onClick={() => setScreen('lesson')} className={`w-full rounded-2xl px-7 py-4 text-lg font-black text-white ${tone.button}`}>Bắt đầu {size} câu</button></section></main>;
  if (screen === 'result') { const missed = results.filter((result) => !result.correctFirstTry).length; return <main className="mx-auto max-w-4xl px-4 py-10"><section className={`rounded-[2.5rem] border-4 border-white bg-white p-7 text-center shadow-2xl ${tone.shadow} md:p-10`}><div className="text-7xl">{reviewMode ? '💪' : '🏅'}</div><p className={`mt-4 font-black tracking-widest ${tone.text}`}>{reviewMode ? 'Hoàn thành lượt ôn lại' : 'Hoàn thành bài luyện tập'}</p><h1 className="mt-2 text-4xl font-black">{summary.score >= 90 ? 'Học kỳ I thật vững vàng!' : summary.score >= 70 ? 'Hoàn thành tốt!' : 'Mình cùng luyện thêm nhé!'}</h1><div className="mt-6 flex justify-center gap-3 text-5xl">{[1, 2, 3].map((star) => <span key={star} className={star <= summary.stars ? '' : 'grayscale opacity-20'}>⭐</span>)}</div><div className="mt-7 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-sky-50 p-5"><p className="font-black text-sky-700">Điểm số</p><p className="text-3xl font-black">{summary.score}%</p></div><div className="rounded-2xl bg-emerald-50 p-5"><p className="font-black text-emerald-700">Đúng lần đầu</p><p className="text-3xl font-black">{summary.correct}/{results.length}</p></div><div className="rounded-2xl bg-amber-50 p-5"><p className="font-black text-amber-700">Sao nhận được</p><p className="text-3xl font-black">{summary.stars}/3</p></div></div><div className="mt-7 overflow-hidden rounded-3xl border-2 border-slate-100 text-left"><h2 className="bg-slate-50 px-5 py-4 text-xl font-black">Kết quả theo kỹ năng</h2>{summary.bySkill.map((skill) => <div key={skill.skillId} className="grid grid-cols-[1fr_auto] gap-3 border-t px-5 py-4"><b>{GRADE3_STAGE3_SKILL_LABELS[skill.skillId]}</b><b>{skill.correct}/{skill.total}</b></div>)}</div><ResultShare score={summary.score} correct={summary.correct} total={results.length} stars={summary.stars} attempts={results} /><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row">{!reviewMode && missed > 0 && <button onClick={review} className="rounded-2xl bg-orange-500 px-6 py-4 font-black text-white">Ôn lại {missed} câu</button>}<button onClick={() => prepare(size)} className={`rounded-2xl px-6 py-4 font-black text-white ${tone.button}`}>Luyện bộ câu mới</button><a href="/lop-3" className="rounded-2xl border-2 border-slate-200 px-6 py-4 font-black">Về lớp 3</a></div></section></main>; }
  const longAnswers = question.answers.some((answer) => String(answer).length > 12);
  return <main className="mx-auto max-w-5xl px-4 py-7"><header className="mb-5 flex items-center justify-between gap-8"><button onClick={() => setScreen('intro')} className="shrink-0 rounded-xl bg-white px-4 py-3 font-black shadow-sm">← Thoát</button><div className="text-right"><p className={`font-black ${tone.text}`}>{reviewMode ? 'Ôn lại · ' : ''}Câu {index + 1}/{questions.length}</p><p className="text-sm font-bold text-slate-500">{GRADE3_STAGE3_SKILL_LABELS[question.skillId]}</p></div></header><div className="mb-6 h-3 overflow-hidden rounded-full bg-white"><div className={`h-full bg-gradient-to-r ${tone.bar}`} style={{ width: `${progress}%` }} /></div><section className={`rounded-[2.5rem] border-4 border-white bg-white p-5 shadow-2xl ${tone.shadow} md:p-9`}><div className="mb-6 flex items-center gap-4"><span className="text-5xl">{index % 2 ? '🐻' : '🐿️'}</span><div><p className={`font-black ${tone.text}`}>{index % 2 ? 'Gấu Mật hỏi' : 'Sóc Nâu hỏi'}</p><h1 className="mt-1 text-2xl font-black md:text-3xl">{question.instruction}</h1></div></div><QuestionVisual question={question} tone={tone} /><div className={`mt-6 grid gap-3 ${longAnswers ? 'sm:grid-cols-2' : question.answers.length === 2 ? 'grid-cols-2' : 'grid-cols-2 sm:grid-cols-4'}`}>{question.answers.map((answer) => <button key={String(answer)} disabled={canContinue} onClick={() => choose(answer)} className={`min-h-20 rounded-2xl border-4 px-3 py-4 text-lg font-black shadow-sm transition md:text-xl ${answerClass(answer)}`}>{answer}{question.type === 'measure' && typeof answer === 'number' ? ` ${question.unit}` : ''}</button>)}</div>{selected !== null && !canContinue && <div className="mt-6 rounded-3xl border-2 border-orange-200 bg-orange-50 p-5"><h2 className="text-xl font-black text-orange-700">💡 Chưa đúng, mình kiểm tra lại nhé!</h2><p className="mt-2 font-semibold"><b>Gợi ý {hint}/3:</b> {question.hintSteps[Math.max(0, hint - 1)]}</p><button onClick={() => setSelected(null)} className="mt-4 rounded-xl bg-orange-500 px-5 py-3 font-black text-white">Chọn lại đáp án</button></div>}{canContinue && <div className="mt-6 rounded-3xl border-2 border-emerald-200 bg-emerald-50 p-5"><div className="flex flex-col items-center justify-between gap-4 sm:flex-row"><div><h2 className="text-xl font-black text-emerald-700">🎉 Chính xác!</h2><p className="mt-1 font-semibold">{question.explanation}</p></div><button onClick={next} className={`w-full rounded-2xl px-6 py-4 font-black text-white sm:w-auto ${tone.button}`}>{index === questions.length - 1 ? 'Xem kết quả' : 'Câu tiếp theo →'}</button></div></div>}</section></main>;
}
